# Generated by Django 6.0.2 on 2026-02-08 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0071_venda_especie_volumes_venda_marca_volumes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConhecimentoTransporte',
            fields=[
                ('id_cte', models.AutoField(primary_key=True, serialize=False)),
                ('chave_cte', models.CharField(blank=True, max_length=44, null=True)),
                ('protocolo_cte', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_cte', models.IntegerField(blank=True, null=True)),
                ('serie_cte', models.IntegerField(default=1)),
                ('status_cte', models.CharField(default='PENDENTE', max_length=20)),
                ('xml_cte', models.TextField(blank=True, null=True)),
                ('cstat', models.IntegerField(blank=True, null=True)),
                ('xmotivo', models.CharField(blank=True, max_length=255, null=True)),
                ('data_emissao', models.DateTimeField(auto_now_add=True)),
                ('cfop', models.CharField(default='5353', max_length=4)),
                ('natureza_operacao', models.CharField(default='Transporte Rodoviário de Carga', max_length=60)),
                ('modelo', models.CharField(default='57', max_length=2)),
                ('tipo_cte', models.IntegerField(default=0)),
                ('modal', models.CharField(default='01', max_length=2)),
                ('tomador_servico', models.IntegerField(default=0)),
                ('produto_predominante', models.CharField(default='Diversos', max_length=60)),
                ('valor_carga', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('peso_bruto', models.DecimalField(decimal_places=4, default=0.0, max_digits=12)),
                ('peso_liquido', models.DecimalField(decimal_places=4, default=0.0, max_digits=12)),
                ('volumes', models.IntegerField(default=0)),
                ('valor_total_servico', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('valor_receber', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('rntrc', models.CharField(blank=True, max_length=20, null=True)),
                ('placa_veiculo', models.CharField(blank=True, max_length=8, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('destinatario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cte_destinatario', to='api.cliente')),
                ('expedidor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cte_expedidor', to='api.cliente')),
                ('recebedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cte_recebedor', to='api.cliente')),
                ('remetente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cte_remetente', to='api.cliente')),
                ('tomador_outros', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cte_tomador', to='api.cliente')),
            ],
            options={
                'db_table': 'cte_conhecimentos',
                'ordering': ['-id_cte'],
            },
        ),
        migrations.CreateModel(
            name='CTeComponenteValor',
            fields=[
                ('id_componente', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=30)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes_valor', to='cte.conhecimentotransporte')),
            ],
            options={
                'db_table': 'cte_componentes_valor',
            },
        ),
        migrations.CreateModel(
            name='CTeDocumentoOriginario',
            fields=[
                ('id_doc', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(default='NFE', max_length=10)),
                ('chave_nfe', models.CharField(blank=True, max_length=44, null=True)),
                ('cte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_originarios', to='cte.conhecimentotransporte')),
            ],
            options={
                'db_table': 'cte_documentos_orig',
            },
        ),
    ]
