# Generated by Django 6.0.2 on 2026-02-10 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cte', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conhecimentotransporte',
            name='cidade_destino_ibge',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='conhecimentotransporte',
            name='cidade_destino_nome',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='conhecimentotransporte',
            name='cidade_destino_uf',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='conhecimentotransporte',
            name='cidade_origem_ibge',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='conhecimentotransporte',
            name='cidade_origem_nome',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='conhecimentotransporte',
            name='cidade_origem_uf',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='conhecimentotransporte',
            name='condutor_cpf',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='conhecimentotransporte',
            name='condutor_nome',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='conhecimentotransporte',
            name='veiculo_renavam',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='conhecimentotransporte',
            name='veiculo_uf',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
