# Generated by Django 6.0.2 on 2026-02-10 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cte', '0002_conhecimentotransporte_cidade_destino_ibge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conhecimentotransporte',
            name='cst_icms',
            field=models.CharField(default='00', help_text='00, 20, 40, 60, 90, SN', max_length=3),
        ),
        migrations.AddField(
            model_name='conhecimentotransporte',
            name='nome_seguradora',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='conhecimentotransporte',
            name='numero_apolice',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='conhecimentotransporte',
            name='p_icms',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='conhecimentotransporte',
            name='resp_seguro',
            field=models.IntegerField(default=0, help_text='0-Remetente, 4-Emitente, 5-Tomador'),
        ),
        migrations.AddField(
            model_name='conhecimentotransporte',
            name='v_bc_icms',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='conhecimentotransporte',
            name='v_icms',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
