# Generated by Django 6.0.2 on 2026-02-10 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cte', '0003_conhecimentotransporte_cst_icms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conhecimentotransporte',
            name='componente_frete_peso',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Frete Peso'),
        ),
        migrations.AddField(
            model_name='conhecimentotransporte',
            name='componente_frete_valor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Frete Valor'),
        ),
        migrations.AddField(
            model_name='conhecimentotransporte',
            name='componente_outros',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Outros'),
        ),
        migrations.AddField(
            model_name='conhecimentotransporte',
            name='componente_pedagio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Pedágio'),
        ),
        migrations.AddField(
            model_name='conhecimentotransporte',
            name='componente_sec_cat',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Sec/Cat'),
        ),
    ]
