# Generated by Django 6.0.2 on 2026-02-10 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cte', '0004_conhecimentotransporte_componente_frete_peso_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTeDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('NFE', 'Nota Fiscal Eletrônica'), ('NF', 'Nota Fiscal (Papel)'), ('OUTROS', 'Outros')], default='NFE', max_length=10)),
                ('chave_nfe', models.CharField(blank=True, help_text='Chave de Acesso da NFe (44 digitos)', max_length=44, null=True)),
                ('cte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='cte.conhecimentotransporte')),
            ],
        ),
    ]
