# Generated by Django 6.0.2 on 2026-02-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cte', '0005_ctedocumento'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='conhecimentotransporte',
                    name='tipo_servico',
                    field=models.IntegerField(default=0),
                ),
            ],
            database_operations=[],
        ),
    ]
