# Generated by Django 6.0.2 on 2026-02-12 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cte', '0006_conhecimentotransporte_tipo_servico'),
    ]

    operations = [
        migrations.AddField(
            model_name='conhecimentotransporte',
            name='qrcode_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
