# Generated by Django 6.0.2 on 2026-05-29 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cte', '0007_conhecimentotransporte_qrcode_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='conhecimentotransporte',
            name='ciot',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='conhecimentotransporte',
            name='ciot_cpf_cnpj',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
