# Generated by Django 6.0.4 on 2026-07-03 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cte', '0008_conhecimentotransporte_ciot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conhecimentotransporte',
            name='ref_cte',
            field=models.CharField(blank=True, help_text='Chave do CT-e que está sendo complementado', max_length=44, null=True),
        ),
    ]
