# Generated by Django 6.0.4 on 2026-07-20 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cte', '0009_conhecimentotransporte_ref_cte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conhecimentotransporte',
            name='ref_cte',
        ),
    ]
