# Generated by Django 6.0.4 on 2026-07-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cte', '0010_remove_conhecimentotransporte_ref_cte'),
    ]

    operations = [
        migrations.AddField(
            model_name='conhecimentotransporte',
            name='c_class_trib',
            field=models.CharField(blank=True, default='000000', help_text='Código de Classificação Tributária', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='conhecimentotransporte',
            name='cbs_aliq',
            field=models.DecimalField(decimal_places=4, default=0.9, help_text='Alíquota CBS (%)', max_digits=7),
        ),
        migrations.AddField(
            model_name='conhecimentotransporte',
            name='cbs_bc',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='conhecimentotransporte',
            name='cbs_cst',
            field=models.CharField(blank=True, default='01', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='conhecimentotransporte',
            name='cst_ibs_cbs',
            field=models.CharField(blank=True, default='01', help_text='CST IBS/CBS', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='conhecimentotransporte',
            name='ibs_aliq',
            field=models.DecimalField(decimal_places=4, default=0.1, help_text='Alíquota IBS total (%)', max_digits=7),
        ),
        migrations.AddField(
            model_name='conhecimentotransporte',
            name='ibs_aliq_mun',
            field=models.DecimalField(decimal_places=4, default=0.0, help_text='Alíquota IBS Mun (%)', max_digits=7),
        ),
        migrations.AddField(
            model_name='conhecimentotransporte',
            name='ibs_aliq_uf',
            field=models.DecimalField(decimal_places=4, default=0.1, help_text='Alíquota IBS UF (%)', max_digits=7),
        ),
        migrations.AddField(
            model_name='conhecimentotransporte',
            name='ibs_bc',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='conhecimentotransporte',
            name='ibs_cst',
            field=models.CharField(blank=True, default='01', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='conhecimentotransporte',
            name='valor_cbs',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='conhecimentotransporte',
            name='valor_ibs',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
