# Generated by Django 5.2.7 on 2025-10-21 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nome_razao_social', models.CharField(max_length=255)),
                ('nome_fantasia', models.CharField(blank=True, max_length=255, null=True)),
                ('cpf_cnpj', models.CharField(max_length=18, unique=True)),
                ('inscricao_estadual', models.CharField(blank=True, max_length=20, null=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('numero', models.CharField(blank=True, max_length=20, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('limite_credito', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GrupoProduto',
            fields=[
                ('id_grupo', models.AutoField(primary_key=True, serialize=False)),
                ('nome_grupo', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'grupos_produto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id_produto', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_produto', models.CharField(max_length=50, unique=True)),
                ('nome_produto', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('unidade_medida', models.CharField(blank=True, max_length=10, null=True)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('classificacao', models.CharField(blank=True, max_length=15, null=True)),
                ('ncm', models.CharField(blank=True, max_length=10, null=True)),
                ('tributacao_info', models.TextField(blank=True, null=True)),
                ('estoque_atual', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('valor_custo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('valor_compra', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('valor_venda', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('observacoes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'produtos',
                'managed': False,
            },
        ),
    ]
