# Generated by Django 6.0.2 on 2026-05-25 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        ('mdfe', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mapacarga',
            name='id_mdfe',
            field=models.ForeignKey(blank=True, db_column='id_mdfe', help_text='MDF-e gerado a partir deste mapa', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mapas_carga', to='mdfe.manifestoeletronico'),
        ),
        migrations.AddField(
            model_name='mapacarga',
            name='id_motorista',
            field=models.ForeignKey(blank=True, db_column='id_motorista_id', help_text='Vendedor que atua como motorista', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mapas_motorista', to='api.vendedor'),
        ),
        migrations.AddField(
            model_name='mapacarga',
            name='id_veiculo',
            field=models.ForeignKey(blank=True, db_column='id_veiculo', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mapas_carga', to='api.veiculo'),
        ),
        migrations.AddField(
            model_name='mapacargaitem',
            name='id_mapa',
            field=models.ForeignKey(db_column='id_mapa', on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='api.mapacarga'),
        ),
        migrations.AddField(
            model_name='marketplaceproduto',
            name='marketplace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos_vinculados', to='api.marketplaceconfig'),
        ),
        migrations.AddField(
            model_name='marketplaceproduto',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_marketplace', to='api.produto'),
        ),
        migrations.AddField(
            model_name='ocorrenciafuncionario',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias', to='api.funcionario'),
        ),
        migrations.AddField(
            model_name='ocorrenciafuncionario',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocorrencias_registradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='operacao',
            name='id_numeracao',
            field=models.ForeignKey(blank=True, db_column='id_numeracao', help_text='Numeração padrão utilizada por esta operação', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operacoes', to='api.numeracao'),
        ),
        migrations.AddField(
            model_name='financeiroconta',
            name='id_operacao',
            field=models.ForeignKey(blank=True, db_column='id_operacao', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.operacao'),
        ),
        migrations.AddField(
            model_name='contratorecorrencia',
            name='operacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_recorrencia', to='api.operacao'),
        ),
        migrations.AddField(
            model_name='conjuntooperacao',
            name='operacoes',
            field=models.ManyToManyField(help_text='Operações que fazem parte deste conjunto', related_name='conjuntos', to='api.operacao'),
        ),
        migrations.AddField(
            model_name='operacaonumeracao',
            name='id_operacao',
            field=models.ForeignKey(db_column='id_operacao', on_delete=django.db.models.deletion.CASCADE, related_name='numeracoes', to='api.operacao'),
        ),
        migrations.AddField(
            model_name='ordemproducao',
            name='criado_por',
            field=models.ForeignKey(blank=True, db_column='id_criado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordemproducao',
            name='deposito',
            field=models.ForeignKey(db_column='id_deposito', help_text='Depósito de onde saem os insumos e onde entra o produto acabado.', on_delete=django.db.models.deletion.PROTECT, related_name='ordens_producao', to='api.deposito'),
        ),
        migrations.AddField(
            model_name='ordemproducao',
            name='produto',
            field=models.ForeignKey(db_column='id_produto', help_text='Produto acabado a ser fabricado.', on_delete=django.db.models.deletion.PROTECT, related_name='ordens_producao', to='api.produto'),
        ),
        migrations.AddField(
            model_name='lead',
            name='origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='api.origemlead'),
        ),
        migrations.AddField(
            model_name='osassinatura',
            name='id_os',
            field=models.OneToOneField(db_column='id_os', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='assinatura', to='api.ordemservico'),
        ),
        migrations.AddField(
            model_name='osfoto',
            name='id_os',
            field=models.ForeignKey(db_column='id_os', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='api.ordemservico'),
        ),
        migrations.AddField(
            model_name='parcelarecorrencia',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='api.contratorecorrencia'),
        ),
        migrations.AddField(
            model_name='pet',
            name='id_cliente',
            field=models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='api.cliente'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='id_pet',
            field=models.ForeignKey(db_column='id_pet', on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='api.pet'),
        ),
        migrations.AddField(
            model_name='precoconcorrente',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precos_concorrencia', to='api.produto'),
        ),
        migrations.AddField(
            model_name='produtocomplementar',
            name='produto',
            field=models.ForeignKey(db_column='id_produto', on_delete=django.db.models.deletion.CASCADE, related_name='complementares', to='api.produto'),
        ),
        migrations.AddField(
            model_name='produtocomplementar',
            name='produto_complementar',
            field=models.ForeignKey(db_column='id_produto_complementar', on_delete=django.db.models.deletion.CASCADE, related_name='complementar_de', to='api.produto'),
        ),
        migrations.AddField(
            model_name='produtosimilar',
            name='produto',
            field=models.ForeignKey(db_column='id_produto', on_delete=django.db.models.deletion.CASCADE, related_name='similares', to='api.produto'),
        ),
        migrations.AddField(
            model_name='produtosimilar',
            name='produto_similar',
            field=models.ForeignKey(db_column='id_produto_similar', on_delete=django.db.models.deletion.CASCADE, related_name='similar_de', to='api.produto'),
        ),
        migrations.AddField(
            model_name='produtovariacao',
            name='id_produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variacoes', to='api.produto'),
        ),
        migrations.AddField(
            model_name='estoque',
            name='id_variacao',
            field=models.ForeignKey(blank=True, db_column='id_variacao', help_text='Variação específica (Grade)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.produtovariacao'),
        ),
        migrations.AddField(
            model_name='produtovariacaocombinacao',
            name='id_variacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.produtovariacao'),
        ),
        migrations.AddField(
            model_name='promocao',
            name='criado_por',
            field=models.ForeignKey(blank=True, db_column='criado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promocoes_criadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promocaoproduto',
            name='id_produto',
            field=models.ForeignKey(db_column='id_produto', on_delete=django.db.models.deletion.CASCADE, to='api.produto'),
        ),
        migrations.AddField(
            model_name='promocaoproduto',
            name='id_promocao',
            field=models.ForeignKey(db_column='id_promocao', on_delete=django.db.models.deletion.CASCADE, related_name='promocao_produtos', to='api.promocao'),
        ),
        migrations.AddField(
            model_name='promocao',
            name='produtos',
            field=models.ManyToManyField(help_text='Produtos em promoção', through='api.PromocaoProduto', to='api.produto'),
        ),
        migrations.AddField(
            model_name='quarto',
            name='comodidades',
            field=models.ManyToManyField(blank=True, db_table='hotel_quarto_comodidade', related_name='quartos', to='api.comodidade'),
        ),
        migrations.AddField(
            model_name='recebimentocartao',
            name='id_financeiro',
            field=models.ForeignKey(blank=True, db_column='id_financeiro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recebimentos_cartao', to='api.financeiroconta'),
        ),
        migrations.AddField(
            model_name='registroponto',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pontos', to='api.funcionario'),
        ),
        migrations.AddField(
            model_name='registroponto',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pontos_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='regrafiscal',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Empresa à qual a regra pertence. Vazio = regra global.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regras_fiscais', to='api.empresaconfig'),
        ),
        migrations.AddField(
            model_name='regrafiscalreforma',
            name='produto',
            field=models.ForeignKey(help_text='Produto vinculado à regra fiscal', on_delete=django.db.models.deletion.CASCADE, related_name='regras_reforma', to='api.produto'),
        ),
        migrations.AddField(
            model_name='regrafiscalreforma',
            name='usuario_cadastro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regras_reforma_criadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reserva',
            name='hospede',
            field=models.ForeignKey(db_column='hospede_id', on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='api.cliente'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='quarto',
            field=models.ForeignKey(db_column='quarto_id', on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='api.quarto'),
        ),
        migrations.AddField(
            model_name='consumoquarto',
            name='reserva',
            field=models.ForeignKey(db_column='reserva_id', on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='api.reserva'),
        ),
        migrations.AddField(
            model_name='saasclientecontrato',
            name='saas_cliente',
            field=models.ForeignKey(db_column='saas_cliente_id', on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='api.saascliente'),
        ),
        migrations.AddField(
            model_name='saasclientemensalidade',
            name='saas_cliente',
            field=models.ForeignKey(db_column='saas_cliente_id', on_delete=django.db.models.deletion.CASCADE, related_name='mensalidades', to='api.saascliente'),
        ),
        migrations.AddField(
            model_name='financeiroconta',
            name='id_safra',
            field=models.ForeignKey(blank=True, db_column='id_safra', help_text='Vínculo com Safra (Agro)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.safra'),
        ),
        migrations.AddField(
            model_name='contratoagricola',
            name='id_safra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.safra'),
        ),
        migrations.AddField(
            model_name='sessaoagendamento',
            name='id_agendamento',
            field=models.ForeignKey(db_column='id_agendamento', on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to='api.agendamento'),
        ),
        migrations.AddField(
            model_name='splitpaymentconfig',
            name='empresa',
            field=models.OneToOneField(help_text='Empresa vinculada à configuração', on_delete=django.db.models.deletion.CASCADE, related_name='split_payment_config', to='api.empresaconfig'),
        ),
        migrations.AddField(
            model_name='sugestaocfop',
            name='id_operacao',
            field=models.ForeignKey(db_column='id_operacao', help_text='Operação à qual esta sugestão de CFOP está vinculada', on_delete=django.db.models.deletion.CASCADE, related_name='sugestoes_cfop', to='api.operacao'),
        ),
        migrations.AddField(
            model_name='quarto',
            name='tipo',
            field=models.ForeignKey(db_column='tipo_id', on_delete=django.db.models.deletion.PROTECT, related_name='quartos', to='api.tipoquarto'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='id_tipo_servico',
            field=models.ForeignKey(blank=True, db_column='id_tipo_servico', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.tiposervico'),
        ),
        migrations.AddField(
            model_name='tipotributacao',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Empresa vinculada (vazio = perfil global)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipos_tributacao', to='api.empresaconfig'),
        ),
        migrations.AddField(
            model_name='transacaomppoint',
            name='config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.configuracaomercadopago'),
        ),
        migrations.AddField(
            model_name='transacaomppoint',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacoes_mp_criadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tributacaoproduto',
            name='produto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tributacao_detalhada', to='api.produto'),
        ),
        migrations.AddField(
            model_name='tributacaouf',
            name='tipo_tributacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliquotas_uf', to='api.tipotributacao'),
        ),
        migrations.AddField(
            model_name='trocaitem',
            name='troca',
            field=models.ForeignKey(db_column='id_troca', on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='api.troca'),
        ),
        migrations.AddField(
            model_name='useratalho',
            name='user',
            field=models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, related_name='atalhos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='valoratributovariacao',
            name='id_atributo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='api.atributovariacao'),
        ),
        migrations.AddField(
            model_name='produtovariacaocombinacao',
            name='id_valor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.valoratributovariacao'),
        ),
        migrations.AddField(
            model_name='produtovariacao',
            name='valores',
            field=models.ManyToManyField(through='api.ProdutoVariacaoCombinacao', to='api.valoratributovariacao'),
        ),
        migrations.AddField(
            model_name='venda',
            name='criado_por',
            field=models.ForeignKey(blank=True, db_column='criado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='venda',
            name='id_cliente',
            field=models.ForeignKey(blank=True, db_column='id_cliente', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.cliente'),
        ),
        migrations.AddField(
            model_name='venda',
            name='id_operacao',
            field=models.ForeignKey(blank=True, db_column='id_operacao', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.operacao'),
        ),
        migrations.AddField(
            model_name='venda',
            name='id_venda_faturamento',
            field=models.ForeignKey(blank=True, db_column='id_venda_faturamento', help_text='Venda NF-e/NFC-e gerada ao faturar esta venda', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas_faturadas', to='api.venda'),
        ),
        migrations.AddField(
            model_name='venda',
            name='id_vendedor1',
            field=models.ForeignKey(blank=True, db_column='id_vendedor1', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas_vendedor1', to='api.vendedor'),
        ),
        migrations.AddField(
            model_name='venda',
            name='id_vendedor2',
            field=models.ForeignKey(blank=True, db_column='id_vendedor2', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas_vendedor2', to='api.vendedor'),
        ),
        migrations.AddField(
            model_name='venda',
            name='transportadora',
            field=models.ForeignKey(blank=True, db_column='id_transportadora', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas_transportadas', to='api.cliente'),
        ),
        migrations.AddField(
            model_name='venda',
            name='venda_futura_destino',
            field=models.ForeignKey(blank=True, db_column='venda_futura_destino', help_text='Venda de entrega futura gerada a partir desta venda', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas_origem_futuras', to='api.venda'),
        ),
        migrations.AddField(
            model_name='venda',
            name='venda_futura_origem',
            field=models.ForeignKey(blank=True, db_column='venda_futura_origem', help_text='Venda de origem que gerou esta entrega futura', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas_futuras_destino', to='api.venda'),
        ),
        migrations.AddField(
            model_name='transacaomppoint',
            name='id_venda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacoes_mp_point', to='api.venda'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='venda',
            field=models.ForeignKey(blank=True, db_column='venda_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='api.venda'),
        ),
        migrations.AddField(
            model_name='recebimentocartao',
            name='id_venda',
            field=models.ForeignKey(blank=True, db_column='id_venda', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recebimentos_cartao', to='api.venda'),
        ),
        migrations.AddField(
            model_name='notafiscalreferenciada',
            name='id_venda',
            field=models.ForeignKey(db_column='id_venda', help_text='Venda (NF-e/NFC-e) que referencia documentos anteriores', on_delete=django.db.models.deletion.CASCADE, related_name='notas_referenciadas', to='api.venda'),
        ),
        migrations.AddField(
            model_name='mapacargaitem',
            name='id_venda',
            field=models.ForeignKey(db_column='id_venda', on_delete=django.db.models.deletion.PROTECT, related_name='mapas_carga', to='api.venda'),
        ),
        migrations.AddField(
            model_name='cashback',
            name='id_venda_origem',
            field=models.ForeignKey(blank=True, db_column='id_venda_origem', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashback_gerado', to='api.venda'),
        ),
        migrations.AddField(
            model_name='cashback',
            name='id_venda_utilizado',
            field=models.ForeignKey(blank=True, db_column='id_venda_utilizado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashback_utilizado', to='api.venda'),
        ),
        migrations.AddField(
            model_name='vendaentregalog',
            name='id_venda',
            field=models.ForeignKey(db_column='id_venda', on_delete=django.db.models.deletion.CASCADE, related_name='logs_entrega', to='api.venda'),
        ),
        migrations.AddField(
            model_name='vendaentregalog',
            name='usuario',
            field=models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendaitem',
            name='id_lote',
            field=models.ForeignKey(blank=True, db_column='id_lote', help_text='Lote utilizado nesta venda', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='venda_itens', to='api.loteproduto'),
        ),
        migrations.AddField(
            model_name='vendaitem',
            name='id_produto',
            field=models.ForeignKey(blank=True, db_column='id_produto', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.produto'),
        ),
        migrations.AddField(
            model_name='vendaitem',
            name='id_variacao',
            field=models.ForeignKey(blank=True, db_column='id_variacao', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.produtovariacao'),
        ),
        migrations.AddField(
            model_name='vendaitem',
            name='id_venda',
            field=models.ForeignKey(db_column='id_venda', on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='api.venda'),
        ),
        migrations.AddField(
            model_name='veiculonovo',
            name='id_venda_item',
            field=models.OneToOneField(db_column='id_venda_item', help_text='Item da venda que contém este veículo', on_delete=django.db.models.deletion.CASCADE, related_name='veiculo_novo', to='api.vendaitem'),
        ),
        migrations.AddField(
            model_name='vendasplitpayment',
            name='aprovacao',
            field=models.ForeignKey(blank=True, help_text='Solicitação de aprovação via WhatsApp', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='splits_aprovados', to='api.solicitacaoaprovacao'),
        ),
        migrations.AddField(
            model_name='vendasplitpayment',
            name='venda',
            field=models.OneToOneField(help_text='Venda vinculada ao split', on_delete=django.db.models.deletion.CASCADE, related_name='split_payment', to='api.venda'),
        ),
        migrations.AddField(
            model_name='webhookpixlog',
            name='cobranca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_logs', to='api.cobrancapix'),
        ),
        migrations.AddIndex(
            model_name='aluguel',
            index=models.Index(fields=['numero_aluguel'], name='alugueis_numero__1b43ed_idx'),
        ),
        migrations.AddIndex(
            model_name='aluguel',
            index=models.Index(fields=['id_cliente', 'status'], name='alugueis_id_clie_5d31b4_idx'),
        ),
        migrations.AddIndex(
            model_name='aluguel',
            index=models.Index(fields=['data_inicio'], name='alugueis_data_in_80b97d_idx'),
        ),
        migrations.AddIndex(
            model_name='aluguel',
            index=models.Index(fields=['status'], name='alugueis_status_fdd2b8_idx'),
        ),
        migrations.AddIndex(
            model_name='categoriamercadologica',
            index=models.Index(fields=['nivel', 'ativo'], name='categorias__nivel_58b301_idx'),
        ),
        migrations.AddIndex(
            model_name='categoriamercadologica',
            index=models.Index(fields=['pai', 'nivel'], name='categorias__pai_id_f8077b_idx'),
        ),
        migrations.AddIndex(
            model_name='cobrancapix',
            index=models.Index(fields=['txid'], name='pix_cobranc_txid_ae9220_idx'),
        ),
        migrations.AddIndex(
            model_name='cobrancapix',
            index=models.Index(fields=['status'], name='pix_cobranc_status_4af061_idx'),
        ),
        migrations.AddIndex(
            model_name='cobrancapix',
            index=models.Index(fields=['id_venda'], name='pix_cobranc_id_vend_bee654_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cotacaofornecedor',
            unique_together={('id_cotacao', 'id_fornecedor')},
        ),
        migrations.AlterUniqueTogether(
            name='cotacaoresposta',
            unique_together={('id_cotacao_fornecedor', 'id_cotacao_item')},
        ),
        migrations.AddIndex(
            model_name='creditocliente',
            index=models.Index(fields=['id_cliente', 'status'], name='creditos_cl_id_clie_1bdb1e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='emailconfig',
            unique_together={('empresa', 'provider', 'from_email')},
        ),
        migrations.AlterUniqueTogether(
            name='emailtemplate',
            unique_together={('empresa', 'slug')},
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['destinatario_email', 'status'], name='email_logs_destina_9214ea_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['campanha', 'status'], name='email_logs_campanh_4352a0_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['provider_message_id'], name='email_logs_provide_200de5_idx'),
        ),
        migrations.AddIndex(
            model_name='aluguelitem',
            index=models.Index(fields=['id_aluguel'], name='alugueis_it_id_alug_df003d_idx'),
        ),
        migrations.AddIndex(
            model_name='aluguelitem',
            index=models.Index(fields=['id_equipamento', 'status'], name='alugueis_it_id_equi_dadf05_idx'),
        ),
        migrations.AddIndex(
            model_name='aluguelitem',
            index=models.Index(fields=['data_devolucao_prevista'], name='alugueis_it_data_de_e08e42_idx'),
        ),
        migrations.AddIndex(
            model_name='filawhatsapp',
            index=models.Index(fields=['status', 'prioridade'], name='whatsapp_fi_status_0022e0_idx'),
        ),
        migrations.AddIndex(
            model_name='filawhatsapp',
            index=models.Index(fields=['data_criacao'], name='whatsapp_fi_data_cr_57412a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='holerite',
            unique_together={('funcionario', 'mes', 'ano')},
        ),
        migrations.AddField(
            model_name='informacaoprodutoapi',
            name='usuario_sincronizacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='composicaoproduto',
            unique_together={('produto_acabado', 'insumo')},
        ),
        migrations.AddIndex(
            model_name='logauditoria',
            index=models.Index(fields=['-data_hora'], name='log_auditor_data_ho_b3d8dc_idx'),
        ),
        migrations.AddIndex(
            model_name='logauditoria',
            index=models.Index(fields=['usuario', '-data_hora'], name='log_auditor_id_user_8c5abb_idx'),
        ),
        migrations.AddIndex(
            model_name='logauditoria',
            index=models.Index(fields=['modulo', '-data_hora'], name='log_auditor_modulo_ed306e_idx'),
        ),
        migrations.AddIndex(
            model_name='logauditoria',
            index=models.Index(fields=['tipo_acao', '-data_hora'], name='log_auditor_tipo_ac_bcca8c_idx'),
        ),
        migrations.AddIndex(
            model_name='manifestacaonfe',
            index=models.Index(fields=['chave_nfe'], name='manifestaca_chave_n_542ad5_idx'),
        ),
        migrations.AddIndex(
            model_name='manifestacaonfe',
            index=models.Index(fields=['status'], name='manifestaca_status_f83233_idx'),
        ),
        migrations.AddIndex(
            model_name='manifestacaonfe',
            index=models.Index(fields=['tipo_evento'], name='manifestaca_tipo_ev_30694d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='marketplaceproduto',
            unique_together={('marketplace', 'produto')},
        ),
        migrations.AddIndex(
            model_name='ocorrenciafuncionario',
            index=models.Index(fields=['funcionario', 'data_inicio'], name='rh_ocorrenc_funcion_9d9af3_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status'], name='crm_lead_status_2c1bc7_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['etapa'], name='crm_lead_etapa_i_7f693f_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['responsavel'], name='crm_lead_respons_6388f8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='parcelarecorrencia',
            unique_together={('contrato', 'competencia')},
        ),
        migrations.AddIndex(
            model_name='precoconcorrente',
            index=models.Index(fields=['ean', 'data_coleta'], name='precos_conc_ean_750f35_idx'),
        ),
        migrations.AddIndex(
            model_name='precoconcorrente',
            index=models.Index(fields=['produto', 'data_coleta'], name='precos_conc_produto_092499_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='produtocomplementar',
            unique_together={('produto', 'produto_complementar')},
        ),
        migrations.AlterUniqueTogether(
            name='produtosimilar',
            unique_together={('produto', 'produto_similar')},
        ),
        migrations.AlterUniqueTogether(
            name='estoque',
            unique_together={('id_produto', 'id_deposito')},
        ),
        migrations.AlterUniqueTogether(
            name='promocaoproduto',
            unique_together={('id_promocao', 'id_produto')},
        ),
        migrations.AddIndex(
            model_name='registroponto',
            index=models.Index(fields=['funcionario', 'data_hora'], name='rh_registro_funcion_9c9aa9_idx'),
        ),
        migrations.AddIndex(
            model_name='regrafiscal',
            index=models.Index(fields=['empresa', 'ncm_codigo', 'tipo_operacao'], name='regras_fisc_empresa_6ea746_idx'),
        ),
        migrations.AddIndex(
            model_name='regrafiscal',
            index=models.Index(fields=['tipo_produto_reform'], name='regras_fisc_tipo_pr_981237_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='regrafiscal',
            unique_together={('empresa', 'ncm_codigo', 'tipo_operacao', 'uf_destino', 'uf_origem', 'tipo_cliente')},
        ),
        migrations.AddIndex(
            model_name='regrafiscalreforma',
            index=models.Index(fields=['ncm', 'vigencia_inicio'], name='regras_fisc_ncm_d7881e_idx'),
        ),
        migrations.AddIndex(
            model_name='regrafiscalreforma',
            index=models.Index(fields=['produto', 'uf_aplicacao'], name='regras_fisc_produto_0623bd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sessaoagendamento',
            unique_together={('id_agendamento', 'numero_sessao')},
        ),
        migrations.AlterUniqueTogether(
            name='sugestaocfop',
            unique_together={('id_operacao', 'tipo_destino')},
        ),
        migrations.AddIndex(
            model_name='agendamento',
            index=models.Index(fields=['id_cliente', 'data_agendamento'], name='petshop_age_id_clie_07d9a3_idx'),
        ),
        migrations.AddIndex(
            model_name='agendamento',
            index=models.Index(fields=['id_pet', 'status'], name='petshop_age_id_pet_8eb8f7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tipotributacao',
            unique_together={('empresa', 'nome')},
        ),
        migrations.AlterUniqueTogether(
            name='tributacaouf',
            unique_together={('tipo_tributacao', 'uf_destino')},
        ),
        migrations.AlterUniqueTogether(
            name='useratalho',
            unique_together={('user', 'tecla')},
        ),
        migrations.AddIndex(
            model_name='notafiscalreferenciada',
            index=models.Index(fields=['id_venda'], name='notas_fisca_id_vend_9a865c_idx'),
        ),
        migrations.AddIndex(
            model_name='notafiscalreferenciada',
            index=models.Index(fields=['chave_acesso'], name='notas_fisca_chave_a_51c576_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mapacargaitem',
            unique_together={('id_mapa', 'id_venda')},
        ),
        migrations.AddIndex(
            model_name='cashback',
            index=models.Index(fields=['id_cliente', 'ativo'], name='cashbacks_id_clie_0f36d4_idx'),
        ),
        migrations.AddIndex(
            model_name='cashback',
            index=models.Index(fields=['data_validade'], name='cashbacks_data_va_61ebf0_idx'),
        ),
        migrations.AddIndex(
            model_name='vendasplitpayment',
            index=models.Index(fields=['venda', 'split_realizado'], name='vendas_spli_venda_i_4f0623_idx'),
        ),
        migrations.AddIndex(
            model_name='vendasplitpayment',
            index=models.Index(fields=['split_data_hora'], name='vendas_spli_split_d_9ebcc4_idx'),
        ),
    ]
