# Generated by Django 5.2.7 on 2025-10-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceiroConta',
            fields=[
                ('id_conta', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_conta', models.CharField(max_length=7)),
                ('descricao', models.CharField(max_length=255)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_pago', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('data_emissao', models.DateField(auto_now_add=True)),
                ('data_vencimento', models.DateField()),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('status_conta', models.CharField(default='Pendente', max_length=9)),
                ('centro_custo', models.CharField(blank=True, max_length=100, null=True)),
                ('forma_pagamento', models.CharField(blank=True, max_length=50, null=True)),
                ('id_venda_origem', models.IntegerField(blank=True, null=True)),
                ('id_compra_origem', models.IntegerField(blank=True, null=True)),
                ('id_os_origem', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'financeiro_contas',
                'managed': False,
            },
        ),
    ]
