# Generated by Django 5.2.7 on 2025-10-21 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_financeiroconta'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroCusto',
            fields=[
                ('id_centro_custo', models.AutoField(primary_key=True, serialize=False)),
                ('nome_centro_custo', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'centro_custo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContaBancaria',
            fields=[
                ('id_conta_bancaria', models.AutoField(primary_key=True, serialize=False)),
                ('nome_conta', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'contas_bancarias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_departamento', models.AutoField(primary_key=True, serialize=False)),
                ('nome_departamento', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'departamentos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Operacao',
            fields=[
                ('id_operacao', models.AutoField(primary_key=True, serialize=False)),
                ('nome_operacao', models.CharField(max_length=100)),
                ('empresa', models.CharField(blank=True, max_length=100, null=True)),
                ('transacao', models.CharField(blank=True, max_length=6, null=True)),
                ('modelo_documento', models.CharField(blank=True, max_length=10, null=True)),
                ('emitente', models.CharField(blank=True, max_length=8, null=True)),
                ('usa_auto_numeracao', models.BooleanField(blank=True, default=False, null=True)),
                ('serie_nf', models.IntegerField(blank=True, default=1, null=True)),
                ('proximo_numero_nf', models.IntegerField(blank=True, default=1, null=True)),
                ('tipo_estoque_baixa', models.CharField(blank=True, max_length=9, null=True)),
                ('gera_financeiro', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'db_table': 'operacoes',
                'managed': False,
            },
        ),
    ]
