# Generated by Django 5.2.7 on 2025-10-22 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_centrocusto_contabancaria_departamento_operacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaConfig',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('nome_razao_social', models.CharField(max_length=255)),
                ('nome_fantasia', models.CharField(blank=True, max_length=255, null=True)),
                ('cpf_cnpj', models.CharField(max_length=18)),
                ('inscricao_estadual', models.CharField(blank=True, max_length=20, null=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('numero', models.CharField(blank=True, max_length=20, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('logo_url', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'empresa_config',
                'managed': False,
            },
        ),
    ]
