# Generated by Django 5.2.7 on 2025-10-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_empresaconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcao',
            fields=[
                ('id_funcao', models.AutoField(primary_key=True, serialize=False)),
                ('nome_funcao', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'funcoes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id_vendedor', models.AutoField(primary_key=True, serialize=False)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('nome_reduzido', models.CharField(blank=True, max_length=100, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
                ('logradouro', models.CharField(blank=True, max_length=255, null=True)),
                ('numero', models.CharField(blank=True, max_length=20, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
                ('percentual_comissao', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'vendedores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VendedorFuncoes',
            fields=[
                ('id_vendedor_funcao', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'vendedor_funcoes',
                'managed': False,
            },
        ),
    ]
