# Generated by Django 5.2.7 on 2025-10-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_funcao_vendedor_vendedorfuncoes'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserParametros',
            fields=[
                ('id_parametro', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'user_parametros',
                'managed': False,
            },
        ),
    ]
