# Generated by Django 5.2.7 on 2025-10-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_userparametros'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPermissoes',
            fields=[
                ('id_permissao', models.AutoField(primary_key=True, serialize=False)),
                ('clientes_acessar', models.IntegerField(blank=True, default=0, null=True)),
                ('clientes_criar', models.IntegerField(blank=True, default=0, null=True)),
                ('clientes_editar', models.IntegerField(blank=True, default=0, null=True)),
                ('clientes_excluir', models.IntegerField(blank=True, default=0, null=True)),
                ('produtos_acessar', models.IntegerField(blank=True, default=0, null=True)),
                ('produtos_criar', models.IntegerField(blank=True, default=0, null=True)),
                ('produtos_editar', models.IntegerField(blank=True, default=0, null=True)),
                ('produtos_excluir', models.IntegerField(blank=True, default=0, null=True)),
                ('financeiro_acessar', models.IntegerField(blank=True, default=0, null=True)),
                ('financeiro_criar', models.IntegerField(blank=True, default=0, null=True)),
                ('financeiro_editar', models.IntegerField(blank=True, default=0, null=True)),
                ('financeiro_excluir', models.IntegerField(blank=True, default=0, null=True)),
                ('financeiro_baixar', models.IntegerField(blank=True, default=0, null=True)),
                ('config_acessar', models.IntegerField(blank=True, default=0, null=True)),
                ('config_empresa', models.IntegerField(blank=True, default=0, null=True)),
                ('config_usuarios', models.IntegerField(blank=True, default=0, null=True)),
                ('config_vendedores', models.IntegerField(blank=True, default=0, null=True)),
                ('config_operacoes', models.IntegerField(blank=True, default=0, null=True)),
                ('config_cadastros_apoio', models.IntegerField(blank=True, default=0, null=True)),
                ('vendas_acessar', models.IntegerField(blank=True, default=0, null=True)),
                ('vendas_criar', models.IntegerField(blank=True, default=0, null=True)),
                ('vendas_editar', models.IntegerField(blank=True, default=0, null=True)),
                ('vendas_excluir', models.IntegerField(blank=True, default=0, null=True)),
                ('vendas_cancelar', models.IntegerField(blank=True, default=0, null=True)),
                ('aut_desconto', models.IntegerField(blank=True, default=0, null=True)),
                ('aut_cancelar_venda', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'db_table': 'user_permissoes',
                'managed': False,
            },
        ),
    ]
