# Generated by Django 5.2.7 on 2025-10-23 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_userpermissoes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id_solicitacao', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_solicitacao', models.CharField(max_length=100)),
                ('id_registro', models.IntegerField(blank=True, null=True)),
                ('dados_solicitacao', models.TextField(blank=True, null=True)),
                ('observacao_solicitante', models.TextField(blank=True, null=True)),
                ('observacao_supervisor', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='Pendente', max_length=9)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'solicitacoes',
                'managed': False,
            },
        ),
    ]
