# Generated by Django 5.2.7 on 2025-10-25 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_solicitacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoAprovacao',
            fields=[
                ('id_solicitacao', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_solicitacao', models.CharField(max_length=100)),
                ('id_registro', models.IntegerField(blank=True, null=True)),
                ('dados_solicitacao', models.TextField(blank=True, null=True)),
                ('observacao_solicitante', models.TextField(blank=True, null=True)),
                ('observacao_supervisor', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='Pendente', max_length=9)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'solicitacoes',
                'ordering': ['-data_solicitacao'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FormaPagamento',
            fields=[
                ('id_forma_pagamento', models.AutoField(primary_key=True, serialize=False)),
                ('nome_forma', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Forma de Pagamento',
                'verbose_name_plural': 'Formas de Pagamento',
                'db_table': 'formas_pagamento',
                'ordering': ['nome_forma'],
            },
        ),
        migrations.DeleteModel(
            name='Solicitacao',
        ),
        migrations.AlterModelOptions(
            name='centrocusto',
            options={'managed': False, 'ordering': ['nome_centro_custo']},
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'managed': False, 'ordering': ['nome_razao_social']},
        ),
        migrations.AlterModelOptions(
            name='contabancaria',
            options={'managed': False, 'ordering': ['nome_conta']},
        ),
        migrations.AlterModelOptions(
            name='departamento',
            options={'managed': False, 'ordering': ['nome_departamento']},
        ),
        migrations.AlterModelOptions(
            name='financeiroconta',
            options={'managed': False, 'ordering': ['data_vencimento', 'descricao']},
        ),
        migrations.AlterModelOptions(
            name='funcao',
            options={'managed': False, 'ordering': ['nome_funcao']},
        ),
        migrations.AlterModelOptions(
            name='grupoproduto',
            options={'managed': False, 'ordering': ['nome_grupo']},
        ),
        migrations.AlterModelOptions(
            name='operacao',
            options={'managed': False, 'ordering': ['nome_operacao']},
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'managed': False, 'ordering': ['nome_produto']},
        ),
        migrations.AlterModelOptions(
            name='vendedor',
            options={'managed': False, 'ordering': ['nome']},
        ),
    ]
