# Generated by Django 5.2.7 on 2025-10-25 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_solicitacaoaprovacao_formapagamento_and_more'),
    ]

    # Esta migração originalmente adicionava campos a um
    # modelo legado FormaPagamento. Em seguida, a
    # migração 0012_formapagamento recria o modelo com os
    # mesmos campos. Para evitar duplicidade de DDL e
    # erros durante a aplicação em bancos de teste/CI,
    # mantemos este passo como um no-op; o modelo é criado
    # por 0012.
    operations = []
