# Generated by Django 5.2.7 on 2025-10-26 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_formapagamento_dias_vencimento_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormaPagamento',
        ),
    ]
