# Generated by Django 5.2.7 on 2025-10-26 22:01

import django.db.models.deletion
from django.db import migrations, models, connection


def create_formas_pagamento(apps, schema_editor):
    is_sqlite = connection.vendor == 'sqlite'
    
    if is_sqlite:
        sql = """
        CREATE TABLE IF NOT EXISTS formas_pagamento (
            id_forma_pagamento INTEGER PRIMARY KEY AUTOINCREMENT,
            nome_forma VARCHAR(100) NOT NULL UNIQUE,
            dias_vencimento INTEGER DEFAULT 0,
            id_conta_padrao INTEGER DEFAULT NULL
        )
        """
    else:
        sql = """
        CREATE TABLE IF NOT EXISTS `formas_pagamento` (
            `id_forma_pagamento` INT AUTO_INCREMENT PRIMARY KEY,
            `nome_forma` VARCHAR(100) NOT NULL UNIQUE,
            `dias_vencimento` INT DEFAULT 0,
            `id_conta_padrao` INT DEFAULT NULL
        ) ENGINE=InnoDB
        """
    
    with connection.cursor() as cursor:
        cursor.execute(sql)


def drop_formas_pagamento(apps, schema_editor):
    is_sqlite = connection.vendor == 'sqlite'
    table_name = 'formas_pagamento' if is_sqlite else '`formas_pagamento`'
    
    with connection.cursor() as cursor:
        cursor.execute(f"DROP TABLE IF EXISTS {table_name}")


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_delete_formapagamento'),
        ('api', '0017_create_unmanaged_tables'),
    ]

    operations = [
        # Use SeparateDatabaseAndState so the database operation is
        # idempotent (CREATE TABLE IF NOT EXISTS) while Django's
        # migration state still registers the CreateModel operation.
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    code=create_formas_pagamento,
                    reverse_code=drop_formas_pagamento,
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='FormaPagamento',
                    fields=[
                        ('id_forma_pagamento', models.AutoField(primary_key=True, serialize=False)),
                        ('nome_forma', models.CharField(max_length=100, unique=True)),
                        ('dias_vencimento', models.IntegerField(blank=True, default=0, null=True)),
                        ('id_conta_padrao', models.ForeignKey(blank=True, db_column='id_conta_padrao', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.contabancaria')),
                    ],
                    options={
                        'verbose_name': 'Forma de Pagamento',
                        'verbose_name_plural': 'Formas de Pagamento',
                        'db_table': 'formas_pagamento',
                        'ordering': ['nome_forma'],
                    },
                ),
            ],
        ),
    ]
