# Generated by Django 5.2.7 on 2025-10-28 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_add_fields_formapagamento'),
        ('api', '0021_add_vendas_columns'),
    ]

    operations = [
    ]
