# Generated by Django 5.2.7 on 2025-10-29 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_operacao_transacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id_fornecedor', models.AutoField(primary_key=True, serialize=False)),
                ('nome_razao_social', models.CharField(max_length=255)),
                ('nome_fantasia', models.CharField(blank=True, max_length=255, null=True)),
                ('cpf_cnpj', models.CharField(max_length=18, unique=True)),
                ('inscricao_estadual', models.CharField(blank=True, max_length=20, null=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('numero', models.CharField(blank=True, max_length=20, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('limite_credito', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('logo_url', models.CharField(blank=True, max_length=500, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'fornecedores',
                'ordering': ['nome_razao_social'],
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='centrocusto',
            options={'managed': True, 'ordering': ['nome_centro_custo']},
        ),
        migrations.AlterModelOptions(
            name='contabancaria',
            options={'managed': True, 'ordering': ['nome_conta']},
        ),
        migrations.AlterModelOptions(
            name='departamento',
            options={'managed': True, 'ordering': ['nome_departamento']},
        ),
        migrations.AlterModelOptions(
            name='financeiroconta',
            options={'managed': True, 'ordering': ['data_vencimento', 'descricao']},
        ),
        migrations.AlterModelOptions(
            name='grupoproduto',
            options={'managed': True, 'ordering': ['nome_grupo']},
        ),
        migrations.AlterModelOptions(
            name='operacao',
            options={'managed': True, 'ordering': ['nome_operacao']},
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'managed': True, 'ordering': ['nome_produto']},
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id_compra', models.AutoField(db_column='id_compra', primary_key=True, serialize=False)),
                ('numero_documento', models.CharField(blank=True, db_column='numero_nota', max_length=50, null=True)),
                ('data_documento', models.DateTimeField(blank=True, db_column='data_movimento_entrada', null=True)),
                ('dados_entrada', models.CharField(blank=True, db_column='chave_nfe', max_length=255, null=True)),
                ('valor_total', models.DecimalField(db_column='valor_total_nota', decimal_places=2, default=0.0, max_digits=12)),
                ('valor_desconto', models.DecimalField(blank=True, db_column='valor_desconto', decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('id_fornecedor', models.ForeignKey(blank=True, db_column='id_fornecedor', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.fornecedor')),
                ('id_operacao', models.ForeignKey(blank=True, db_column='id_operacao', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.operacao')),
            ],
            options={
                'db_table': 'compras',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompraItem',
            fields=[
                ('id_item', models.AutoField(db_column='id_compra_item', primary_key=True, serialize=False)),
                ('quantidade', models.DecimalField(db_column='quantidade', decimal_places=3, default=0.0, max_digits=12)),
                ('unidade', models.CharField(db_column='unidade', default='UN', max_length=10)),
                ('valor_compra', models.DecimalField(db_column='valor_unitario', decimal_places=2, default=0.0, max_digits=12)),
                ('valor_total', models.DecimalField(db_column='valor_total', decimal_places=2, default=0.0, max_digits=12)),
                ('desconto', models.DecimalField(blank=True, db_column='valor_desconto', decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('id_compra', models.ForeignKey(db_column='id_compra', on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='api.compra')),
                ('id_produto', models.ForeignKey(blank=True, db_column='id_produto', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.produto')),
            ],
            options={
                'db_table': 'compra_itens',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id_venda', models.AutoField(primary_key=True, serialize=False)),
                ('numero_documento', models.CharField(blank=True, max_length=50, null=True)),
                ('data_documento', models.DateTimeField(auto_now_add=True)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('gerou_financeiro', models.IntegerField(blank=True, default=0, null=True)),
                ('vista', models.IntegerField(blank=True, default=0, null=True)),
                ('criado_por', models.ForeignKey(blank=True, db_column='criado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('id_cliente', models.ForeignKey(blank=True, db_column='id_cliente', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.cliente')),
                ('id_operacao', models.ForeignKey(blank=True, db_column='id_operacao', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.operacao')),
                ('id_vendedor1', models.ForeignKey(blank=True, db_column='id_vendedor1', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas_vendedor1', to='api.vendedor')),
                ('id_vendedor2', models.ForeignKey(blank=True, db_column='id_vendedor2', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas_vendedor2', to='api.vendedor')),
            ],
            options={
                'db_table': 'vendas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VendaItem',
            fields=[
                ('id_item', models.AutoField(db_column='id_venda_item', primary_key=True, serialize=False)),
                ('quantidade', models.DecimalField(db_column='quantidade', decimal_places=3, default=0.0, max_digits=12)),
                ('valor_unitario', models.DecimalField(db_column='valor_unitario', decimal_places=2, default=0.0, max_digits=12)),
                ('desconto_valor', models.DecimalField(blank=True, db_column='valor_desconto', decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('valor_total', models.DecimalField(db_column='valor_total', decimal_places=2, default=0.0, max_digits=12)),
                ('id_produto', models.ForeignKey(blank=True, db_column='id_produto', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.produto')),
                ('id_venda', models.ForeignKey(db_column='id_venda', on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='api.venda')),
            ],
            options={
                'db_table': 'venda_itens',
                'managed': False,
            },
        ),
    ]
