# Generated by Django 5.2.7 on 2025-11-02 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_add_venda_id_financeiro'),
    ]

    operations = [
    ]
