# Generated by Django 5.2.7 on 2025-11-03 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_remover_campos_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('id_deposito', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('nome_deposito', models.CharField(db_column='nome', help_text='Nome do depósito', max_length=100)),
                ('descricao', models.TextField(blank=True, help_text='Descrição do depósito', null=True)),
                ('estoque_baixo', models.IntegerField(default=0, help_text='Estoque mínimo para alerta')),
                ('estoque_incremento', models.IntegerField(default=0, help_text='Incremento de estoque')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, db_column='criado_em')),
                ('data_modificacao', models.DateTimeField(auto_now=True, db_column='atualizado_em')),
            ],
            options={
                'verbose_name': 'Depósito',
                'verbose_name_plural': 'Depósitos',
                'db_table': 'deposito',
                'ordering': ['nome_deposito'],
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='contabancaria',
            options={'managed': True, 'ordering': ['nome_conta'], 'verbose_name': 'Conta BancÃ¡ria', 'verbose_name_plural': 'Contas BancÃ¡rias'},
        ),
        migrations.RenameField(
            model_name='financeiroconta',
            old_name='valor_pago',
            new_name='valor_desconto',
        ),
        migrations.RenameField(
            model_name='financeiroconta',
            old_name='valor_total',
            new_name='valor_parcela',
        ),
        migrations.RemoveField(
            model_name='financeiroconta',
            name='centro_custo',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='estoque_atual',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='valor_compra',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='valor_custo',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='valor_venda',
        ),
        migrations.AddField(
            model_name='contabancaria',
            name='agencia',
            field=models.CharField(blank=True, help_text='NÃºmero da agÃªncia', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contabancaria',
            name='codigo_banco',
            field=models.CharField(blank=True, help_text='CÃ³digo do banco (ex: 001, 033, 104)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='contabancaria',
            name='conta',
            field=models.CharField(blank=True, help_text='NÃºmero da conta', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contabancaria',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='contabancaria',
            name='data_modificacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='contabancaria',
            name='digito',
            field=models.CharField(blank=True, help_text='DÃ\xadgito verificador', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='contabancaria',
            name='nome_banco',
            field=models.CharField(blank=True, help_text='Nome do banco', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contabancaria',
            name='obs',
            field=models.TextField(blank=True, help_text='ObservaÃ§Ãµes gerais', null=True),
        ),
        migrations.AddField(
            model_name='contabancaria',
            name='saldo_inicial',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Saldo inicial da conta', max_digits=15),
        ),
        migrations.AddField(
            model_name='contabancaria',
            name='tipo_conta',
            field=models.CharField(choices=[('C', 'Conta Corrente'), ('P', 'PoupanÃ§a')], default='C', help_text='Tipo da conta bancÃ¡ria', max_length=1),
        ),
        migrations.AddField(
            model_name='financeiroconta',
            name='documento_numero',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='financeiroconta',
            name='gerencial',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='financeiroconta',
            name='id_centro_custo',
            field=models.ForeignKey(blank=True, db_column='id_centro_custo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.centrocusto'),
        ),
        migrations.AddField(
            model_name='financeiroconta',
            name='id_cliente_fornecedor',
            field=models.ForeignKey(blank=True, db_column='id_cliente_fornecedor', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.cliente'),
        ),
        migrations.AddField(
            model_name='financeiroconta',
            name='id_conta_baixa',
            field=models.ForeignKey(blank=True, db_column='id_conta_baixa', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_baixa', to='api.contabancaria'),
        ),
        migrations.AddField(
            model_name='financeiroconta',
            name='id_conta_cobranca',
            field=models.ForeignKey(blank=True, db_column='id_conta_cobranca', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_cobranca', to='api.contabancaria'),
        ),
        migrations.AddField(
            model_name='financeiroconta',
            name='id_departamento',
            field=models.ForeignKey(blank=True, db_column='id_departamento', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.departamento'),
        ),
        migrations.AddField(
            model_name='financeiroconta',
            name='id_operacao',
            field=models.ForeignKey(blank=True, db_column='id_operacao', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.operacao'),
        ),
        migrations.AddField(
            model_name='financeiroconta',
            name='parcela_numero',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='financeiroconta',
            name='parcela_total',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='financeiroconta',
            name='valor_juros',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='financeiroconta',
            name='valor_liquidado',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='financeiroconta',
            name='valor_multa',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='operacao',
            name='id_deposito_incremento',
            field=models.IntegerField(blank=True, db_column='id_deposito_incremento', null=True),
        ),
        migrations.AddField(
            model_name='operacao',
            name='incrementar_estoque',
            field=models.IntegerField(blank=True, db_column='incrementar_estoque', default=0, null=True),
        ),
        migrations.AddField(
            model_name='operacao',
            name='tipo_estoque_incremento',
            field=models.CharField(blank=True, default='Nenhum', max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='id_grupo',
            field=models.ForeignKey(blank=True, db_column='id_grupo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.grupoproduto'),
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='contabancaria',
            name='nome_conta',
            field=models.CharField(help_text='Nome identificador da conta', max_length=100),
        ),
        migrations.AlterField(
            model_name='operacao',
            name='gera_financeiro',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='operacao',
            name='tipo_estoque_baixa',
            field=models.CharField(blank=True, default='Nenhum', max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='operacao',
            name='usa_auto_numeracao',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id_estoque', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.DecimalField(decimal_places=3, default=0.0, help_text='Quantidade atual em estoque', max_digits=15)),
                ('quantidade_minima', models.DecimalField(decimal_places=3, default=0.0, help_text='Quantidade mÃ\xadnima de estoque', max_digits=15)),
                ('quantidade_maxima', models.DecimalField(blank=True, decimal_places=3, help_text='Quantidade mÃ¡xima de estoque', max_digits=15, null=True)),
                ('custo_medio', models.DecimalField(decimal_places=4, default=0.0, help_text='Custo mÃ©dio do produto', max_digits=15)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0.0, help_text='Valor total do estoque (quantidade Ã— custo mÃ©dio)', max_digits=15)),
                ('valor_venda', models.DecimalField(decimal_places=2, default=0.0, help_text='Valor de venda do produto neste depósito', max_digits=15)),
                ('valor_ultima_compra', models.DecimalField(decimal_places=2, default=0.0, help_text='Valor da última compra do produto neste depósito', max_digits=15)),
                ('data_ultima_entrada', models.DateTimeField(blank=True, help_text='Data da Ãºltima entrada no estoque', null=True)),
                ('data_ultima_saida', models.DateTimeField(blank=True, help_text='Data da Ãºltima saÃ\xadda do estoque', null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('data_modificacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True, help_text='Registro ativo')),
                ('id_deposito', models.ForeignKey(db_column='id_deposito', help_text='DepÃ³sito onde o produto estÃ¡ armazenado', on_delete=django.db.models.deletion.CASCADE, to='api.deposito')),
                ('id_produto', models.ForeignKey(db_column='id_produto', help_text='Produto relacionado ao estoque', on_delete=django.db.models.deletion.CASCADE, to='api.produto')),
            ],
            options={
                'verbose_name': 'Estoque',
                'verbose_name_plural': 'Estoques',
                'db_table': 'estoque',
                'ordering': ['id_produto', 'id_deposito'],
                'managed': True,
                'unique_together': {('id_produto', 'id_deposito')},
            },
        ),
        migrations.CreateModel(
            name='EstoqueMovimentacao',
            fields=[
                ('id_movimentacao', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_movimentacao', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'SaÃ\xadda'), ('AJUSTE', 'Ajuste'), ('TRANSFERENCIA', 'TransferÃªncia')], help_text='Tipo da movimentaÃ§Ã£o', max_length=15)),
                ('quantidade_anterior', models.DecimalField(decimal_places=3, help_text='Quantidade antes da movimentaÃ§Ã£o', max_digits=15)),
                ('quantidade_movimentada', models.DecimalField(decimal_places=3, help_text='Quantidade movimentada', max_digits=15)),
                ('quantidade_atual', models.DecimalField(decimal_places=3, help_text='Quantidade apÃ³s a movimentaÃ§Ã£o', max_digits=15)),
                ('custo_unitario', models.DecimalField(decimal_places=4, default=0.0, help_text='Custo unitÃ¡rio da movimentaÃ§Ã£o', max_digits=15)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0.0, help_text='Valor total da movimentaÃ§Ã£o', max_digits=15)),
                ('documento_numero', models.CharField(blank=True, help_text='NÃºmero do documento de origem', max_length=50, null=True)),
                ('documento_tipo', models.CharField(blank=True, choices=[('VENDA', 'Venda'), ('COMPRA', 'Compra'), ('AJUSTE', 'Ajuste'), ('TRANSFERENCIA', 'TransferÃªncia'), ('INVENTARIO', 'InventÃ¡rio')], help_text='Tipo do documento de origem', max_length=15, null=True)),
                ('id_documento_origem', models.IntegerField(blank=True, help_text='ID do documento de origem', null=True)),
                ('observacoes', models.TextField(blank=True, help_text='ObservaÃ§Ãµes sobre a movimentaÃ§Ã£o', null=True)),
                ('usuario_responsavel', models.CharField(blank=True, help_text='UsuÃ¡rio responsÃ¡vel pela movimentaÃ§Ã£o', max_length=100, null=True)),
                ('data_movimentacao', models.DateTimeField(auto_now_add=True, help_text='Data e hora da movimentaÃ§Ã£o')),
                ('id_deposito', models.ForeignKey(db_column='id_deposito', help_text='DepÃ³sito da movimentaÃ§Ã£o', on_delete=django.db.models.deletion.CASCADE, to='api.deposito')),
                ('id_estoque', models.ForeignKey(db_column='id_estoque', help_text='Estoque relacionado Ã\xa0 movimentaÃ§Ã£o', on_delete=django.db.models.deletion.CASCADE, to='api.estoque')),
                ('id_produto', models.ForeignKey(db_column='id_produto', help_text='Produto movimentado', on_delete=django.db.models.deletion.CASCADE, to='api.produto')),
            ],
            options={
                'verbose_name': 'MovimentaÃ§Ã£o de Estoque',
                'verbose_name_plural': 'MovimentaÃ§Ãµes de Estoque',
                'db_table': 'estoque_movimentacoes',
                'ordering': ['-data_movimentacao'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FinanceiroBancario',
            fields=[
                ('id_movimento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_movimento', models.CharField(choices=[('C', 'Crédito'), ('D', 'Débito')], help_text='Tipo do movimento bancário', max_length=1)),
                ('data_pagamento', models.DateField(help_text='Data do movimento')),
                ('valor_movimento', models.DecimalField(decimal_places=2, help_text='Valor do movimento', max_digits=15)),
                ('descricao', models.CharField(help_text='Descrição do movimento', max_length=255)),
                ('documento_numero', models.CharField(blank=True, help_text='Número do documento', max_length=50, null=True)),
                ('forma_pagamento', models.CharField(blank=True, help_text='Forma de pagamento', max_length=50, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('id_cliente_fornecedor', models.ForeignKey(blank=True, db_column='id_cliente_fornecedor', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.cliente')),
                ('id_conta_bancaria', models.ForeignKey(db_column='id_conta_bancaria', on_delete=django.db.models.deletion.PROTECT, to='api.contabancaria')),
            ],
            options={
                'verbose_name': 'Movimento Bancário',
                'verbose_name_plural': 'Movimentos Bancários',
                'db_table': 'financeiro_bancario',
                'ordering': ['-data_pagamento', '-id_movimento'],
                'managed': True,
            },
        ),
    ]
