# Generated by Django 5.2.7 on 2025-11-04 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_criar_financeiro_bancario'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('destaque', models.BooleanField(default=False, verbose_name='Produto em Destaque')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('produto', models.ForeignKey(db_column='id_produto', help_text='Produto do catálogo', on_delete=django.db.models.deletion.CASCADE, related_name='catalogo_items', to='api.produto')),
            ],
            options={
                'verbose_name': 'Item do Catálogo',
                'verbose_name_plural': 'Itens do Catálogo',
                'db_table': 'catalogo_item',
                'ordering': ['ordem', 'produto__nome_produto'],
                'managed': True,
            },
        ),
    ]
