# Generated by Django 5.2.7 on 2025-11-04 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_catalogoitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogoitem',
            options={'ordering': ['ordem', 'produto__nome_produto'], 'verbose_name': 'Item do Catálogo', 'verbose_name_plural': 'Itens do Catálogo'},
        ),
        migrations.AlterField(
            model_name='catalogoitem',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='catalogoitem',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='catalogoitem',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='catalogoitem',
            name='destaque',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='catalogoitem',
            name='ordem',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='catalogoitem',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalogo_items', to='api.produto'),
        ),
        migrations.AlterModelTable(
            name='catalogoitem',
            table='api_catalogoitem',
        ),
    ]
