# Generated by Django 5.2.7 on 2025-11-04 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_catalogoitem_options_alter_catalogoitem_ativo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_catalogo', models.CharField(help_text='Nome identificador do catálogo (ex: Catálogo Verão 2025)', max_length=200, verbose_name='Nome do Catálogo')),
                ('descricao', models.TextField(blank=True, help_text='Descrição opcional do catálogo', null=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, help_text='Catálogo ativo para compartilhamento', verbose_name='Ativo')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Catálogo',
                'verbose_name_plural': 'Catálogos',
                'db_table': 'api_catalogo',
                'ordering': ['-data_cadastro'],
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='catalogoitem',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalogo_items', to='api.produto', verbose_name='Produto'),
        ),
        migrations.AddField(
            model_name='catalogoitem',
            name='catalogo',
            field=models.ForeignKey(blank=True, help_text='Catálogo ao qual este item pertence', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='api.catalogo', verbose_name='Catálogo'),
        ),
    ]
