# Generated by Django 5.2.7 on 2025-11-05 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_add_valor_catalogo_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditoCliente',
            fields=[
                ('id_credito', models.AutoField(primary_key=True, serialize=False)),
                ('id_cliente', models.IntegerField(db_index=True)),
                ('valor_credito', models.DecimalField(decimal_places=2, help_text='Valor total do crédito', max_digits=10)),
                ('valor_utilizado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('saldo', models.DecimalField(decimal_places=2, help_text='Saldo disponível', max_digits=10)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_validade', models.DateField(blank=True, help_text='Data de expiração do crédito', null=True)),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('utilizado', 'Totalmente Utilizado'), ('parcialmente_utilizado', 'Parcialmente Utilizado'), ('expirado', 'Expirado'), ('cancelado', 'Cancelado')], default='disponivel', max_length=30)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Crédito de Cliente',
                'verbose_name_plural': 'Créditos de Clientes',
                'db_table': 'creditos_cliente',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='CreditoUtilizacao',
            fields=[
                ('id_utilizacao', models.AutoField(primary_key=True, serialize=False)),
                ('id_venda', models.IntegerField(db_index=True)),
                ('valor_utilizado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_utilizacao', models.DateTimeField(auto_now_add=True)),
                ('credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilizacoes', to='api.creditocliente')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Utilização de Crédito',
                'verbose_name_plural': 'Utilizações de Créditos',
                'db_table': 'credito_utilizacoes',
                'ordering': ['-data_utilizacao'],
            },
        ),
        migrations.CreateModel(
            name='Devolucao',
            fields=[
                ('id_devolucao', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('venda', 'Devolução de Venda'), ('compra', 'Devolução de Compra')], max_length=10)),
                ('id_venda', models.IntegerField(blank=True, help_text='ID da venda sendo devolvida', null=True)),
                ('id_compra', models.IntegerField(blank=True, help_text='ID da compra sendo devolvida', null=True)),
                ('id_cliente', models.IntegerField(blank=True, null=True)),
                ('id_fornecedor', models.IntegerField(blank=True, null=True)),
                ('id_operacao', models.IntegerField(blank=True, help_text='Operação de devolução', null=True)),
                ('data_devolucao', models.DateTimeField(auto_now_add=True)),
                ('numero_devolucao', models.CharField(help_text='Número único da devolução', max_length=50, unique=True)),
                ('motivo', models.TextField(help_text='Motivo da devolução')),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('gerar_credito', models.BooleanField(default=False, help_text='Gerar crédito para o cliente?')),
                ('valor_total_devolucao', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('cancelada', 'Cancelada')], default='pendente', max_length=20)),
                ('estoque_atualizado', models.BooleanField(default=False)),
                ('financeiro_gerado', models.BooleanField(default=False)),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devolucoes_aprovadas', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devolucoes_criadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Devolução',
                'verbose_name_plural': 'Devoluções',
                'db_table': 'devolucoes',
                'ordering': ['-data_devolucao'],
            },
        ),
        migrations.AddField(
            model_name='creditocliente',
            name='devolucao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditos', to='api.devolucao'),
        ),
        migrations.CreateModel(
            name='DevolucaoItem',
            fields=[
                ('id_devolucao_item', models.AutoField(primary_key=True, serialize=False)),
                ('id_produto', models.IntegerField()),
                ('nome_produto', models.CharField(help_text='Nome do produto no momento da devolução', max_length=255)),
                ('codigo_produto', models.CharField(blank=True, max_length=100, null=True)),
                ('quantidade_devolvida', models.DecimalField(decimal_places=3, max_digits=10)),
                ('quantidade_original', models.DecimalField(decimal_places=3, help_text='Quantidade na venda/compra original', max_digits=10)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motivo_item', models.TextField(blank=True, help_text='Motivo específico deste item', null=True)),
                ('id_venda_item', models.IntegerField(blank=True, help_text='ID do item da venda original', null=True)),
                ('id_compra_item', models.IntegerField(blank=True, help_text='ID do item da compra original', null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('devolucao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='api.devolucao')),
            ],
            options={
                'verbose_name': 'Item de Devolução',
                'verbose_name_plural': 'Itens de Devolução',
                'db_table': 'devolucao_itens',
            },
        ),
        migrations.AddIndex(
            model_name='creditocliente',
            index=models.Index(fields=['id_cliente', 'status'], name='creditos_cl_id_clie_1bdb1e_idx'),
        ),
    ]
