# Generated by Django 5.2.7 on 2025-11-05 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_creditocliente_creditoutilizacao_devolucao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditocliente',
            name='devolucao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creditos', to='api.devolucao'),
        ),
    ]
