# Generated by Django 5.2.7 on 2025-11-06 17:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_alter_creditocliente_devolucao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Troca',
            fields=[
                ('id_troca', models.AutoField(primary_key=True, serialize=False)),
                ('id_venda_original', models.BigIntegerField(help_text='ID da venda original que está sendo trocada')),
                ('id_cliente', models.BigIntegerField(blank=True, help_text='ID do cliente (opcional)', null=True)),
                ('data_troca', models.DateTimeField(default=django.utils.timezone.now, help_text='Data e hora da troca')),
                ('valor_total_retorno', models.DecimalField(decimal_places=2, default=0, help_text='Valor total dos produtos devolvidos', max_digits=12)),
                ('valor_total_substituicao', models.DecimalField(decimal_places=2, default=0, help_text='Valor total dos produtos substitutos', max_digits=12)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='pendente', help_text='Status da troca', max_length=20)),
                ('observacao', models.TextField(blank=True, help_text='Observações sobre a troca', null=True)),
                ('criado_por', models.BigIntegerField(blank=True, help_text='ID do usuário que criou a troca', null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('id_financeiro', models.BigIntegerField(blank=True, help_text='ID do registro financeiro gerado (se houver)', null=True)),
            ],
            options={
                'verbose_name': 'Troca',
                'verbose_name_plural': 'Trocas',
                'db_table': 'trocas',
                'ordering': ['-data_troca'],
            },
        ),
        migrations.AddField(
            model_name='catalogoitem',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='catalogoitem',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='TrocaItem',
            fields=[
                ('id_troca_item', models.AutoField(primary_key=True, serialize=False)),
                ('id_venda_item_original', models.BigIntegerField(blank=True, help_text='ID do item da venda original sendo devolvido', null=True)),
                ('id_produto_retorno', models.BigIntegerField(blank=True, help_text='ID do produto sendo devolvido', null=True)),
                ('quantidade_retorno', models.DecimalField(decimal_places=3, default=0, help_text='Quantidade do produto devolvido', max_digits=12)),
                ('valor_unit_retorno', models.DecimalField(decimal_places=2, default=0, help_text='Valor unitário do produto devolvido', max_digits=12)),
                ('valor_total_retorno', models.DecimalField(decimal_places=2, default=0, help_text='Valor total do produto devolvido', max_digits=12)),
                ('id_produto_substituicao', models.BigIntegerField(blank=True, help_text='ID do produto substituto', null=True)),
                ('quantidade_substituicao', models.DecimalField(decimal_places=3, default=0, help_text='Quantidade do produto substituto', max_digits=12)),
                ('valor_unit_substituicao', models.DecimalField(decimal_places=2, default=0, help_text='Valor unitário do produto substituto', max_digits=12)),
                ('valor_total_substituicao', models.DecimalField(decimal_places=2, default=0, help_text='Valor total do produto substituto', max_digits=12)),
                ('troca', models.ForeignKey(db_column='id_troca', on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='api.troca')),
            ],
            options={
                'verbose_name': 'Item de Troca',
                'verbose_name_plural': 'Itens de Troca',
                'db_table': 'troca_itens',
            },
        ),
    ]
