# Generated by Django 5.2.7 on 2025-11-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_troca_catalogoitem_data_nascimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacao',
            name='transacao',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
