# Generated by Django 5.2.7 on 2025-11-11 18:34

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_alter_operacao_transacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotacao',
            fields=[
                ('id_cotacao', models.AutoField(db_column='id_cotacao', primary_key=True, serialize=False)),
                ('numero_cotacao', models.CharField(db_column='numero_cotacao', max_length=50, unique=True)),
                ('data_cotacao', models.DateTimeField(db_column='data_cotacao', default=django.utils.timezone.now)),
                ('prazo_resposta', models.DateTimeField(db_column='prazo_resposta')),
                ('status', models.CharField(choices=[('Rascunho', 'Rascunho'), ('Enviada', 'Enviada'), ('Em Análise', 'Em Análise'), ('Finalizada', 'Finalizada'), ('Cancelada', 'Cancelada')], db_column='status', default='Rascunho', max_length=20)),
                ('observacoes', models.TextField(blank=True, db_column='observacoes', null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='criado_em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_column='atualizado_em')),
                ('criado_por', models.ForeignKey(blank=True, db_column='criado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cotacoes',
                'ordering': ['-data_cotacao'],
            },
        ),
        migrations.CreateModel(
            name='CotacaoFornecedor',
            fields=[
                ('id_cotacao_fornecedor', models.AutoField(db_column='id_cotacao_fornecedor', primary_key=True, serialize=False)),
                ('token_acesso', models.UUIDField(db_column='token_acesso', default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Visualizada', 'Visualizada'), ('Respondida', 'Respondida'), ('Vencedor', 'Vencedor'), ('Não Vencedor', 'Não Vencedor')], db_column='status', default='Pendente', max_length=20)),
                ('data_envio', models.DateTimeField(blank=True, db_column='data_envio', null=True)),
                ('data_visualizacao', models.DateTimeField(blank=True, db_column='data_visualizacao', null=True)),
                ('data_resposta', models.DateTimeField(blank=True, db_column='data_resposta', null=True)),
                ('email_enviado', models.BooleanField(db_column='email_enviado', default=False)),
                ('whatsapp_enviado', models.BooleanField(db_column='whatsapp_enviado', default=False)),
                ('id_cotacao', models.ForeignKey(db_column='id_cotacao', on_delete=django.db.models.deletion.CASCADE, related_name='fornecedores', to='api.cotacao')),
                ('id_fornecedor', models.ForeignKey(db_column='id_fornecedor', on_delete=django.db.models.deletion.CASCADE, to='api.fornecedor')),
            ],
            options={
                'db_table': 'cotacao_fornecedores',
                'unique_together': {('id_cotacao', 'id_fornecedor')},
            },
        ),
        migrations.CreateModel(
            name='CotacaoItem',
            fields=[
                ('id_cotacao_item', models.AutoField(db_column='id_cotacao_item', primary_key=True, serialize=False)),
                ('quantidade_solicitada', models.DecimalField(db_column='quantidade_solicitada', decimal_places=3, max_digits=10)),
                ('observacoes', models.TextField(blank=True, db_column='observacoes', null=True)),
                ('valor_vencedor', models.DecimalField(blank=True, db_column='valor_vencedor', decimal_places=2, max_digits=10, null=True)),
                ('fornecedor_vencedor', models.ForeignKey(blank=True, db_column='fornecedor_vencedor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_cotacao_vencidos', to='api.fornecedor')),
                ('id_cotacao', models.ForeignKey(db_column='id_cotacao', on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='api.cotacao')),
                ('id_produto', models.ForeignKey(db_column='id_produto', on_delete=django.db.models.deletion.CASCADE, to='api.produto')),
            ],
            options={
                'db_table': 'cotacao_itens',
            },
        ),
        migrations.CreateModel(
            name='CotacaoResposta',
            fields=[
                ('id_cotacao_resposta', models.AutoField(db_column='id_cotacao_resposta', primary_key=True, serialize=False)),
                ('valor_unitario', models.DecimalField(db_column='valor_unitario', decimal_places=2, max_digits=10)),
                ('prazo_entrega_dias', models.IntegerField(blank=True, db_column='prazo_entrega_dias', null=True)),
                ('observacoes', models.TextField(blank=True, db_column='observacoes', null=True)),
                ('valor_total', models.DecimalField(db_column='valor_total', decimal_places=2, max_digits=12)),
                ('id_cotacao_fornecedor', models.ForeignKey(db_column='id_cotacao_fornecedor', on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='api.cotacaofornecedor')),
                ('id_cotacao_item', models.ForeignKey(db_column='id_cotacao_item', on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='api.cotacaoitem')),
            ],
            options={
                'db_table': 'cotacao_respostas',
                'unique_together': {('id_cotacao_fornecedor', 'id_cotacao_item')},
            },
        ),
    ]
