# Generated by Django 5.2.7 on 2025-11-13 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_cotacao_cotacaofornecedor_cotacaoitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='taxa_entrega',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
    ]
