# Generated by Django 5.2.7 on 2025-11-13 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_add_taxa_entrega_venda'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contabancaria',
            options={'managed': True, 'ordering': ['nome_conta'], 'verbose_name': 'Conta Bancária', 'verbose_name_plural': 'Contas Bancárias'},
        ),
        migrations.AlterModelOptions(
            name='estoquemovimentacao',
            options={'managed': True, 'ordering': ['-data_movimentacao'], 'verbose_name': 'Movimentaé§é£o de Estoque', 'verbose_name_plural': 'Movimentaé§éµes de Estoque'},
        ),
        migrations.AlterField(
            model_name='catalogo',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Atualização'),
        ),
        migrations.AlterField(
            model_name='catalogo',
            name='descricao',
            field=models.TextField(blank=True, help_text='Descrição opcional do catálogo', null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='catalogo',
            name='nome_catalogo',
            field=models.CharField(help_text='Nome identificador do catálogo (ex: Catálogo Veréo 2025)', max_length=200, verbose_name='Nome do Catálogo'),
        ),
        migrations.AlterField(
            model_name='contabancaria',
            name='agencia',
            field=models.CharField(blank=True, help_text='Número da agência', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contabancaria',
            name='codigo_banco',
            field=models.CharField(blank=True, help_text='Código do banco (ex: 001, 033, 104)', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='contabancaria',
            name='conta',
            field=models.CharField(blank=True, help_text='Número da conta', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contabancaria',
            name='digito',
            field=models.CharField(blank=True, help_text='Dígito verificador', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='contabancaria',
            name='obs',
            field=models.TextField(blank=True, help_text='Observações gerais', null=True),
        ),
        migrations.AlterField(
            model_name='contabancaria',
            name='tipo_conta',
            field=models.CharField(choices=[('C', 'Conta Corrente'), ('P', 'Poupança')], default='C', help_text='Tipo da conta bancária', max_length=1),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='custo_medio',
            field=models.DecimalField(decimal_places=4, default=0.0, help_text='Custo médio do produto', max_digits=15),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='data_ultima_entrada',
            field=models.DateTimeField(blank=True, help_text='Data da éºltima entrada no estoque', null=True),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='data_ultima_saida',
            field=models.DateTimeField(blank=True, help_text='Data da éºltima saé\xadda do estoque', null=True),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='id_deposito',
            field=models.ForeignKey(db_column='id_deposito', help_text='Depósito onde o produto está armazenado', on_delete=django.db.models.deletion.CASCADE, to='api.deposito'),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='quantidade_maxima',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Quantidade mé¡xima de estoque', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='quantidade_minima',
            field=models.DecimalField(decimal_places=3, default=0.0, help_text='Quantidade mé\xadnima de estoque', max_digits=15),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Valor total do estoque (quantidade × custo médio)', max_digits=15),
        ),
        migrations.AlterField(
            model_name='estoquemovimentacao',
            name='custo_unitario',
            field=models.DecimalField(decimal_places=4, default=0.0, help_text='Custo unité¡rio da movimentaé§é£o', max_digits=15),
        ),
        migrations.AlterField(
            model_name='estoquemovimentacao',
            name='data_movimentacao',
            field=models.DateTimeField(auto_now_add=True, help_text='Data e hora da movimentaé§é£o'),
        ),
        migrations.AlterField(
            model_name='estoquemovimentacao',
            name='documento_numero',
            field=models.CharField(blank=True, help_text='Néºmero do documento de origem', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='estoquemovimentacao',
            name='documento_tipo',
            field=models.CharField(blank=True, choices=[('VENDA', 'Venda'), ('COMPRA', 'Compra'), ('AJUSTE', 'Ajuste'), ('TRANSFERENCIA', 'Transferéªncia'), ('INVENTARIO', 'Inventário')], help_text='Tipo do documento de origem', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='estoquemovimentacao',
            name='id_deposito',
            field=models.ForeignKey(db_column='id_deposito', help_text='Depé³sito da movimentaé§é£o', on_delete=django.db.models.deletion.CASCADE, to='api.deposito'),
        ),
        migrations.AlterField(
            model_name='estoquemovimentacao',
            name='id_estoque',
            field=models.ForeignKey(db_column='id_estoque', help_text='Estoque relacionado é\xa0 movimentaé§é£o', on_delete=django.db.models.deletion.CASCADE, to='api.estoque'),
        ),
        migrations.AlterField(
            model_name='estoquemovimentacao',
            name='observacoes',
            field=models.TextField(blank=True, help_text='Observaé§éµes sobre a movimentaé§é£o', null=True),
        ),
        migrations.AlterField(
            model_name='estoquemovimentacao',
            name='quantidade_anterior',
            field=models.DecimalField(decimal_places=3, help_text='Quantidade antes da movimentaé§é£o', max_digits=15),
        ),
        migrations.AlterField(
            model_name='estoquemovimentacao',
            name='quantidade_atual',
            field=models.DecimalField(decimal_places=3, help_text='Quantidade apé³s a movimentaé§é£o', max_digits=15),
        ),
        migrations.AlterField(
            model_name='estoquemovimentacao',
            name='tipo_movimentacao',
            field=models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saé\xadda'), ('AJUSTE', 'Ajuste'), ('TRANSFERENCIA', 'Transferéªncia')], help_text='Tipo da movimentaé§é£o', max_length=15),
        ),
        migrations.AlterField(
            model_name='estoquemovimentacao',
            name='usuario_responsavel',
            field=models.CharField(blank=True, help_text='Usué¡rio responsé¡vel pela movimentaé§é£o', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='estoquemovimentacao',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Valor total da movimentaé§é£o', max_digits=15),
        ),
        migrations.AlterField(
            model_name='financeirobancario',
            name='descricao',
            field=models.CharField(help_text='Descrição do movimento', max_length=255),
        ),
    ]
