# Generated by Django 5.2.7 on 2025-11-13 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_alter_contabancaria_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estoquemovimentacao',
            options={'managed': True, 'ordering': ['-data_movimentacao'], 'verbose_name': 'Movimentação de Estoque', 'verbose_name_plural': 'Movimentações de Estoque'},
        ),
    ]
