# Generated by Django 5.2.7 on 2025-11-13 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_alter_estoquemovimentacao_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupoproduto',
            name='descricao',
            field=models.TextField(blank=True, db_column='descricao', help_text='Descrição do grupo de produtos', null=True),
        ),
    ]
