# Generated by Django 5.2.7 on 2025-11-13 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_grupoproduto_descricao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocao',
            fields=[
                ('id_promocao', models.AutoField(primary_key=True, serialize=False)),
                ('nome_promocao', models.CharField(help_text="Nome da promoção (ex: 'Liquidação Verão 2025')", max_length=255)),
                ('descricao', models.TextField(blank=True, help_text='Descrição detalhada da promoção', null=True)),
                ('data_inicio', models.DateTimeField(help_text='Data e hora de início da promoção')),
                ('data_fim', models.DateTimeField(help_text='Data e hora de término da promoção')),
                ('tipo_desconto', models.CharField(choices=[('percentual', 'Percentual (%)'), ('unidade', 'Valor por Unidade (R$)'), ('valor', 'Valor Total (R$)')], default='percentual', help_text='Tipo de desconto a aplicar', max_length=20)),
                ('valor_desconto', models.DecimalField(decimal_places=2, help_text='Valor ou percentual de desconto', max_digits=12)),
                ('tipo_criterio', models.CharField(choices=[('quantidade', 'Por Quantidade Vendida'), ('valor', 'Por Valor de Venda')], default='quantidade', help_text='Critério para selecionar produtos em promoção', max_length=20)),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('inativa', 'Inativa'), ('expirada', 'Expirada')], default='ativa', help_text='Status atual da promoção', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, db_column='criado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promocoes_criadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Promoção',
                'verbose_name_plural': 'Promoções',
                'db_table': 'promocoes',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='PromocaoProduto',
            fields=[
                ('id_promocao_produto', models.AutoField(primary_key=True, serialize=False)),
                ('valor_minimo_venda', models.DecimalField(blank=True, decimal_places=2, help_text='Valor mínimo para aplicar desconto (opcional)', max_digits=12, null=True)),
                ('quantidade_minima', models.DecimalField(blank=True, decimal_places=3, help_text='Quantidade mínima para aplicar desconto (opcional)', max_digits=12, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('id_produto', models.ForeignKey(db_column='id_produto', on_delete=django.db.models.deletion.CASCADE, to='api.produto')),
                ('id_promocao', models.ForeignKey(db_column='id_promocao', on_delete=django.db.models.deletion.CASCADE, related_name='promocao_produtos', to='api.promocao')),
            ],
            options={
                'verbose_name': 'Produto em Promoção',
                'verbose_name_plural': 'Produtos em Promoção',
                'db_table': 'promocao_produtos',
                'unique_together': {('id_promocao', 'id_produto')},
            },
        ),
        migrations.AddField(
            model_name='promocao',
            name='produtos',
            field=models.ManyToManyField(help_text='Produtos em promoção', through='api.PromocaoProduto', to='api.produto'),
        ),
    ]
