# Generated by Django 5.2.7 on 2025-11-14 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_add_promocao_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocaoproduto',
            name='valor_desconto_produto',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Desconto individual para este produto (sobrescreve o desconto geral)', max_digits=12, null=True),
        ),
    ]
