# Generated by Django 5.2.7 on 2025-11-17 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_promocaoproduto_valor_desconto_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoServico',
            fields=[
                ('id_tipo_servico', models.AutoField(primary_key=True, serialize=False)),
                ('nome_servico', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('duracao_minutos', models.IntegerField(default=30, help_text='Duração estimada em minutos')),
                ('preco_base', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'petshop_tipo_servicos',
                'ordering': ['nome_servico'],
            },
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id_agendamento', models.AutoField(primary_key=True, serialize=False)),
                ('data_agendamento', models.DateTimeField()),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Agendado', 'Agendado'), ('Em Andamento', 'Em Andamento'), ('Concluído', 'Concluído'), ('Cancelado', 'Cancelado'), ('Não Compareceu', 'Não Compareceu')], default='Agendado', max_length=20)),
                ('preco_servico', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_modificacao', models.DateTimeField(auto_now=True)),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos_petshop', to='api.cliente')),
            ],
            options={
                'db_table': 'petshop_agendamentos',
                'ordering': ['-data_agendamento'],
            },
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id_avaliacao', models.AutoField(primary_key=True, serialize=False)),
                ('nota', models.IntegerField(choices=[(1, '⭐ Muito Ruim'), (2, '⭐⭐ Ruim'), (3, '⭐⭐⭐ Bom'), (4, '⭐⭐⭐⭐ Muito Bom'), (5, '⭐⭐⭐⭐⭐ Excelente')], default=5)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('data_avaliacao', models.DateTimeField(auto_now_add=True)),
                ('id_agendamento', models.ForeignKey(db_column='id_agendamento', on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='api.agendamento')),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, to='api.cliente')),
            ],
            options={
                'db_table': 'petshop_avaliacoes',
                'ordering': ['-data_avaliacao'],
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id_pet', models.AutoField(primary_key=True, serialize=False)),
                ('nome_pet', models.CharField(max_length=100)),
                ('raca', models.CharField(blank=True, max_length=100, null=True)),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('F', 'Fêmea')], default='M', max_length=1)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, help_text='Peso em kg', max_digits=5, null=True)),
                ('cor', models.CharField(blank=True, max_length=100, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='api.cliente')),
            ],
            options={
                'db_table': 'petshop_pets',
                'ordering': ['nome_pet'],
            },
        ),
        migrations.AddField(
            model_name='agendamento',
            name='id_pet',
            field=models.ForeignKey(db_column='id_pet', on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='api.pet'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='id_tipo_servico',
            field=models.ForeignKey(blank=True, db_column='id_tipo_servico', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.tiposervico'),
        ),
        migrations.AddIndex(
            model_name='agendamento',
            index=models.Index(fields=['id_cliente', 'data_agendamento'], name='petshop_age_id_clie_07d9a3_idx'),
        ),
        migrations.AddIndex(
            model_name='agendamento',
            index=models.Index(fields=['id_pet', 'status'], name='petshop_age_id_pet_8eb8f7_idx'),
        ),
    ]
