# Generated by Django 5.2.7 on 2025-11-17 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_tiposervico_agendamento_avaliacao_pet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='preco_total_pacote',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Preço total do pacote', max_digits=10),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='quantidade_sessoes',
            field=models.IntegerField(default=1, help_text='Número de sessões no pacote'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='tipo_agendamento',
            field=models.CharField(choices=[('Único', 'Serviço Único'), ('Pacote', 'Pacote de Serviços')], default='Único', max_length=10),
        ),
        migrations.CreateModel(
            name='SessaoAgendamento',
            fields=[
                ('id_sessao', models.AutoField(primary_key=True, serialize=False)),
                ('numero_sessao', models.IntegerField(help_text='Número sequencial da sessão (1, 2, 3...)')),
                ('data_sessao', models.DateTimeField()),
                ('data_realizacao', models.DateTimeField(blank=True, help_text='Data/hora que foi realizada', null=True)),
                ('status', models.CharField(choices=[('Agendada', 'Agendada'), ('Concluída', 'Concluída'), ('Cancelada', 'Cancelada')], default='Agendada', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('id_agendamento', models.ForeignKey(db_column='id_agendamento', on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to='api.agendamento')),
            ],
            options={
                'db_table': 'petshop_sessoes_agendamento',
                'ordering': ['numero_sessao'],
                'unique_together': {('id_agendamento', 'numero_sessao')},
            },
        ),
    ]
