# Generated by Django 5.2.7 on 2025-11-18 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_add_permissions_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id_log', models.AutoField(primary_key=True, serialize=False)),
                ('usuario_nome', models.CharField(max_length=150)),
                ('tipo_acao', models.CharField(choices=[('CREATE', 'Criação'), ('UPDATE', 'Edição'), ('DELETE', 'Exclusão'), ('VIEW', 'Visualização'), ('ESTORNO', 'Estorno'), ('CANCELAMENTO', 'Cancelamento'), ('APROVACAO', 'Aprovação'), ('BAIXA', 'Baixa'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('EXPORT', 'Exportação'), ('IMPORT', 'Importação'), ('PRINT', 'Impressão')], max_length=20)),
                ('modulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('tabela', models.CharField(blank=True, max_length=100, null=True)),
                ('registro_id', models.CharField(blank=True, max_length=100, null=True)),
                ('dados_anteriores', models.TextField(blank=True, null=True)),
                ('dados_novos', models.TextField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('data_hora', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('usuario', models.ForeignKey(db_column='id_user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'log_auditoria',
                'ordering': ['-data_hora'],
                'indexes': [models.Index(fields=['-data_hora'], name='log_auditor_data_ho_b3d8dc_idx'), models.Index(fields=['usuario', '-data_hora'], name='log_auditor_id_user_8c5abb_idx'), models.Index(fields=['modulo', '-data_hora'], name='log_auditor_modulo_ed306e_idx'), models.Index(fields=['tipo_acao', '-data_hora'], name='log_auditor_tipo_ac_bcca8c_idx')],
            },
        ),
    ]
