# Generated by Django 5.2.7 on 2025-11-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_logauditoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compra',
            options={},
        ),
        migrations.AlterModelOptions(
            name='compraitem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='venda',
            options={},
        ),
        migrations.AlterModelOptions(
            name='vendaitem',
            options={},
        ),
        migrations.AddField(
            model_name='operacao',
            name='validacao_limite_credito',
            field=models.CharField(blank=True, db_column='validacao_limite_credito', default='nao_validar', help_text='Define como validar o limite de crédito: nao_validar, alertar, bloquear, solicitar_senha', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='operacao',
            name='emitente',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
