# Generated by Django 5.2.7 on 2025-11-25 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_alter_compra_options_alter_compraitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
