# Generated by Django 5.2.7 on 2025-11-26 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_alter_produto_imagem_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacao',
            name='baixa_automatica',
            field=models.BooleanField(db_column='baixa_automatica', default=False, help_text='Se marcado, faz baixa automática quando data_documento = data_vencimento'),
        ),
        migrations.AddField(
            model_name='operacao',
            name='cashback_percentual',
            field=models.DecimalField(blank=True, db_column='cashback_percentual', decimal_places=2, default=0.0, help_text='Percentual de cashback gerado nas vendas (ex: 5.00 para 5%)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='operacao',
            name='cashback_validade_dias',
            field=models.IntegerField(blank=True, db_column='cashback_validade_dias', default=30, help_text='Quantidade de dias de validade do cashback gerado', null=True),
        ),
        migrations.CreateModel(
            name='Cashback',
            fields=[
                ('id_cashback', models.AutoField(db_column='id_cashback', primary_key=True, serialize=False)),
                ('valor_gerado', models.DecimalField(db_column='valor_gerado', decimal_places=2, default=0.0, help_text='Valor original de cashback gerado', max_digits=12)),
                ('valor_utilizado', models.DecimalField(db_column='valor_utilizado', decimal_places=2, default=0.0, help_text='Valor já utilizado deste cashback', max_digits=12)),
                ('saldo', models.DecimalField(db_column='saldo', decimal_places=2, default=0.0, help_text='Saldo disponível (gerado - utilizado)', max_digits=12)),
                ('data_geracao', models.DateTimeField(auto_now_add=True, db_column='data_geracao')),
                ('data_validade', models.DateTimeField(db_column='data_validade', help_text='Data de expiração do cashback')),
                ('data_utilizacao', models.DateTimeField(blank=True, db_column='data_utilizacao', help_text='Data da última utilização', null=True)),
                ('ativo', models.BooleanField(db_column='ativo', default=True, help_text='False se expirado ou totalmente utilizado')),
                ('percentual_origem', models.DecimalField(blank=True, db_column='percentual_origem', decimal_places=2, help_text='Percentual que gerou este cashback (para histórico)', max_digits=5, null=True)),
                ('observacoes', models.TextField(blank=True, db_column='observacoes', null=True)),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, related_name='cashbacks', to='api.cliente')),
                ('id_venda_origem', models.ForeignKey(blank=True, db_column='id_venda_origem', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashback_gerado', to='api.venda')),
                ('id_venda_utilizado', models.ForeignKey(blank=True, db_column='id_venda_utilizado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashback_utilizado', to='api.venda')),
            ],
            options={
                'db_table': 'cashbacks',
                'ordering': ['-data_geracao'],
                'indexes': [models.Index(fields=['id_cliente', 'ativo'], name='cashbacks_id_clie_0f36d4_idx'), models.Index(fields=['data_validade'], name='cashbacks_data_va_61ebf0_idx')],
            },
        ),
    ]
