# Generated by Django 5.2.7 on 2025-11-27 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_operacao_baixa_automatica_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id_ordem', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('data', models.DateField()),
                ('tipo_atendimento', models.CharField(choices=[('veiculo', 'Veículo'), ('animais', 'Animais'), ('equipamento', 'Equipamento')], default='equipamento', max_length=20)),
                ('veiculo_placa', models.CharField(blank=True, max_length=20, null=True)),
                ('veiculo_marca', models.CharField(blank=True, max_length=100, null=True)),
                ('veiculo_modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('veiculo_ano', models.IntegerField(blank=True, null=True)),
                ('veiculo_cor', models.CharField(blank=True, max_length=50, null=True)),
                ('veiculo_km', models.IntegerField(blank=True, null=True)),
                ('animal_nome', models.CharField(blank=True, max_length=100, null=True)),
                ('animal_especie', models.CharField(blank=True, max_length=100, null=True)),
                ('animal_raca', models.CharField(blank=True, max_length=100, null=True)),
                ('animal_idade', models.IntegerField(blank=True, null=True)),
                ('equipamento_tipo', models.CharField(blank=True, max_length=100, null=True)),
                ('equipamento_marca', models.CharField(blank=True, max_length=100, null=True)),
                ('equipamento_modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('equipamento_serie', models.CharField(blank=True, max_length=100, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('ocorrencia', models.TextField(blank=True, null=True)),
                ('solicitante', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('em_execucao', 'Em Execução'), ('fechado', 'Fechado'), ('cancelado', 'Cancelado')], default='aberto', max_length=20)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('id_cliente', models.ForeignKey(blank=True, db_column='id_cliente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.cliente')),
                ('id_operacao', models.ForeignKey(blank=True, db_column='id_operacao', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.operacao')),
                ('id_vendedor', models.ForeignKey(blank=True, db_column='id_vendedor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.vendedor')),
                ('usuario_atualizacao', models.ForeignKey(blank=True, db_column='usuario_atualizacao', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ordens_atualizadas', to=settings.AUTH_USER_MODEL)),
                ('usuario_criacao', models.ForeignKey(blank=True, db_column='usuario_criacao', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ordens_criadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ordem_servico',
                'ordering': ['-data', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='OrdemServicoItem',
            fields=[
                ('id_item', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('produto', 'Produto'), ('servico', 'Serviço')], default='produto', max_length=10)),
                ('descricao', models.TextField()),
                ('quantidade', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('id_ordem', models.ForeignKey(db_column='id_ordem', on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='api.ordemservico')),
                ('id_produto', models.ForeignKey(blank=True, db_column='id_produto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.produto')),
            ],
            options={
                'db_table': 'ordem_servico_itens',
                'ordering': ['id_item'],
            },
        ),
    ]
