# Generated by Django 5.2.7 on 2025-12-02 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_ordemservico_ordemservicoitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='OsItensProduto',
            fields=[
                ('id_os_item_produto', models.AutoField(db_column='id_os_item_produto', primary_key=True, serialize=False)),
                ('quantidade', models.DecimalField(db_column='quantidade', decimal_places=3, max_digits=10)),
                ('valor_unitario', models.DecimalField(db_column='valor_unitario', decimal_places=2, max_digits=10)),
                ('desconto', models.DecimalField(blank=True, db_column='desconto', decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('valor_total', models.DecimalField(db_column='valor_total', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'os_itens_produtos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OsItensServico',
            fields=[
                ('id_os_item_servico', models.AutoField(db_column='id_os_item_servico', primary_key=True, serialize=False)),
                ('descricao_servico', models.CharField(db_column='descricao_servico', max_length=255)),
                ('quantidade', models.DecimalField(db_column='quantidade', decimal_places=2, max_digits=10)),
                ('valor_unitario', models.DecimalField(db_column='valor_unitario', decimal_places=2, max_digits=10)),
                ('desconto', models.DecimalField(blank=True, db_column='desconto', decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('valor_total', models.DecimalField(db_column='valor_total', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'os_itens_servicos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StatusOrdemServico',
            fields=[
                ('id_status', models.AutoField(primary_key=True, serialize=False)),
                ('nome_status', models.CharField(max_length=50, unique=True)),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('cor', models.CharField(default='blue', help_text='primary, success, warning, error, info', max_length=20)),
                ('ordem', models.IntegerField(default=0, help_text='Ordem de exibição')),
                ('ativo', models.BooleanField(default=True)),
                ('padrao', models.BooleanField(default=False, help_text='Status padrão para novas OS')),
                ('gera_financeiro', models.BooleanField(db_column='gera_financeiro', default=False, help_text='Gera financeiro ao definir este status')),
                ('permite_editar', models.BooleanField(default=True)),
                ('permite_excluir', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Status de Ordem de Serviço',
                'verbose_name_plural': 'Status de Ordens de Serviço',
                'db_table': 'status_ordem_servico',
                'ordering': ['ordem', 'nome_status'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TabelaComercial',
            fields=[
                ('id_tabela_comercial', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Tabela')),
                ('percentual', models.DecimalField(decimal_places=2, default=0.0, help_text='Ex: 10.00 = +10%, -15.00 = -15%', max_digits=5, verbose_name='Percentual de Ajuste')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('padrao', models.BooleanField(default=False, verbose_name='Padrão')),
                ('perguntar_ao_vender', models.BooleanField(db_column='perguntar_ao_vender', default=False, help_text='Se marcado, pergunta ao adicionar produto e ao gerar financeiro na venda rápida', verbose_name='Perguntar ao Vender')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tabelas_comerciais',
                'ordering': ['nome'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id_tecnico', models.AutoField(db_column='id_tecnico', primary_key=True, serialize=False)),
                ('nome_tecnico', models.CharField(db_column='nome_tecnico', max_length=255)),
                ('cpf', models.CharField(blank=True, db_column='cpf', max_length=14, null=True)),
                ('telefone', models.CharField(blank=True, db_column='telefone', max_length=20, null=True)),
                ('percentual_comissao', models.DecimalField(blank=True, db_column='percentual_comissao', decimal_places=2, max_digits=5, null=True)),
                ('ativo', models.BooleanField(db_column='ativo', default=True)),
            ],
            options={
                'db_table': 'tecnicos',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='ordemservico',
            options={'managed': False, 'ordering': ['-data_abertura']},
        ),
        migrations.AddField(
            model_name='compra',
            name='gerou_financeiro',
            field=models.IntegerField(blank=True, db_column='gerou_financeiro', default=0, null=True),
        ),
        migrations.AddField(
            model_name='operacao',
            name='abreviacao',
            field=models.CharField(blank=True, default='', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='operacao',
            name='acao_atraso',
            field=models.CharField(blank=True, db_column='acao_atraso', default='alertar', help_text='Ação quando cliente em atraso: alertar, bloquear, solicitar_senha', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='operacao',
            name='acao_estoque',
            field=models.CharField(blank=True, db_column='acao_estoque', default='nao_validar', help_text='Ação quando não há estoque: nao_validar, alertar, bloquear, solicitar_senha', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='operacao',
            name='dias_atraso_tolerancia',
            field=models.IntegerField(blank=True, db_column='dias_atraso_tolerancia', default=0, help_text='Quantidade de dias de tolerância para atraso (0 = não tolera nenhum atraso)', null=True),
        ),
        migrations.AddField(
            model_name='operacao',
            name='validar_atraso',
            field=models.BooleanField(db_column='validar_atraso', default=False, help_text='Se TRUE, valida se cliente tem títulos em atraso'),
        ),
        migrations.AddField(
            model_name='operacao',
            name='validar_estoque',
            field=models.BooleanField(db_column='validar_estoque', default=False, help_text='Se TRUE, valida se há estoque disponível antes de permitir a venda'),
        ),
        migrations.DeleteModel(
            name='OrdemServicoItem',
        ),
    ]
