# Generated by Django 6.0 on 2025-12-06 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_ositensproduto_ositensservico_statusordemservico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='data_entrada',
            field=models.DateField(blank=True, db_column='data_entrada', null=True),
        ),
    ]
