# Generated by Django 6.0 on 2025-12-11 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_compra_data_entrada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id_cheque', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('receber', 'A Receber'), ('pagar', 'A Pagar')], default='receber', max_length=10)),
                ('numero_cheque', models.CharField(max_length=50)),
                ('banco', models.CharField(max_length=100)),
                ('agencia', models.CharField(max_length=20)),
                ('conta', models.CharField(max_length=30)),
                ('emitente', models.CharField(help_text='Nome de quem emitiu o cheque', max_length=255)),
                ('cpf_cnpj_emitente', models.CharField(blank=True, max_length=18, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_emissao', models.DateField()),
                ('data_vencimento', models.DateField(help_text='Data do bom para')),
                ('data_deposito', models.DateField(blank=True, null=True)),
                ('data_compensacao', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('custodia', 'Em Custódia'), ('depositado', 'Depositado'), ('compensado', 'Compensado'), ('devolvido', 'Devolvido'), ('repassado', 'Repassado'), ('cancelado', 'Cancelado')], default='custodia', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('imagem_cheque', models.CharField(blank=True, help_text='URL da foto do cheque', max_length=500, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cheque',
                'verbose_name_plural': 'Cheques',
                'db_table': 'cheques',
                'ordering': ['-data_vencimento'],
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='operacao',
            name='entrega_futura',
            field=models.BooleanField(db_column='entrega_futura', default=False, help_text='Se TRUE, esta operação é para vendas com entrega futura'),
        ),
        migrations.AddField(
            model_name='operacao',
            name='tipo_entrega_futura',
            field=models.CharField(blank=True, db_column='tipo_entrega_futura', default='origem', help_text='Define se é operação de origem (pedido) ou destino (entrega): origem, destino', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='venda_futura_destino',
            field=models.ForeignKey(blank=True, db_column='venda_futura_destino', help_text='Venda de entrega futura gerada a partir desta venda', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas_origem_futuras', to='api.venda'),
        ),
        migrations.AddField(
            model_name='venda',
            name='venda_futura_origem',
            field=models.ForeignKey(blank=True, db_column='venda_futura_origem', help_text='Venda de origem que gerou esta entrega futura', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas_futuras_destino', to='api.venda'),
        ),
        migrations.AddField(
            model_name='vendaitem',
            name='quantidade_entregue',
            field=models.DecimalField(db_column='quantidade_entregue', decimal_places=3, default=0.0, help_text='Quantidade já entregue deste item (para entregas parciais)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='compra',
            name='valor_desconto',
            field=models.DecimalField(blank=True, db_column='valor_desconto', decimal_places=6, default=0.0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='valor_total',
            field=models.DecimalField(db_column='valor_total_nota', decimal_places=6, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='compraitem',
            name='desconto',
            field=models.DecimalField(blank=True, db_column='valor_desconto', decimal_places=6, default=0.0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='compraitem',
            name='quantidade',
            field=models.DecimalField(db_column='quantidade', decimal_places=6, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='compraitem',
            name='valor_compra',
            field=models.DecimalField(db_column='valor_unitario', decimal_places=6, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='compraitem',
            name='valor_total',
            field=models.DecimalField(db_column='valor_total', decimal_places=6, default=0.0, max_digits=15),
        ),
    ]
