# Generated by Django 6.0 on 2025-12-12 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_cheque_operacao_entrega_futura_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id_equipamento', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(help_text='Código único do equipamento', max_length=50, unique=True)),
                ('nome', models.CharField(help_text='Nome/descrição do equipamento', max_length=255)),
                ('descricao', models.TextField(blank=True, help_text='Descrição detalhada', null=True)),
                ('categoria', models.CharField(blank=True, help_text='Categoria do equipamento', max_length=100, null=True)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('alugado', 'Alugado'), ('manutencao', 'Manutenção'), ('inativo', 'Inativo')], default='disponivel', max_length=20)),
                ('valor_diaria', models.DecimalField(decimal_places=2, help_text='Valor da diária de aluguel', max_digits=10)),
                ('valor_semanal', models.DecimalField(blank=True, decimal_places=2, help_text='Valor para 7 dias', max_digits=10, null=True)),
                ('valor_mensal', models.DecimalField(blank=True, decimal_places=2, help_text='Valor para 30 dias', max_digits=10, null=True)),
                ('imagem_url', models.TextField(blank=True, help_text='URL ou base64 da imagem', null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'equipamentos',
                'ordering': ['nome'],
                'managed': True,
                'indexes': [models.Index(fields=['codigo'], name='equipamento_codigo_4e0430_idx'), models.Index(fields=['status'], name='equipamento_status_530c23_idx'), models.Index(fields=['categoria'], name='equipamento_categor_777747_idx')],
            },
        ),
        migrations.CreateModel(
            name='Aluguel',
            fields=[
                ('id_aluguel', models.AutoField(primary_key=True, serialize=False)),
                ('numero_aluguel', models.CharField(help_text='Número único do aluguel', max_length=50, unique=True)),
                ('data_inicio', models.DateField(help_text='Data de início do aluguel')),
                ('data_fim_prevista', models.DateField(help_text='Data prevista para devolução')),
                ('data_fim_real', models.DateField(blank=True, help_text='Data real da devolução', null=True)),
                ('quantidade_dias', models.IntegerField(help_text='Quantidade de dias do aluguel')),
                ('valor_diaria', models.DecimalField(decimal_places=2, help_text='Valor da diária no momento do aluguel', max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, help_text='Valor total do aluguel', max_digits=10)),
                ('valor_multa', models.DecimalField(decimal_places=2, default=0, help_text='Multa por atraso na devolução', max_digits=10)),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=0, help_text='Desconto aplicado', max_digits=10)),
                ('valor_final', models.DecimalField(decimal_places=2, help_text='Valor final com multas e descontos', max_digits=10)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='ativo', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.PROTECT, to='api.cliente')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', help_text='Usuário que registrou o aluguel', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('id_equipamento', models.ForeignKey(db_column='id_equipamento', on_delete=django.db.models.deletion.PROTECT, to='api.equipamento')),
            ],
            options={
                'db_table': 'alugueis',
                'ordering': ['-data_cadastro'],
                'managed': True,
                'indexes': [models.Index(fields=['numero_aluguel'], name='alugueis_numero__1b43ed_idx'), models.Index(fields=['id_cliente', 'status'], name='alugueis_id_clie_5d31b4_idx'), models.Index(fields=['id_equipamento', 'status'], name='alugueis_id_equi_c5ee7e_idx'), models.Index(fields=['data_inicio'], name='alugueis_data_in_80b97d_idx'), models.Index(fields=['status'], name='alugueis_status_fdd2b8_idx')],
            },
        ),
    ]
