# Generated by Django 6.0 on 2025-12-12 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_equipamento_aluguel'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='equipamento',
            new_name='equipamento_codigo_5c9cc6_idx',
            old_name='equipamento_codigo_4e0430_idx',
        ),
        migrations.RenameIndex(
            model_name='equipamento',
            new_name='equipamento_status_a0834d_idx',
            old_name='equipamento_status_530c23_idx',
        ),
        migrations.RenameIndex(
            model_name='equipamento',
            new_name='equipamento_categor_0bf4cf_idx',
            old_name='equipamento_categor_777747_idx',
        ),
        migrations.AlterModelTable(
            name='equipamento',
            table='equipamentos_aluguel',
        ),
    ]
