# Generated by Django 6.0 on 2025-12-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_rename_equipamento_codigo_4e0430_idx_equipamento_codigo_5c9cc6_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeiroconta',
            name='id_aluguel_origem',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
