# Generated by Django 6.0 on 2025-12-12 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_add_aluguel_origem_financeiro'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AluguelItem',
            fields=[
                ('id_item', models.AutoField(primary_key=True, serialize=False)),
                ('data_devolucao_prevista', models.DateField(help_text='Data prevista para devolução deste item')),
                ('data_devolucao_real', models.DateField(blank=True, help_text='Data real da devolução', null=True)),
                ('quantidade_dias', models.IntegerField(help_text='Quantidade de dias')),
                ('valor_diaria', models.DecimalField(decimal_places=2, help_text='Valor da diária', max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, help_text='Valor total do item', max_digits=10)),
                ('valor_multa', models.DecimalField(decimal_places=2, default=0, help_text='Multa por atraso', max_digits=10)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('devolvido', 'Devolvido'), ('cancelado', 'Cancelado')], default='ativo', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'alugueis_itens',
                'ordering': ['id_aluguel', 'id_item'],
                'managed': True,
            },
        ),
        migrations.RemoveIndex(
            model_name='aluguel',
            name='alugueis_id_equi_c5ee7e_idx',
        ),
        migrations.AlterField(
            model_name='aluguel',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', help_text='Usuário que registrou', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aluguel',
            name='valor_final',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor final', max_digits=10),
        ),
        migrations.AlterField(
            model_name='aluguel',
            name='valor_multa',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Multa por atraso', max_digits=10),
        ),
        migrations.AlterField(
            model_name='aluguel',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor total do aluguel', max_digits=10),
        ),
        migrations.AddField(
            model_name='aluguelitem',
            name='id_aluguel',
            field=models.ForeignKey(db_column='id_aluguel', on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='api.aluguel'),
        ),
        migrations.AddField(
            model_name='aluguelitem',
            name='id_equipamento',
            field=models.ForeignKey(db_column='id_equipamento', on_delete=django.db.models.deletion.PROTECT, to='api.equipamento'),
        ),
        migrations.RemoveField(
            model_name='aluguel',
            name='data_fim_real',
        ),
        migrations.RemoveField(
            model_name='aluguel',
            name='id_equipamento',
        ),
        migrations.RemoveField(
            model_name='aluguel',
            name='quantidade_dias',
        ),
        migrations.RemoveField(
            model_name='aluguel',
            name='valor_diaria',
        ),
        migrations.AddIndex(
            model_name='aluguelitem',
            index=models.Index(fields=['id_aluguel'], name='alugueis_it_id_alug_df003d_idx'),
        ),
        migrations.AddIndex(
            model_name='aluguelitem',
            index=models.Index(fields=['id_equipamento', 'status'], name='alugueis_it_id_equi_dadf05_idx'),
        ),
        migrations.AddIndex(
            model_name='aluguelitem',
            index=models.Index(fields=['data_devolucao_prevista'], name='alugueis_it_data_de_e08e42_idx'),
        ),
    ]
