# Generated by Django 6.0 on 2025-12-13 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_configuracaocontrato'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracaocontrato',
            options={'managed': True, 'verbose_name': 'Configuração de Contrato', 'verbose_name_plural': 'Configurações de Contratos'},
        ),
        migrations.AlterField(
            model_name='configuracaocontrato',
            name='id_configuracao',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
