# Generated by Django 6.0 on 2026-02-05 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_alter_configuracaocontrato_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='classificacao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
