# Generated by Django 6.0 on 2026-02-05 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_alter_produto_classificacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='classificacao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
