# Generated by Django 6.0 on 2026-02-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_alter_produto_classificacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='classificacao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
