# Generated by Django 6.0.2 on 2026-02-06 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_alter_produto_classificacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='TributacaoProduto',
            fields=[
                ('id_tributacao', models.AutoField(primary_key=True, serialize=False)),
                ('classificacao_fiscal', models.CharField(blank=True, max_length=50, null=True)),
                ('cst_pis_cofins', models.CharField(blank=True, default='000', max_length=10, null=True)),
                ('cst_icms', models.CharField(blank=True, default='000', max_length=10, null=True)),
                ('cst_ipi', models.CharField(blank=True, default='000', max_length=10, null=True)),
                ('icms_aliquota', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('marketing_icms', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('pis_aliquota', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('cofins_aliquota', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('ipi_aliquota', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('ibs_aliquota', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('cbs_aliquota', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('imposto_seletivo_aliquota', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('fonte_info', models.CharField(blank=True, max_length=100, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('produto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tributacao_detalhada', to='api.produto')),
            ],
            options={
                'db_table': 'tributacao_produto',
                'managed': True,
            },
        ),
    ]
