# Generated by Django 6.0.2 on 2026-02-07 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_tributacaoproduto'),
    ]

    operations = [
        migrations.AddField(
            model_name='formapagamento',
            name='codigo_t_pag',
            field=models.CharField(blank=True, default='99', help_text='Código SEFAZ (01=Dinheiro, 03=Crédito, 04=Débito, etc)', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='chave_nfe',
            field=models.CharField(blank=True, db_column='chave_nfe', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='numero_nfe',
            field=models.IntegerField(blank=True, db_column='numero_nfe', null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='protocolo_nfe',
            field=models.CharField(blank=True, db_column='protocolo_nfe', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='qrcode_nfe',
            field=models.TextField(blank=True, db_column='qrcode_nfe', null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='serie_nfe',
            field=models.IntegerField(db_column='serie_nfe', default=1),
        ),
        migrations.AddField(
            model_name='venda',
            name='status_nfe',
            field=models.CharField(db_column='status_nfe', default='PENDENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='venda',
            name='xml_nfe',
            field=models.TextField(blank=True, db_column='xml_nfe', null=True),
        ),
    ]
