# Generated by Django 6.0.2 on 2026-02-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_add_qrcode_nfe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeiroconta',
            name='status_conta',
            field=models.CharField(default='Pendente', max_length=50),
        ),
    ]
