# Generated by Django 6.0.2 on 2026-02-08 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_alter_financeiroconta_status_conta'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='especie_volumes',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='marca_volumes',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='observacao_fisco',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='peso_bruto',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='venda',
            name='peso_liquido',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='venda',
            name='placa_veiculo',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='quantidade_volumes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='venda',
            name='rntrc',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='tipo_frete',
            field=models.IntegerField(default=9, help_text='0=Rem, 1=Dest, 9=Sem Frete'),
        ),
        migrations.AddField(
            model_name='venda',
            name='transportadora',
            field=models.ForeignKey(blank=True, db_column='id_transportadora', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas_transportadas', to='api.cliente'),
        ),
        migrations.AddField(
            model_name='venda',
            name='uf_veiculo',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
