# Generated by Django 6.0.2 on 2026-02-08 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_venda_especie_volumes_venda_marca_volumes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='observacao_contribuinte',
            field=models.TextField(blank=True, null=True),
        ),
    ]
