# Generated by Django 6.0.2 on 2026-02-12 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_venda_observacao_contribuinte'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id_veiculo', models.AutoField(primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('ano', models.IntegerField(blank=True, null=True)),
                ('cor', models.CharField(blank=True, max_length=50, null=True)),
                ('chassi', models.CharField(blank=True, max_length=50, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('rntrc', models.CharField(blank=True, max_length=20, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'veiculos',
                'managed': False,
            },
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='AtributoVariacao',
                    fields=[
                        ('id_atributo', models.AutoField(primary_key=True, serialize=False)),
                        ('nome', models.CharField(max_length=50, unique=True)),
                    ],
                    options={
                        'db_table': 'atributos_variacao',
                        'managed': True,
                    },
                ),
                migrations.CreateModel(
                    name='Safra',
                    fields=[
                        ('id_safra', models.AutoField(primary_key=True, serialize=False)),
                        ('descricao', models.CharField(help_text='Ex: Soja 24/25, Milho Safrinha 24', max_length=100)),
                        ('data_inicio', models.DateField()),
                        ('data_fim', models.DateField()),
                        ('ativo', models.BooleanField(default=True)),
                    ],
                    options={
                        'db_table': 'safras',
                        'ordering': ['-data_inicio'],
                        'managed': True,
                    },
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='tributacaoproduto',
                    name='cst_ibs_cbs',
                    field=models.CharField(blank=True, default='410', max_length=10, null=True),
                ),
            ],
            database_operations=[],
        ),
        migrations.CreateModel(
            name='ContratoAgricola',
            fields=[
                ('id_contrato', models.AutoField(primary_key=True, serialize=False)),
                ('numero_contrato', models.CharField(max_length=50, unique=True)),
                ('quantidade_negociada', models.DecimalField(decimal_places=3, help_text='Quantidade a entregar (na unidade do contrato)', max_digits=15)),
                ('unidade_medida', models.CharField(help_text="Unidade (Ex: 'sc', 'ton')", max_length=20)),
                ('valor_unitario', models.DecimalField(decimal_places=2, help_text='Preço travado por unidade', max_digits=12)),
                ('valor_total_contrato', models.DecimalField(decimal_places=2, help_text='Valor total estimado', max_digits=15)),
                ('data_emissao', models.DateField()),
                ('data_entrega', models.DateField(help_text='Previsão de entrega da colheita')),
                ('status', models.CharField(choices=[('Aberto', 'Aberto'), ('Liquidado', 'Liquidado'), ('Cancelado', 'Cancelado')], default='Aberto', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('id_cliente', models.ForeignKey(help_text='Produtor Rural', on_delete=django.db.models.deletion.PROTECT, to='api.cliente')),
                ('id_produto_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos_barter', to='api.produto')),
                ('id_safra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.safra')),
            ],
            options={
                'db_table': 'contratos_agricolas',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='financeiroconta',
            name='id_contrato_agricola',
            field=models.ForeignKey(blank=True, db_column='id_contrato_agricola', help_text='Vínculo com Contrato de Barter', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.contratoagricola'),
        ),
        migrations.CreateModel(
            name='ConversaoUnidade',
            fields=[
                ('id_conversao', models.AutoField(primary_key=True, serialize=False)),
                ('unidade_origem', models.CharField(help_text="Unidade que o usuário digita (Ex: 'sc', 'ton')", max_length=20)),
                ('unidade_destino', models.CharField(help_text="Unidade base do sistema (Ex: 'kg', 'lt')", max_length=20)),
                ('fator_conversao', models.DecimalField(decimal_places=4, help_text='Fator multiplicador para converter Origem -> Destino', max_digits=12)),
                ('operacao', models.CharField(choices=[('M', 'Multiplicar'), ('D', 'Dividir')], default='M', max_length=1)),
                ('id_produto', models.ForeignKey(blank=True, help_text='Se vazio, regra aplica a todos', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.produto')),
            ],
            options={
                'db_table': 'conversoes_unidades',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProdutoVariacao',
            fields=[
                ('id_variacao', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_barras', models.CharField(blank=True, max_length=50, null=True)),
                ('referencia_variacao', models.CharField(blank=True, max_length=50, null=True)),
                ('preco_venda', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('imagem_url', models.TextField(blank=True, null=True)),
                ('id_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variacoes', to='api.produto')),
            ],
            options={
                'db_table': 'produtos_variacoes',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='estoque',
            name='id_variacao',
            field=models.ForeignKey(blank=True, db_column='id_variacao', help_text='Variação específica (Grade)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.produtovariacao'),
        ),
        migrations.AddField(
            model_name='vendaitem',
            name='id_variacao',
            field=models.ForeignKey(blank=True, db_column='id_variacao', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.produtovariacao'),
        ),
        migrations.AddField(
            model_name='financeiroconta',
            name='id_safra',
            field=models.ForeignKey(blank=True, db_column='id_safra', help_text='Vínculo com Safra (Agro)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.safra'),
        ),
        migrations.CreateModel(
            name='ValorAtributoVariacao',
            fields=[
                ('id_valor', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.CharField(max_length=50)),
                ('id_atributo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='api.atributovariacao')),
            ],
            options={
                'db_table': 'valores_atributo_variacao',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProdutoVariacaoCombinacao',
            fields=[
                ('id_combinacao', models.AutoField(primary_key=True, serialize=False)),
                ('id_variacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.produtovariacao')),
                ('id_valor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.valoratributovariacao')),
            ],
            options={
                'db_table': 'produtos_variacoes_combinacao',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='produtovariacao',
            name='valores',
            field=models.ManyToManyField(through='api.ProdutoVariacaoCombinacao', to='api.valoratributovariacao'),
        ),
    ]
