# Generated by Django 6.0.2 on 2026-02-12 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_veiculo_atributovariacao_safra_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConjuntoOperacao',
            fields=[
                ('id_conjunto', models.AutoField(primary_key=True, serialize=False)),
                ('nome_conjunto', models.CharField(help_text='Nome do conjunto de operações', max_length=100)),
                ('descricao', models.TextField(blank=True, help_text='Descrição detalhada do conjunto', null=True)),
                ('ativo', models.BooleanField(default=True, help_text='Se o conjunto está ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, help_text='Data de criação do conjunto')),
                ('data_modificacao', models.DateTimeField(auto_now=True, help_text='Data da última modificação')),
                ('operacoes', models.ManyToManyField(help_text='Operações que fazem parte deste conjunto', related_name='conjuntos', to='api.operacao')),
            ],
            options={
                'verbose_name': 'Conjunto de Operação',
                'verbose_name_plural': 'Conjuntos de Operações',
                'db_table': 'conjunto_operacoes',
                'ordering': ['nome_conjunto'],
                'managed': True,
            },
        ),
    ]
