# Generated by Django 6.0.2 on 2026-02-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_conjuntooperacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoProduto',
            fields=[
                ('id_config', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_geracao_codigo', models.CharField(choices=[('automatica', 'Automática'), ('semi-automatica', 'Semi-Automática'), ('manual', 'Manual')], default='manual', help_text='Tipo de geração do código do produto', max_length=20)),
                ('proximo_codigo', models.IntegerField(default=1, help_text='Próximo código a ser gerado (usado em automática e semi-automática)')),
                ('prefixo_codigo', models.CharField(blank=True, help_text='Prefixo opcional para o código (ex: PROD, P, etc.)', max_length=10, null=True)),
                ('tamanho_codigo', models.IntegerField(default=6, help_text='Tamanho do código numérico (será preenchido com zeros à esquerda)')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_modificacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de Produto',
                'verbose_name_plural': 'Configurações de Produto',
                'db_table': 'configuracao_produto',
                'managed': True,
            },
        ),
    ]
