# Generated by Django 6.0.2 on 2026-02-12 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_configuracaoproduto'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoproduto',
            name='controlar_lote_validade',
            field=models.BooleanField(default=False, help_text='Habilita o controle de lote e validade nos produtos'),
        ),
        migrations.CreateModel(
            name='LoteProduto',
            fields=[
                ('id_lote', models.AutoField(primary_key=True, serialize=False)),
                ('numero_lote', models.CharField(help_text='Número identificador do lote', max_length=50)),
                ('data_fabricacao', models.DateField(blank=True, null=True)),
                ('data_validade', models.DateField(help_text='Data de validade do lote')),
                ('quantidade', models.DecimalField(decimal_places=3, default=0.0, max_digits=12)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_modificacao', models.DateTimeField(auto_now=True)),
                ('id_produto', models.ForeignKey(db_column='id_produto', on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='api.produto')),
            ],
            options={
                'verbose_name': 'Lote de Produto',
                'verbose_name_plural': 'Lotes de Produtos',
                'db_table': 'lotes_produto',
                'ordering': ['data_validade'],
                'managed': True,
            },
        ),
    ]
