# Generated by Django 6.0.2 on 2026-02-13 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0076_configuracaoproduto_controlar_lote_validade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoproduto',
            name='produto_em_grade',
            field=models.BooleanField(default=False, help_text='Habilita a opção de marcar produto em grade no cadastro de produtos'),
        ),
    ]
