# Generated by Django 6.0.2 on 2026-02-13 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0077_configuracaoproduto_produto_em_grade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControleCaixa',
            fields=[
                ('id_caixa', models.AutoField(primary_key=True, serialize=False)),
                ('data_abertura', models.DateTimeField(auto_now_add=True)),
                ('valor_abertura', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('data_fechamento', models.DateTimeField(blank=True, null=True)),
                ('valor_fechamento', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(default='ABERTO', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='caixas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'controle_caixa',
                'ordering': ['-data_abertura'],
                'managed': True,
            },
        ),
    ]
