# Generated by Django 6.0.2 on 2026-02-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0078_venda_mensagem_nfe_controlecaixa'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimentacaoCaixa',
            fields=[
                ('id_movimentacao', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('SUPRIMENTO', 'Suprimento'), ('SANGRIA', 'Sangria')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_movimentacao', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'movimentacao_caixa',
                'ordering': ['-data_movimentacao'],
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='venda',
            name='mensagem_nfe',
            field=models.TextField(blank=True, db_column='mensagem_nfe', help_text='Ultima mensagem de erro ou status da NFe/NFCe', null=True),
        ),
    ]
