# Generated by Django 6.0.2 on 2026-02-16 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0079_movimentacaocaixa_venda_mensagem_nfe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresaconfig',
            options={'managed': True},
        ),
    ]
