# Generated by Django 6.0.2 on 2026-02-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0080_alter_empresaconfig_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresaconfig',
            name='sped_aproveita_credito_icms',
            field=models.BooleanField(default=True, verbose_name='Aproveita ICMS ST e IPI'),
        ),
        migrations.AddField(
            model_name='empresaconfig',
            name='sped_bloco_k_deposito',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empresaconfig',
            name='sped_bloco_k_grupo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empresaconfig',
            name='sped_bloco_k_leiaute',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empresaconfig',
            name='sped_bloco_k_preco',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empresaconfig',
            name='sped_centro_custo_credito',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empresaconfig',
            name='sped_centro_custo_debito',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empresaconfig',
            name='sped_finalidade',
            field=models.CharField(default='0', help_text='0-Remessa Original, 1-Retificadora', max_length=1),
        ),
        migrations.AddField(
            model_name='empresaconfig',
            name='sped_gerar_bloco_c',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='empresaconfig',
            name='sped_gerar_bloco_c_vazio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='empresaconfig',
            name='sped_gerar_bloco_d',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='empresaconfig',
            name='sped_gerar_bloco_e',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='empresaconfig',
            name='sped_gerar_bloco_g',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='empresaconfig',
            name='sped_gerar_bloco_h',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='empresaconfig',
            name='sped_gerar_bloco_k',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='empresaconfig',
            name='sped_operacao_bloco_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empresaconfig',
            name='sped_operacao_entrada_bloco_0',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empresaconfig',
            name='sped_operacao_entrada_bloco_c',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empresaconfig',
            name='sped_operacao_entrada_bloco_d',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empresaconfig',
            name='sped_operacao_saida_bloco_0',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empresaconfig',
            name='sped_operacao_saida_bloco_c',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empresaconfig',
            name='sped_operacao_saida_bloco_d',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empresaconfig',
            name='sped_verifica_contingencia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='empresaconfig',
            name='sped_versao',
            field=models.CharField(default='020', help_text='Versão do Layout (ex: 020)', max_length=3),
        ),
    ]
