# Generated by Django 6.0.2 on 2026-02-16 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0081_empresaconfig_ambiente_cte_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresaconfig',
            options={'managed': False},
        ),
    ]
