# Generated by Django 6.0.2 on 2026-02-20 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0083_add_sped_contribuicoes_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='tributacaoproduto',
            name='cfop',
            field=models.CharField(blank=True, default='5102', max_length=10, null=True),
        ),
    ]
