# Generated by Django 6.0.2 on 2026-02-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0084_add_cfop_tributacao_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='tributacaoproduto',
            name='cfop_entrada',
            field=models.CharField(blank=True, default='1102', help_text='CFOP de entrada/compra (ex: 1102 compra nacional)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tributacaoproduto',
            name='csosn',
            field=models.CharField(blank=True, default='400', help_text='CSOSN p/ Simples Nacional (ex: 102, 400, 500)', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tributacaoproduto',
            name='cfop',
            field=models.CharField(blank=True, default='5102', help_text='CFOP de saída/venda (ex: 5102 venda mercadoria adq p/ revenda)', max_length=10, null=True),
        ),
    ]
