# Generated by Django 6.0.2 on 2026-02-20 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0085_add_csosn_cfop_entrada_tributacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tributacaoproduto',
            name='cfop_entrada',
        ),
        migrations.RemoveField(
            model_name='tributacaoproduto',
            name='csosn',
        ),
        migrations.AlterField(
            model_name='tributacaoproduto',
            name='cfop',
            field=models.CharField(blank=True, default='5102', max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='RegraFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regime_tributario', models.CharField(blank=True, choices=[('SIMPLES', 'Simples Nacional'), ('MEI', 'MEI'), ('LUCRO_PRESUMIDO', 'Lucro Presumido'), ('LUCRO_REAL', 'Lucro Real'), ('NORMAL', 'Regime Normal (sem especificação)')], help_text='Preenchido quando a regra é de regime (fallback), não de empresa específica', max_length=20, null=True)),
                ('ncm_codigo', models.CharField(db_index=True, help_text='NCM de 8 dígitos', max_length=8)),
                ('cest_codigo', models.CharField(blank=True, help_text='CEST (7 dígitos) — obrigatório para ST', max_length=7, null=True)),
                ('tipo_operacao', models.CharField(choices=[('INTERNA', 'Venda Interna (mesmo estado)'), ('INTERESTADUAL', 'Venda Interestadual'), ('EXPORTACAO', 'Exportação'), ('DEVOLUCAO', 'Devolução'), ('BRINDE', 'Brinde / Bonificação'), ('TRANSFERENCIA', 'Transferência entre Filiais'), ('COMPRA', 'Compra / Entrada'), ('RURAL', 'Nota de Produtor Rural (Agro)')], default='INTERNA', max_length=20)),
                ('uf_destino', models.CharField(blank=True, choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], help_text='Nulo = regra válida para qualquer UF destino', max_length=2, null=True)),
                ('cfop', models.CharField(blank=True, default='5102', help_text='CFOP padrão para esta combinação (ex: 5102, 6102, 5405)', max_length=5, null=True)),
                ('c_benef', models.CharField(blank=True, help_text='Código de Benefício Fiscal (cBenef) — obrigatório MG e outros', max_length=10, null=True)),
                ('c_class_trib', models.CharField(blank=True, help_text='Código Classificação Tributária Reforma 2026 (essencial, luxo, etc.)', max_length=10, null=True)),
                ('icms_cst_csosn', models.CharField(blank=True, default='400', help_text='CST (Regime Normal) ou CSOSN (Simples Nacional)', max_length=3, null=True)),
                ('icms_modalidade_bc', models.CharField(blank=True, default='3', help_text='Modalidade base cálculo: 0-MV, 1-Pauta, 2-PF, 3-Valor Op.', max_length=1, null=True)),
                ('icms_aliq', models.DecimalField(decimal_places=4, default=0.0, max_digits=7)),
                ('icms_reducao_bc_perc', models.DecimalField(decimal_places=4, default=0.0, help_text='% Redução Base Cálculo ICMS (pRedBC)', max_digits=7)),
                ('icms_desonerado', models.DecimalField(decimal_places=2, default=0.0, help_text='vICMSDeson — insumos agrícolas isentos, Agro', max_digits=10)),
                ('icmsst_aliq', models.DecimalField(decimal_places=4, default=0.0, max_digits=7)),
                ('icmsst_mva_perc', models.DecimalField(decimal_places=4, default=0.0, help_text='Margem de Valor Agregado ST (pMVAST)', max_digits=7)),
                ('icmsst_reducao_bc_perc', models.DecimalField(decimal_places=4, default=0.0, max_digits=7)),
                ('pis_cst', models.CharField(blank=True, default='07', max_length=2, null=True)),
                ('pis_aliq', models.DecimalField(decimal_places=4, default=1.65, max_digits=7)),
                ('cofins_cst', models.CharField(blank=True, default='07', max_length=2, null=True)),
                ('cofins_aliq', models.DecimalField(decimal_places=4, default=7.6, max_digits=7)),
                ('ipi_cst', models.CharField(blank=True, default='99', max_length=2, null=True)),
                ('ipi_aliq', models.DecimalField(decimal_places=4, default=0.0, max_digits=7)),
                ('ipi_classe_enquadramento', models.CharField(blank=True, help_text='Classe de Enquadramento IPI (clEnq)', max_length=5, null=True)),
                ('ibs_cst', models.CharField(blank=True, default='410', max_length=3, null=True)),
                ('ibs_aliq', models.DecimalField(decimal_places=4, default=0.1, help_text='IBS — alíquota teste 2026 (pIBS)', max_digits=7)),
                ('cbs_cst', models.CharField(blank=True, default='410', max_length=3, null=True)),
                ('cbs_aliq', models.DecimalField(decimal_places=4, default=0.9, help_text='CBS — alíquota teste 2026 (pCBS)', max_digits=7)),
                ('is_aliq', models.DecimalField(decimal_places=4, default=0.0, help_text='Imposto Seletivo (IS) — produtos de luxo/nocivos', max_digits=7)),
                ('diferimento_icms_perc', models.DecimalField(decimal_places=4, default=0.0, help_text='% Diferimento ICMS — produtor rural / agro', max_digits=7)),
                ('funrural_aliq', models.DecimalField(decimal_places=4, default=0.0, help_text='Alíquota Funrural (incide sobre nota de produtor rural)', max_digits=7)),
                ('senar_aliq', models.DecimalField(decimal_places=4, default=0.0, help_text='Alíquota SENAR', max_digits=5)),
                ('ativo', models.BooleanField(default=True)),
                ('descricao', models.CharField(blank=True, help_text='Descrição livre da regra (ex: "Simples Revenda MG")', max_length=255, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(blank=True, help_text='Nulo = regra genérica de regime (fallback)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regras_fiscais', to='api.empresaconfig')),
            ],
            options={
                'verbose_name': 'Regra Fiscal',
                'verbose_name_plural': 'Regras Fiscais',
                'db_table': 'regras_fiscais',
                'ordering': ['ncm_codigo', 'tipo_operacao'],
                'managed': True,
                'indexes': [models.Index(fields=['empresa', 'ncm_codigo', 'tipo_operacao'], name='regras_fisc_empresa_eeae12_idx'), models.Index(fields=['regime_tributario', 'ncm_codigo'], name='regras_fisc_regime__127a24_idx'), models.Index(fields=['ncm_codigo'], name='regras_fisc_ncm_cod_9b3d52_idx')],
                'unique_together': {('empresa', 'ncm_codigo', 'tipo_operacao', 'uf_destino')},
            },
        ),
    ]
