# Generated by Django 6.0.2 on 2026-02-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0086_add_regra_fiscal_matriz'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='regrafiscal',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='regrafiscal',
            name='split_payment',
            field=models.BooleanField(default=False, help_text='Split Payment: quando True, o pagamento fiscal é recolhido diretamente pela instituição financeira (exigência Reforma 2026)'),
        ),
        migrations.AddField(
            model_name='regrafiscal',
            name='tipo_cliente',
            field=models.CharField(blank=True, choices=[('TODOS', 'Todos (sem distinção)'), ('CONSUMIDOR_FINAL', 'Consumidor Final (Pessoa Física / Não Contribuinte)'), ('REVENDEDOR', 'Revendedor / Contribuinte ICMS')], default='TODOS', help_text='Tipo de cliente destino — impacta aplicação de ICMS-ST e alíquota difal', max_length=20),
        ),
        migrations.AddField(
            model_name='regrafiscal',
            name='tipo_produto_reform',
            field=models.CharField(blank=True, choices=[('PADRAO', 'Alíquota Padrão'), ('REDUZIDA_50', 'Reduzida 50% (saúde, educação básica…)'), ('REDUZIDA_100', 'Reduzida 100% (cesta básica ampliada)'), ('ZERO', 'Alíquota Zero (cesta básica nacional)'), ('ISENTO', 'Isento'), ('IMUNE', 'Imune'), ('LUXO', 'Imposto Seletivo — Produto de Luxo'), ('NOCIVO', 'Imposto Seletivo — Produto Nocivo')], default='PADRAO', help_text='Classificação do produto para IBS/CBS na Reforma 2026', max_length=15),
        ),
        migrations.AddField(
            model_name='regrafiscal',
            name='uf_origem',
            field=models.CharField(blank=True, choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], help_text='UF de origem (emitente). Nulo = regra independente de origem', max_length=2, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='regrafiscal',
            unique_together={('empresa', 'ncm_codigo', 'tipo_operacao', 'uf_destino', 'uf_origem', 'tipo_cliente')},
        ),
        migrations.AddIndex(
            model_name='regrafiscal',
            index=models.Index(fields=['empresa', 'ncm_codigo', 'tipo_operacao', 'uf_destino'], name='regras_fisc_empresa_6ea746_idx'),
        ),
        migrations.AddIndex(
            model_name='regrafiscal',
            index=models.Index(fields=['tipo_produto_reform'], name='regras_fisc_tipo_pr_981237_idx'),
        ),
    ]
