# Generated by Django 6.0.2 on 2026-02-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0090_tributacaoproduto_add_sn_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='tributacao_info',
        ),
        migrations.AlterField(
            model_name='tributacaoproduto',
            name='csosn',
            field=models.CharField(blank=True, default='400', max_length=10, null=True),
        ),
    ]
