# Generated by Django 6.0.2 on 2026-02-20 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0091_remove_tributacao_info_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tributacaoproduto',
            name='classificacao_fiscal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
