# Generated by Django 6.0.2 on 2026-02-20 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0092_fix_classificacao_fiscal_maxlength'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='gtin',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
