# Generated by Django 6.0.2 on 2026-02-24 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0093_produto_gtin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManifestacaoNFe',
            fields=[
                ('id_manifestacao', models.AutoField(primary_key=True, serialize=False)),
                ('chave_nfe', models.CharField(db_index=True, max_length=44)),
                ('numero_nfe', models.CharField(blank=True, max_length=20, null=True)),
                ('serie', models.CharField(blank=True, max_length=5, null=True)),
                ('emitente_nome', models.CharField(blank=True, max_length=255, null=True)),
                ('emitente_cnpj', models.CharField(blank=True, max_length=18, null=True)),
                ('valor_nfe', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('data_emissao', models.DateField(blank=True, null=True)),
                ('tipo_evento', models.CharField(choices=[('210210', 'Ciência da Operação'), ('210200', 'Confirmação da Operação'), ('210240', 'Desconhecimento da Operação'), ('210220', 'Operação não Realizada')], max_length=6)),
                ('n_seq_evento', models.IntegerField(default=1)),
                ('justificativa', models.TextField(blank=True, help_text='Obrigatório para Operação não Realizada (mín. 15 chars)', null=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('AUTORIZADO', 'Autorizado pela SEFAZ'), ('REJEITADO', 'Rejeitado pela SEFAZ'), ('ERRO', 'Erro de Comunicação')], default='PENDENTE', max_length=20)),
                ('c_stat', models.CharField(blank=True, help_text='Código de status retornado pela SEFAZ', max_length=6, null=True)),
                ('x_motivo', models.TextField(blank=True, help_text='Motivo retornado pela SEFAZ', null=True)),
                ('protocolo', models.CharField(blank=True, max_length=50, null=True)),
                ('dh_reg_evento', models.DateTimeField(blank=True, null=True)),
                ('xml_evento', models.TextField(blank=True, null=True)),
                ('xml_retorno', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manifestacoes_criadas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(blank=True, db_column='id_empresa', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manifestacoes', to='api.empresaconfig')),
            ],
            options={
                'db_table': 'manifestacao_nfe',
                'ordering': ['-criado_em'],
                'unique_together': {('chave_nfe', 'tipo_evento', 'n_seq_evento')},
            },
        ),
    ]
