# Generated by Django 6.0.2 on 2026-02-24 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0094_manifestacao_nfe'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='xml_conteudo',
            field=models.TextField(blank=True, db_column='xml_conteudo', null=True),
        ),
    ]
