# Generated by Django 6.0.2 on 2026-02-24 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0096_add_tributacao_padrao_to_config_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('id_veterinario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('crmv', models.CharField(help_text='Número do CRMV (ex: SP-12345)', max_length=30, unique=True)),
                ('especialidade', models.CharField(blank=True, help_text='Ex: Clínica Geral, Dermatologia, Ortopedia', max_length=100, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'clinica_veterinarios',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='pet',
            name='especie',
            field=models.CharField(choices=[('Cachorro', 'Cachorro'), ('Gato', 'Gato'), ('Ave', 'Ave'), ('Coelho', 'Coelho'), ('Hamster', 'Hamster'), ('Réptil', 'Réptil'), ('Peixe', 'Peixe'), ('Outro', 'Outro')], default='Cachorro', max_length=30),
        ),
        migrations.AddField(
            model_name='pet',
            name='microchip',
            field=models.CharField(blank=True, help_text='Número do microchip', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='ConsultaVeterinaria',
            fields=[
                ('id_consulta', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_consulta', models.CharField(choices=[('Rotina', 'Consulta de Rotina'), ('Retorno', 'Retorno'), ('Urgência', 'Urgência/Emergência'), ('Pós-operatório', 'Pós-operatório'), ('Vacinação', 'Vacinação'), ('Exame', 'Coleta / Exame'), ('Cirurgia', 'Cirurgia'), ('Outro', 'Outro')], default='Rotina', max_length=20)),
                ('data_consulta', models.DateTimeField()),
                ('status', models.CharField(choices=[('Agendada', 'Agendada'), ('Em Atendimento', 'Em Atendimento'), ('Concluída', 'Concluída'), ('Cancelada', 'Cancelada')], default='Agendada', max_length=20)),
                ('queixa_principal', models.TextField(blank=True, help_text='Motivo da consulta / queixa principal', null=True)),
                ('historico_clinico', models.TextField(blank=True, help_text='Histórico clínico relevante', null=True)),
                ('peso_consulta', models.DecimalField(blank=True, decimal_places=2, help_text='Peso registrado na consulta (kg)', max_digits=5, null=True)),
                ('temperatura', models.DecimalField(blank=True, decimal_places=1, help_text='Temperatura corporal (°C)', max_digits=4, null=True)),
                ('frequencia_cardiaca', models.IntegerField(blank=True, help_text='Frequência cardíaca (bpm)', null=True)),
                ('frequencia_respiratoria', models.IntegerField(blank=True, help_text='Frequência respiratória (rpm)', null=True)),
                ('diagnostico', models.TextField(blank=True, null=True)),
                ('tratamento', models.TextField(blank=True, help_text='Tratamento prescrito / procedimentos realizados', null=True)),
                ('receituario', models.TextField(blank=True, help_text='Medicamentos: nome, dose, frequência, duração', null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('retorno_previsto', models.DateField(blank=True, help_text='Data prevista para retorno', null=True)),
                ('valor_consulta', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_modificacao', models.DateTimeField(auto_now=True)),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, related_name='consultas_vet', to='api.cliente')),
                ('id_pet', models.ForeignKey(db_column='id_pet', on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='api.pet')),
                ('id_veterinario', models.ForeignKey(blank=True, db_column='id_veterinario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas', to='api.veterinario')),
            ],
            options={
                'db_table': 'clinica_consultas',
                'ordering': ['-data_consulta'],
            },
        ),
        migrations.CreateModel(
            name='VacinaAplicada',
            fields=[
                ('id_vacina', models.AutoField(primary_key=True, serialize=False)),
                ('nome_vacina', models.CharField(help_text='Ex: V8, V10, Antirrábica, Giárdia, Gripe Felina', max_length=100)),
                ('fabricante', models.CharField(blank=True, max_length=100, null=True)),
                ('lote', models.CharField(blank=True, max_length=50, null=True)),
                ('data_aplicacao', models.DateField()),
                ('proxima_dose', models.DateField(blank=True, help_text='Data prevista para a próxima dose / reforço', null=True)),
                ('via_aplicacao', models.CharField(blank=True, help_text='Ex: Subcutânea, Intranasal', max_length=30, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('id_pet', models.ForeignKey(db_column='id_pet', on_delete=django.db.models.deletion.CASCADE, related_name='vacinas', to='api.pet')),
                ('id_veterinario', models.ForeignKey(blank=True, db_column='id_veterinario', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.veterinario')),
            ],
            options={
                'db_table': 'clinica_vacinas',
                'ordering': ['-data_aplicacao'],
            },
        ),
        migrations.CreateModel(
            name='Internacao',
            fields=[
                ('id_internacao', models.AutoField(primary_key=True, serialize=False)),
                ('motivo', models.CharField(choices=[('Pós-operatório', 'Pós-operatório'), ('Tratamento Clínico', 'Tratamento Clínico'), ('Observação', 'Observação'), ('Cirurgia Eletiva', 'Cirurgia Eletiva'), ('Emergência', 'Emergência'), ('Outro', 'Outro')], default='Tratamento Clínico', max_length=30)),
                ('descricao_motivo', models.TextField(blank=True, null=True)),
                ('data_entrada', models.DateTimeField()),
                ('data_alta', models.DateTimeField(blank=True, help_text='Deixe em branco se ainda internado', null=True)),
                ('numero_baia', models.CharField(blank=True, help_text='Número da baia / box', max_length=20, null=True)),
                ('evolucao_clinica', models.TextField(blank=True, help_text='Evolução clínica e procedimentos realizados durante a internação', null=True)),
                ('dieta', models.CharField(blank=True, help_text='Dieta / alimentação prescrita', max_length=200, null=True)),
                ('medicamentos', models.TextField(blank=True, help_text='Medicamentos: nome, dose, frequência, via', null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('valor_diaria', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_modificacao', models.DateTimeField(auto_now=True)),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, related_name='internacoes_vet', to='api.cliente')),
                ('id_pet', models.ForeignKey(db_column='id_pet', on_delete=django.db.models.deletion.CASCADE, related_name='internacoes', to='api.pet')),
                ('id_veterinario', models.ForeignKey(blank=True, db_column='id_veterinario', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.veterinario')),
            ],
            options={
                'db_table': 'clinica_internacoes',
                'ordering': ['-data_entrada'],
            },
        ),
        migrations.CreateModel(
            name='ExameLaboratorial',
            fields=[
                ('id_exame', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_exame', models.CharField(choices=[('Hemograma', 'Hemograma'), ('Bioquímico', 'Bioquímico'), ('Urinálise', 'Urinálise'), ('Parasitológico', 'Parasitológico'), ('Raio-X', 'Raio-X'), ('Ultrassom', 'Ultrassom'), ('Ecocardiograma', 'Ecocardiograma'), ('Citologia', 'Citologia'), ('Histopatológico', 'Histopatológico'), ('PCR', 'PCR'), ('Sorologia', 'Sorologia'), ('Outro', 'Outro')], default='Hemograma', max_length=30)),
                ('descricao', models.CharField(blank=True, help_text='Descrição detalhada do exame', max_length=200, null=True)),
                ('data_solicitacao', models.DateField()),
                ('data_resultado', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Solicitado', 'Solicitado'), ('Coletado', 'Amostras Coletadas'), ('Aguardando', 'Aguardando Resultado'), ('Concluído', 'Resultado Disponível'), ('Cancelado', 'Cancelado')], default='Solicitado', max_length=20)),
                ('resultado', models.TextField(blank=True, help_text='Resultado/laudo do exame', null=True)),
                ('laboratorio', models.CharField(blank=True, max_length=100, null=True)),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('id_consulta', models.ForeignKey(blank=True, db_column='id_consulta', help_text='Consulta na qual o exame foi solicitado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exames', to='api.consultaveterinaria')),
                ('id_pet', models.ForeignKey(db_column='id_pet', on_delete=django.db.models.deletion.CASCADE, related_name='exames', to='api.pet')),
                ('id_veterinario', models.ForeignKey(blank=True, db_column='id_veterinario', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.veterinario')),
            ],
            options={
                'db_table': 'clinica_exames',
                'ordering': ['-data_solicitacao'],
            },
        ),
        migrations.AddIndex(
            model_name='consultaveterinaria',
            index=models.Index(fields=['id_pet', 'data_consulta'], name='clinica_con_id_pet_735075_idx'),
        ),
        migrations.AddIndex(
            model_name='consultaveterinaria',
            index=models.Index(fields=['status', 'data_consulta'], name='clinica_con_status_1ed486_idx'),
        ),
    ]
