# Generated by Django 6.0.2 on 2026-02-24 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0097_add_clinica_veterinaria'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaoDeObraAgro',
            fields=[
                ('id_trabalhador', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('funcao', models.CharField(blank=True, help_text='Ex: Tratorista, Peão, Operador de Pulverizador', max_length=100, null=True)),
                ('tipo', models.CharField(choices=[('CLT', 'CLT / Efetivo'), ('Diarista', 'Diarista'), ('Terceirizado', 'Terceirizado'), ('Empreiteiro', 'Empreiteiro'), ('Sazonal', 'Sazonal')], default='Diarista', max_length=15)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('valor_diaria', models.DecimalField(decimal_places=2, default=0, help_text='R$ por diária', max_digits=10)),
                ('valor_hora', models.DecimalField(decimal_places=2, default=0, help_text='R$ por hora', max_digits=10)),
                ('ativo', models.BooleanField(default=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'agro_mao_de_obra',
                'ordering': ['nome'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MaquinarioAgro',
            fields=[
                ('id_maquinario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Ex: Trator John Deere 6110J', max_length=150)),
                ('tipo', models.CharField(choices=[('Trator', 'Trator'), ('Colheitadeira', 'Colheitadeira'), ('Pulverizador', 'Pulverizador'), ('Plantadeira', 'Plantadeira'), ('Semeadeira', 'Semeadeira'), ('Grade', 'Grade / Niveladora'), ('Caminhão', 'Caminhão'), ('Implemento', 'Implemento'), ('Outro', 'Outro')], default='Trator', max_length=20)),
                ('marca', models.CharField(blank=True, max_length=80, null=True)),
                ('modelo', models.CharField(blank=True, max_length=80, null=True)),
                ('ano_fabricacao', models.IntegerField(blank=True, null=True)),
                ('placa', models.CharField(blank=True, max_length=15, null=True)),
                ('horimetro_atual', models.DecimalField(decimal_places=1, default=0, help_text='Horímetro atual (horas)', max_digits=10)),
                ('valor_hora', models.DecimalField(decimal_places=2, default=0, help_text='Custo por hora operacional (R$)', max_digits=10)),
                ('capacidade', models.CharField(blank=True, help_text='Ex: 180 cv, tanque 2000L', max_length=60, null=True)),
                ('status', models.CharField(choices=[('Disponível', 'Disponível'), ('Em Uso', 'Em Uso'), ('Manutenção', 'Manutenção'), ('Inativo', 'Inativo')], default='Disponível', max_length=15)),
                ('ativo', models.BooleanField(default=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'agro_maquinarios',
                'ordering': ['tipo', 'nome'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Talhao',
            fields=[
                ('id_talhao', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Ex: Talhão A - Soja 24/25', max_length=100)),
                ('cultura', models.CharField(choices=[('Soja', 'Soja'), ('Milho', 'Milho'), ('Trigo', 'Trigo'), ('Sorgo', 'Sorgo'), ('Algodão', 'Algodão'), ('Cana', 'Cana-de-Açúcar'), ('Café', 'Café'), ('Feijão', 'Feijão'), ('Arroz', 'Arroz'), ('Pastagem', 'Pastagem'), ('Outro', 'Outro')], default='Soja', max_length=20)),
                ('variedade', models.CharField(blank=True, max_length=100, null=True)),
                ('area_hectares', models.DecimalField(decimal_places=4, help_text='Área em hectares', max_digits=10)),
                ('data_plantio', models.DateField(blank=True, null=True)),
                ('data_colheita_prevista', models.DateField(blank=True, null=True)),
                ('data_colheita_real', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Planejado', 'Planejado'), ('Plantado', 'Plantado'), ('Em Desenvolvimento', 'Em Desenvolvimento'), ('Colhido', 'Colhido'), ('Cancelado', 'Cancelado')], default='Planejado', max_length=25)),
                ('produtividade_prevista', models.DecimalField(blank=True, decimal_places=2, help_text='Produtividade prevista (sc/ha)', max_digits=10, null=True)),
                ('produtividade_real', models.DecimalField(blank=True, decimal_places=2, help_text='Produtividade real obtida (sc/ha)', max_digits=10, null=True)),
                ('populacao_plantas', models.IntegerField(blank=True, help_text='Plantas por hectare', null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('id_safra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talhoes', to='api.safra')),
            ],
            options={
                'db_table': 'agro_talhoes',
                'ordering': ['id_safra', 'nome'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LancamentoMaquinario',
            fields=[
                ('id_lancamento_maq', models.AutoField(primary_key=True, serialize=False)),
                ('operacao', models.CharField(choices=[('Preparo Solo', 'Preparo do Solo'), ('Plantio', 'Plantio / Semeadura'), ('Adubação', 'Adubação / Fertirrigação'), ('Pulverização', 'Pulverização'), ('Irrigação', 'Irrigação'), ('Colheita', 'Colheita'), ('Transporte', 'Transporte'), ('Manutenção', 'Manutenção'), ('Outro', 'Outro')], default='Outro', max_length=20)),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('horas_trabalhadas', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('area_trabalhada_ha', models.DecimalField(blank=True, decimal_places=4, help_text='Área trabalhada em ha', max_digits=10, null=True)),
                ('operador', models.CharField(blank=True, max_length=100, null=True)),
                ('combustivel_litros', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, help_text='Custo total (horas × valor_hora)', max_digits=14)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('id_safra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos_maquinario', to='api.safra')),
                ('id_maquinario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='api.maquinarioagro')),
                ('id_talhao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos_maquinario', to='api.talhao')),
            ],
            options={
                'db_table': 'agro_lancamentos_maquinario',
                'ordering': ['-data_inicio'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LancamentoMaoDeObra',
            fields=[
                ('id_lancamento_mdo', models.AutoField(primary_key=True, serialize=False)),
                ('nome_avulso', models.CharField(blank=True, help_text='Nome de trabalhador avulso não cadastrado', max_length=150, null=True)),
                ('atividade', models.CharField(choices=[('Preparo Solo', 'Preparo do Solo'), ('Plantio', 'Plantio / Semeadura'), ('Adubação', 'Adubação'), ('Pulverização', 'Pulverização'), ('Irrigação', 'Irrigação'), ('Capina', 'Capina / Controle Plantas'), ('Colheita', 'Colheita'), ('Pós-Colheita', 'Pós-Colheita / Limpeza'), ('Manutenção', 'Manutenção Máquinas'), ('Transporte', 'Transporte'), ('Outro', 'Outro')], default='Outro', max_length=20)),
                ('data', models.DateField()),
                ('quantidade', models.DecimalField(decimal_places=2, default=1, help_text='Dias / horas / unidades conforme tipo_pagamento', max_digits=8)),
                ('tipo_pagamento', models.CharField(choices=[('Diária', 'Diária'), ('Hora', 'Hora'), ('Empreitada', 'Empreitada'), ('Mensal', 'Mensal')], default='Diária', max_length=12)),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('id_safra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos_mdo', to='api.safra')),
                ('id_trabalhador', models.ForeignKey(blank=True, help_text='Trabalhador cadastrado (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos', to='api.maodeobraagro')),
                ('id_talhao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos_mdo', to='api.talhao')),
            ],
            options={
                'db_table': 'agro_lancamentos_mdo',
                'ordering': ['-data'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DespesaAgro',
            fields=[
                ('id_despesa', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(choices=[('Sementes', 'Sementes'), ('Fertilizantes', 'Fertilizantes'), ('Defensivos', 'Defensivos'), ('Combustível', 'Combustível'), ('Energia', 'Energia'), ('Manutenção', 'Manutenção'), ('Mão de Obra', 'Mão de Obra'), ('Transporte', 'Transporte'), ('Armazenagem', 'Armazenagem'), ('Seguro', 'Seguro'), ('Arrendamento', 'Arrendamento'), ('Consultoria', 'Consultoria'), ('Outros', 'Outros')], default='Outros', max_length=20)),
                ('descricao', models.CharField(max_length=200)),
                ('data_lancamento', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('quantidade', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('unidade', models.CharField(blank=True, help_text='Ex: kg, L, sc, ha', max_length=20, null=True)),
                ('fornecedor', models.CharField(blank=True, max_length=150, null=True)),
                ('numero_nota', models.CharField(blank=True, max_length=50, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('id_safra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesas', to='api.safra')),
                ('id_talhao', models.ForeignKey(blank=True, help_text='Deixe em branco para despesa geral da safra', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despesas', to='api.talhao')),
            ],
            options={
                'db_table': 'agro_despesas',
                'ordering': ['-data_lancamento'],
                'managed': True,
            },
        ),
    ]
