# Generated by Django 6.0.2 on 2026-02-26 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0098_add_agro_operacional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartaCorrecaoNFe',
            fields=[
                ('id_carta_correcao', models.AutoField(primary_key=True, serialize=False)),
                ('numero_sequencial', models.IntegerField(help_text='Número sequencial da CCe (1, 2, 3...). Cada NFe pode ter múltiplas CCe.')),
                ('texto_correcao', models.TextField(help_text='Texto da correção (mínimo 15 caracteres)')),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('protocolo', models.CharField(blank=True, max_length=50, null=True)),
                ('xml_evento', models.TextField(blank=True, help_text='XML do evento de CCe (retorno da SEFAZ)', null=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('REGISTRADO', 'Registrado'), ('REJEITADO', 'Rejeitado'), ('ERRO', 'Erro')], default='PENDENTE', max_length=20)),
                ('mensagem_retorno', models.TextField(blank=True, help_text='Mensagem de retorno da SEFAZ', null=True)),
            ],
            options={
                'db_table': 'carta_correcao_nfe',
                'ordering': ['-data_envio'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ComplementoICMSNFe',
            fields=[
                ('id_complemento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_complemento', models.CharField(choices=[('ICMS', 'ICMS'), ('ICMS_ST', 'ICMS-ST'), ('IPI', 'IPI'), ('DIFAL', 'Diferencial de Alíquota'), ('OUTROS', 'Outros')], default='ICMS', max_length=20)),
                ('valor_complemento', models.DecimalField(decimal_places=2, help_text='Valor do imposto a complementar', max_digits=14)),
                ('base_calculo', models.DecimalField(blank=True, decimal_places=2, help_text='Base de cálculo do complemento', max_digits=14, null=True)),
                ('aliquota', models.DecimalField(blank=True, decimal_places=4, help_text='Alíquota aplicada', max_digits=7, null=True)),
                ('motivo', models.TextField(help_text='Motivo do complemento (ex: Diferença de alíquota interestadual)')),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EMITIDA', 'Emitida'), ('CANCELADA', 'Cancelada'), ('ERRO', 'Erro')], default='PENDENTE', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_emissao', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'complemento_icms_nfe',
                'ordering': ['-data_criacao'],
                'managed': True,
            },
        ),
        migrations.RemoveIndex(
            model_name='consultaveterinaria',
            name='clinica_con_id_pet_735075_idx',
        ),
        migrations.RemoveIndex(
            model_name='consultaveterinaria',
            name='clinica_con_status_1ed486_idx',
        ),
        migrations.RemoveField(
            model_name='examelaboratorial',
            name='id_consulta',
        ),
        migrations.RemoveField(
            model_name='examelaboratorial',
            name='id_pet',
        ),
        migrations.RemoveField(
            model_name='examelaboratorial',
            name='id_veterinario',
        ),
        migrations.RemoveField(
            model_name='internacao',
            name='id_cliente',
        ),
        migrations.RemoveField(
            model_name='internacao',
            name='id_pet',
        ),
        migrations.RemoveField(
            model_name='internacao',
            name='id_veterinario',
        ),
        migrations.RemoveField(
            model_name='vacinaaplicada',
            name='id_pet',
        ),
        migrations.RemoveField(
            model_name='vacinaaplicada',
            name='id_veterinario',
        ),
        migrations.AlterModelOptions(
            name='manifestacaonfe',
            options={'managed': True, 'ordering': ['-criado_em']},
        ),
        migrations.AlterUniqueTogether(
            name='manifestacaonfe',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='compra',
            name='xml_conteudo',
        ),
        migrations.RemoveField(
            model_name='configuracaoproduto',
            name='trib_cfop',
        ),
        migrations.RemoveField(
            model_name='configuracaoproduto',
            name='trib_classificacao_fiscal',
        ),
        migrations.RemoveField(
            model_name='configuracaoproduto',
            name='trib_cofins_aliquota',
        ),
        migrations.RemoveField(
            model_name='configuracaoproduto',
            name='trib_csosn',
        ),
        migrations.RemoveField(
            model_name='configuracaoproduto',
            name='trib_cst_icms',
        ),
        migrations.RemoveField(
            model_name='configuracaoproduto',
            name='trib_cst_ipi',
        ),
        migrations.RemoveField(
            model_name='configuracaoproduto',
            name='trib_cst_pis_cofins',
        ),
        migrations.RemoveField(
            model_name='configuracaoproduto',
            name='trib_icms_aliquota',
        ),
        migrations.RemoveField(
            model_name='configuracaoproduto',
            name='trib_ipi_aliquota',
        ),
        migrations.RemoveField(
            model_name='configuracaoproduto',
            name='trib_pis_aliquota',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='especie',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='microchip',
        ),
        migrations.AddField(
            model_name='manifestacaonfe',
            name='usuario',
            field=models.ForeignKey(blank=True, help_text='Usuário que criou a manifestação', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='manifestacaonfe',
            name='c_stat',
            field=models.CharField(blank=True, help_text='Código de status do retorno SEFAZ', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='manifestacaonfe',
            name='chave_nfe',
            field=models.CharField(help_text='Chave de acesso da NFe (44 dígitos)', max_length=44),
        ),
        migrations.AlterField(
            model_name='manifestacaonfe',
            name='dh_reg_evento',
            field=models.DateTimeField(blank=True, help_text='Data/hora de registro do evento na SEFAZ', null=True),
        ),
        migrations.AlterField(
            model_name='manifestacaonfe',
            name='emitente_cnpj',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='manifestacaonfe',
            name='justificativa',
            field=models.TextField(blank=True, help_text='Justificativa (obrigatória para Operação não Realizada ou Desconhecimento)', null=True),
        ),
        migrations.AlterField(
            model_name='manifestacaonfe',
            name='n_seq_evento',
            field=models.IntegerField(default=1, help_text='Número sequencial do evento'),
        ),
        migrations.AlterField(
            model_name='manifestacaonfe',
            name='numero_nfe',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manifestacaonfe',
            name='protocolo',
            field=models.CharField(blank=True, help_text='Número do protocolo de autorização', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='manifestacaonfe',
            name='serie',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manifestacaonfe',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('ENVIADO', 'Enviado'), ('REGISTRADO', 'Registrado'), ('REJEITADO', 'Rejeitado'), ('ERRO', 'Erro')], default='PENDENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='manifestacaonfe',
            name='tipo_evento',
            field=models.CharField(choices=[('210200', 'Confirmação da Operação'), ('210210', 'Ciência da Operação'), ('210220', 'Operação não Realizada'), ('210240', 'Desconhecimento da Operação')], help_text='Código do tipo de evento (210200, 210210, 210220, 210240)', max_length=6),
        ),
        migrations.AlterField(
            model_name='manifestacaonfe',
            name='valor_nfe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='manifestacaonfe',
            name='x_motivo',
            field=models.TextField(blank=True, help_text='Descrição do motivo retornado pela SEFAZ', null=True),
        ),
        migrations.AlterField(
            model_name='manifestacaonfe',
            name='xml_evento',
            field=models.TextField(blank=True, help_text='XML completo do evento de manifestação', null=True),
        ),
        migrations.AddIndex(
            model_name='manifestacaonfe',
            index=models.Index(fields=['chave_nfe'], name='manifestaca_chave_n_542ad5_idx'),
        ),
        migrations.AddIndex(
            model_name='manifestacaonfe',
            index=models.Index(fields=['status'], name='manifestaca_status_f83233_idx'),
        ),
        migrations.AddIndex(
            model_name='manifestacaonfe',
            index=models.Index(fields=['tipo_evento'], name='manifestaca_tipo_ev_30694d_idx'),
        ),
        migrations.AddField(
            model_name='cartacorrecaonfe',
            name='id_venda',
            field=models.ForeignKey(db_column='id_venda', on_delete=django.db.models.deletion.CASCADE, related_name='cartas_correcao', to='api.venda'),
        ),
        migrations.AddField(
            model_name='cartacorrecaonfe',
            name='usuario',
            field=models.ForeignKey(blank=True, help_text='Usuário que criou a CCe', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complementoicmsnfe',
            name='id_venda_complemento',
            field=models.ForeignKey(blank=True, db_column='id_venda_complemento', help_text='NFe de complemento gerada', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complementos_icms', to='api.venda'),
        ),
        migrations.AddField(
            model_name='complementoicmsnfe',
            name='id_venda_referencia',
            field=models.ForeignKey(db_column='id_venda_referencia', help_text='NFe original que está sendo complementada', on_delete=django.db.models.deletion.PROTECT, related_name='complementos_icms_referencia', to='api.venda'),
        ),
        migrations.AddField(
            model_name='complementoicmsnfe',
            name='usuario',
            field=models.ForeignKey(blank=True, help_text='Usuário que criou o complemento', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='consultaveterinaria',
            name='id_cliente',
        ),
        migrations.RemoveField(
            model_name='consultaveterinaria',
            name='id_pet',
        ),
        migrations.RemoveField(
            model_name='consultaveterinaria',
            name='id_veterinario',
        ),
        migrations.DeleteModel(
            name='ExameLaboratorial',
        ),
        migrations.DeleteModel(
            name='Internacao',
        ),
        migrations.DeleteModel(
            name='VacinaAplicada',
        ),
        migrations.RemoveField(
            model_name='manifestacaonfe',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='manifestacaonfe',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='manifestacaonfe',
            name='xml_retorno',
        ),
        migrations.AlterUniqueTogether(
            name='cartacorrecaonfe',
            unique_together={('id_venda', 'numero_sequencial')},
        ),
        migrations.DeleteModel(
            name='ConsultaVeterinaria',
        ),
        migrations.DeleteModel(
            name='Veterinario',
        ),
    ]
