# Generated by Django 6.0.2 on 2026-03-02 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0099_add_carta_correcao_nfe'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegraFiscalReforma',
            fields=[
                ('id_regra', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(help_text='Ex: Regra Geral Bebidas Frias', max_length=100)),
                ('ativo', models.BooleanField(default=True)),
                ('ncm_prefixo', models.CharField(db_index=True, help_text="Pode ser o NCM completo (8 dig) ou prefixo (ex: '22' para todas as bebidas)", max_length=10)),
                ('uf_destino', models.CharField(choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], default='MG', max_length=2)),
                ('tipo_operacao', models.CharField(choices=[('CONSUMO', 'Consumo Final'), ('REVENDA', 'Revenda')], default='CONSUMO', max_length=20)),
                ('cst_ibs_cbs', models.CharField(default='01', help_text='Novo Código de Situação Tributária', max_length=5)),
                ('aliquota_ibs', models.DecimalField(decimal_places=2, default=0.0, help_text='% IBS (Estadual/Municipal)', max_digits=5)),
                ('aliquota_cbs', models.DecimalField(decimal_places=2, default=0.0, help_text='% CBS (Federal)', max_digits=5)),
                ('aliquota_is', models.DecimalField(decimal_places=2, default=0.0, help_text='% Imposto Seletivo (Imposto do Pecado)', max_digits=5)),
                ('is_split_elegivel', models.BooleanField(default=False, help_text='Se True, aciona a lógica de pagamento dividido na maquininha/Pix')),
            ],
            options={
                'db_table': 'regras_fiscais_reforma',
                'indexes': [models.Index(fields=['ncm_prefixo', 'uf_destino'], name='regras_fisc_ncm_pre_f004b6_idx')],
            },
        ),
        migrations.CreateModel(
            name='SplitPaymentConfig',
            fields=[
                ('id_config', models.AutoField(primary_key=True, serialize=False)),
                ('meio_pagamento', models.CharField(choices=[('PIX', 'Pix (QR Code Dinâmico)'), ('CARTAO', 'Cartão Crédito/Débito (TEF)'), ('BOLETO', 'Boleto Híbrido')], max_length=10)),
                ('chave_pix_destino', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_banco_tef', models.CharField(blank=True, help_text='Código da instituição para roteamento TEF', max_length=10, null=True)),
                ('regra_fiscal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='api.regrafiscalreforma')),
            ],
            options={
                'db_table': 'split_payment_config',
            },
        ),
    ]
