# Generated by Django 6.0.2 on 2026-03-02 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0100_produto_metragem_caixa_produto_peso_unitario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='metragem_caixa',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Metragem em m² que cada caixa cobre (pisos/revestimentos)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='peso_unitario',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Peso unitário em kg para controle de carga', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='produto_pai',
            field=models.ForeignKey(blank=True, db_column='id_produto_pai', help_text='Produto Pai para variações (ex: Cano PVC)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variacoes_simples', to='api.produto'),
        ),
        migrations.AddField(
            model_name='produto',
            name='rendimento_m2',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rendimento em m² por unidade (tintas)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='variacao',
            field=models.CharField(blank=True, help_text='Descrição da variação (ex: 20mm, 25mm, Branco)', max_length=100, null=True),
        ),
    ]
