# Generated by Django 6.0.2 on 2026-03-02 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0101_produto_metragem_caixa_produto_peso_unitario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAtalho',
            fields=[
                ('id_atalho', models.AutoField(primary_key=True, serialize=False)),
                ('tecla', models.CharField(help_text='Tecla de atalho (ex: F1, F2)', max_length=5)),
                ('caminho', models.CharField(help_text='Rota do sistema (ex: /vendas)', max_length=255)),
                ('descricao', models.CharField(blank=True, help_text='Descrição exibida ao usuário', max_length=100, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, related_name='atalhos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Atalho de Usuário',
                'verbose_name_plural': 'Atalhos de Usuários',
                'db_table': 'user_atalhos',
                'managed': True,
                'unique_together': {('user', 'tecla')},
            },
        ),
    ]
