# Generated by Django 6.0.2 on 2026-03-02 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0102_useratalho'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('id_veterinario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('crmv', models.CharField(help_text='Registro no Conselho Regional de Medicina Veterinária', max_length=20, unique=True)),
                ('especialidade', models.CharField(blank=True, max_length=100, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'veterinarios',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='pet',
            name='especie',
            field=models.CharField(choices=[('Cão', 'Cão'), ('Gato', 'Gato'), ('Ave', 'Ave'), ('Roedor', 'Roedor'), ('Réptil', 'Réptil'), ('Outro', 'Outro')], default='Cão', max_length=20),
        ),
        migrations.AddField(
            model_name='pet',
            name='microchip',
            field=models.CharField(blank=True, help_text='Número do microchip', max_length=50, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='ConsultaVeterinaria',
            fields=[
                ('id_consulta', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_consulta', models.CharField(choices=[('Rotina', 'Consulta de Rotina'), ('Retorno', 'Retorno'), ('Emergência', 'Emergência'), ('Cirurgia', 'Consulta Pré-Cirurgia'), ('Vacina', 'Aplicação de Vacinas')], default='Rotina', max_length=20)),
                ('data_consulta', models.DateTimeField()),
                ('queixa_principal', models.TextField(blank=True, help_text='Motivo da consulta', null=True)),
                ('historico_clinico', models.TextField(blank=True, null=True)),
                ('peso_consulta', models.DecimalField(blank=True, decimal_places=2, help_text='Peso em kg', max_digits=5, null=True)),
                ('temperatura', models.DecimalField(blank=True, decimal_places=1, help_text='Temperatura em °C', max_digits=4, null=True)),
                ('frequencia_cardiaca', models.IntegerField(blank=True, help_text='Batimentos por minuto', null=True)),
                ('frequencia_respiratoria', models.IntegerField(blank=True, help_text='Respirações por minuto', null=True)),
                ('diagnostico', models.TextField(blank=True, null=True)),
                ('tratamento', models.TextField(blank=True, null=True)),
                ('receituario', models.TextField(blank=True, help_text='Prescrição médica', null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('retorno_previsto', models.DateField(blank=True, null=True)),
                ('valor_consulta', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('Agendada', 'Agendada'), ('Em Atendimento', 'Em Atendimento'), ('Concluída', 'Concluída'), ('Cancelada', 'Cancelada')], default='Agendada', max_length=20)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_modificacao', models.DateTimeField(auto_now=True)),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, related_name='consultas_vet', to='api.cliente')),
                ('id_pet', models.ForeignKey(db_column='id_pet', on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='api.pet')),
                ('id_veterinario', models.ForeignKey(blank=True, db_column='id_veterinario', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.veterinario')),
            ],
            options={
                'db_table': 'consultas_veterinarias',
                'ordering': ['-data_consulta'],
            },
        ),
        migrations.CreateModel(
            name='VacinaAplicada',
            fields=[
                ('id_vacina', models.AutoField(primary_key=True, serialize=False)),
                ('nome_vacina', models.CharField(help_text='Ex: V10, Antirrábica, Giardia', max_length=200)),
                ('fabricante', models.CharField(blank=True, max_length=100, null=True)),
                ('lote', models.CharField(blank=True, max_length=50, null=True)),
                ('data_aplicacao', models.DateField()),
                ('proxima_dose', models.DateField(blank=True, help_text='Data prevista para reforço', null=True)),
                ('via_aplicacao', models.CharField(choices=[('Subcutânea', 'Subcutânea'), ('Intramuscular', 'Intramuscular'), ('Intranasal', 'Intranasal'), ('Oral', 'Oral')], default='Subcutânea', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('id_pet', models.ForeignKey(db_column='id_pet', on_delete=django.db.models.deletion.CASCADE, related_name='vacinas', to='api.pet')),
                ('id_veterinario', models.ForeignKey(blank=True, db_column='id_veterinario', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.veterinario')),
            ],
            options={
                'db_table': 'vacinas_aplicadas',
                'ordering': ['-data_aplicacao'],
                'indexes': [models.Index(fields=['id_pet', 'proxima_dose'], name='vacinas_apl_id_pet_683b91_idx')],
            },
        ),
        migrations.CreateModel(
            name='Internacao',
            fields=[
                ('id_internacao', models.AutoField(primary_key=True, serialize=False)),
                ('motivo', models.CharField(choices=[('Tratamento Clínico', 'Tratamento Clínico'), ('Pós-Cirúrgico', 'Recuperação Pós-Cirúrgica'), ('Observação', 'Observação'), ('Emergência', 'Emergência'), ('Medicação Contínua', 'Medicação Contínua')], default='Tratamento Clínico', max_length=30)),
                ('descricao_motivo', models.TextField(blank=True, null=True)),
                ('data_entrada', models.DateTimeField()),
                ('data_alta', models.DateTimeField(blank=True, null=True)),
                ('numero_baia', models.CharField(blank=True, help_text='Número da baia onde está internado', max_length=20, null=True)),
                ('dieta', models.TextField(blank=True, help_text='Dieta prescrita', null=True)),
                ('medicamentos', models.TextField(blank=True, help_text='Medicamentos administrados', null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('valor_diaria', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0.0, help_text='Valor total da internação', max_digits=10)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_modificacao', models.DateTimeField(auto_now=True)),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, related_name='internacoes_vet', to='api.cliente')),
                ('id_pet', models.ForeignKey(db_column='id_pet', on_delete=django.db.models.deletion.CASCADE, related_name='internacoes', to='api.pet')),
                ('id_veterinario', models.ForeignKey(blank=True, db_column='id_veterinario', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.veterinario')),
            ],
            options={
                'db_table': 'internacoes',
                'ordering': ['-data_entrada'],
                'indexes': [models.Index(fields=['id_pet', 'data_alta'], name='internacoes_id_pet_fb8148_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExameLaboratorial',
            fields=[
                ('id_exame', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_exame', models.CharField(choices=[('Hemograma', 'Hemograma Completo'), ('Bioquímico', 'Exame Bioquímico'), ('Urina', 'Exame de Urina'), ('Fezes', 'Exame de Fezes (Parasitológico)'), ('Raio-X', 'Raio-X'), ('Ultrassom', 'Ultrassonografia'), ('Citologia', 'Exame Citológico'), ('Histopatológico', 'Exame Histopatológico'), ('PCR', 'PCR (Diagnóstico Molecular)'), ('Sorológico', 'Exame Sorológico'), ('Outro', 'Outro')], default='Hemograma', max_length=30)),
                ('descricao', models.TextField(blank=True, help_text='Descrição detalhada do exame', null=True)),
                ('data_solicitacao', models.DateField()),
                ('data_resultado', models.DateField(blank=True, null=True)),
                ('laboratorio', models.CharField(blank=True, max_length=200, null=True)),
                ('resultado', models.TextField(blank=True, help_text='Resultado do exame', null=True)),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('Solicitado', 'Solicitado'), ('Coletado', 'Material Coletado'), ('Aguardando', 'Aguardando Resultado'), ('Concluído', 'Concluído'), ('Cancelado', 'Cancelado')], default='Solicitado', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('id_consulta', models.ForeignKey(blank=True, db_column='id_consulta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exames', to='api.consultaveterinaria')),
                ('id_pet', models.ForeignKey(db_column='id_pet', on_delete=django.db.models.deletion.CASCADE, related_name='exames', to='api.pet')),
                ('id_veterinario', models.ForeignKey(blank=True, db_column='id_veterinario', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.veterinario')),
            ],
            options={
                'db_table': 'exames_laboratoriais',
                'ordering': ['-data_solicitacao'],
                'indexes': [models.Index(fields=['id_pet', 'status'], name='exames_labo_id_pet_8bcd51_idx'), models.Index(fields=['id_consulta'], name='exames_labo_id_cons_6adbb0_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='consultaveterinaria',
            index=models.Index(fields=['id_pet', 'data_consulta'], name='consultas_v_id_pet_90b843_idx'),
        ),
        migrations.AddIndex(
            model_name='consultaveterinaria',
            index=models.Index(fields=['id_veterinario', 'status'], name='consultas_v_id_vete_36d28f_idx'),
        ),
    ]
