# Generated by Django 6.0.2 on 2026-03-03 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0103_veterinario_pet_especie_pet_microchip_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoBalanca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_configuracao', models.CharField(max_length=100, verbose_name='Nome da Configuração')),
                ('tipo_balanca', models.CharField(choices=[('checkout', 'Balança de Check-out (Fora do Caixa)'), ('integrada', 'Balança Integrada ao Caixa')], default='checkout', max_length=20)),
                ('modelo_balanca', models.CharField(choices=[('toledo', 'Toledo'), ('filizola', 'Filizola'), ('urano', 'Urano'), ('elgin', 'Elgin'), ('balmak', 'Balmak'), ('generica', 'Genérica')], default='toledo', max_length=50)),
                ('porta_serial', models.CharField(blank=True, help_text='Ex: COM1, COM3', max_length=20, null=True, verbose_name='Porta Serial')),
                ('baud_rate', models.IntegerField(default=9600, verbose_name='Baud Rate')),
                ('ip_balanca', models.CharField(blank=True, help_text='Para balanças com conexão de rede', max_length=50, null=True, verbose_name='IP da Balança')),
                ('porta_rede', models.IntegerField(blank=True, default=9100, null=True, verbose_name='Porta de Rede')),
                ('formato_exportacao', models.CharField(choices=[('toledo_mgv6', 'Toledo MGV6'), ('filizola_smart', 'Filizola Smart'), ('urano_pop', 'Urano POP'), ('texto_padrao', 'Texto Padrão'), ('csv', 'CSV')], default='texto_padrao', max_length=50)),
                ('codigo_inicial_plu', models.IntegerField(default=1, help_text='Código inicial para numeração dos produtos', verbose_name='Código Inicial PLU')),
                ('usar_codigo_barras', models.BooleanField(default=True, verbose_name='Usar Código de Barras do Produto')),
                ('prefixo_codigo', models.CharField(blank=True, help_text='Prefixo para códigos gerados', max_length=10, null=True, verbose_name='Prefixo do Código')),
                ('tamanho_nome_produto', models.IntegerField(default=50, verbose_name='Tamanho Máximo do Nome')),
                ('incluir_validade', models.BooleanField(default=True, verbose_name='Incluir Validade')),
                ('dias_validade_padrao', models.IntegerField(default=3, verbose_name='Dias de Validade Padrão')),
                ('apenas_produtos_peso', models.BooleanField(default=True, verbose_name='Apenas Produtos Vendidos por Peso')),
                ('grupos_permitidos', models.JSONField(blank=True, default=list, help_text='IDs dos grupos permitidos', verbose_name='Grupos de Produtos Permitidos')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario_criacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balancas_criadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuração de Balança',
                'verbose_name_plural': 'Configurações de Balança',
                'db_table': 'configuracao_balanca',
                'ordering': ['nome_configuracao'],
            },
        ),
        migrations.CreateModel(
            name='ExportacaoBalanca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo_gerado', models.CharField(max_length=255, verbose_name='Nome do Arquivo')),
                ('quantidade_produtos', models.IntegerField(default=0)),
                ('formato', models.CharField(max_length=50)),
                ('conteudo_arquivo', models.TextField(verbose_name='Conteúdo do Arquivo')),
                ('tamanho_bytes', models.IntegerField(default=0)),
                ('data_exportacao', models.DateTimeField(auto_now_add=True)),
                ('configuracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exportacoes', to='api.configuracaobalanca')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exportação de Balança',
                'verbose_name_plural': 'Exportações de Balança',
                'db_table': 'exportacao_balanca',
                'ordering': ['-data_exportacao'],
            },
        ),
        migrations.CreateModel(
            name='ProdutoBalanca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_plu', models.IntegerField(verbose_name='Código PLU')),
                ('tara', models.DecimalField(decimal_places=3, default=0, help_text='Peso da embalagem', max_digits=10, verbose_name='Tara (kg)')),
                ('validade_dias', models.IntegerField(default=3, verbose_name='Validade (dias)')),
                ('departamento', models.IntegerField(default=1, verbose_name='Departamento/Setor')),
                ('ativo', models.BooleanField(default=True)),
                ('exportado_em', models.DateTimeField(blank=True, null=True, verbose_name='Última Exportação')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('configuracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='api.configuracaobalanca')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.produto')),
            ],
            options={
                'verbose_name': 'Produto na Balança',
                'verbose_name_plural': 'Produtos na Balança',
                'db_table': 'produto_balanca',
                'ordering': ['codigo_plu'],
                'unique_together': {('configuracao', 'codigo_plu'), ('configuracao', 'produto')},
            },
        ),
    ]
