# Generated by Django 6.0.2 on 2026-03-03 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0104_configuracaobalanca_exportacaobalanca_produtobalanca'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='xml_conteudo',
            field=models.TextField(blank=True, db_column='xml_conteudo', null=True),
        ),
    ]
