# Generated by Django 6.0.2 on 2026-03-04 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0106_create_conta_servico'),
    ]

    operations = [
        migrations.AddField(
            model_name='formapagamento',
            name='dias_repasse',
            field=models.IntegerField(default=1, help_text='Dias para o repasse financeiro (D+X)'),
        ),
        migrations.AddField(
            model_name='formapagamento',
            name='taxa_operadora',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Taxa percentual da operadora (ex: 2.50)', max_digits=5),
        ),
        migrations.CreateModel(
            name='RecebimentoCartao',
            fields=[
                ('id_recebimento', models.AutoField(primary_key=True, serialize=False)),
                ('data_venda', models.DateField()),
                ('valor_bruto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('taxa_percentual', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('valor_taxa', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('valor_liquido', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_previsao', models.DateField(help_text='Data prevista para o crédito em conta')),
                ('data_pagamento', models.DateField(blank=True, help_text='Data real da liquidação/conciliação', null=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONCILIADO', 'Conciliado'), ('LIQUIDADO', 'Liquidado'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20)),
                ('bandeira', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_cartao', models.CharField(default='CREDITO', max_length=20)),
                ('nsu', models.CharField(blank=True, max_length=50, null=True)),
                ('codigo_autorizacao', models.CharField(blank=True, max_length=50, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('id_financeiro', models.ForeignKey(blank=True, db_column='id_financeiro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recebimentos_cartao', to='api.financeiroconta')),
                ('id_venda', models.ForeignKey(blank=True, db_column='id_venda', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recebimentos_cartao', to='api.venda')),
            ],
            options={
                'verbose_name': 'Recebimento de Cartão',
                'verbose_name_plural': 'Recebimentos de Cartões',
                'db_table': 'financeiro_cartoes',
                'ordering': ['data_previsao', 'status'],
                'managed': True,
            },
        ),
    ]
