# Generated by Django 6.0.2 on 2026-03-06 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0107_formapagamento_dias_repasse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='chave_nfe_referenciada',
            field=models.CharField(blank=True, db_column='chave_nfe_referenciada', help_text='Chave de Acesso da NFe que está sendo devolvida/referenciada', max_length=50, null=True),
        ),
    ]
