# Generated by Django 6.0.2 on 2026-03-07 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0109_sequencial_nfe_e_chave_devolucao'),
    ]

    operations = [
        migrations.AddField(
            model_name='regrafiscalreforma',
            name='aliquota_ibs_estadual',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='% IBS quota-parte estadual (tag pAliqIBS_E na NF-e 2026)', max_digits=5),
        ),
        migrations.AddField(
            model_name='regrafiscalreforma',
            name='aliquota_ibs_municipal',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='% IBS quota-parte municipal (tag pAliqIBS_M na NF-e 2026)', max_digits=5),
        ),
        migrations.AddField(
            model_name='regrafiscalreforma',
            name='credito_presumido_perc',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='% de crédito presumido no período de transição', max_digits=5),
        ),
        migrations.AddField(
            model_name='regrafiscalreforma',
            name='reducao_bc_perc',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='% de redução da base de cálculo IBS/CBS', max_digits=5),
        ),
        migrations.AddField(
            model_name='regrafiscalreforma',
            name='vigencia_fim',
            field=models.DateField(blank=True, help_text='Data de fim da validade (null = vigente indefinidamente)', null=True),
        ),
        migrations.AddField(
            model_name='regrafiscalreforma',
            name='vigencia_inicio',
            field=models.DateField(blank=True, help_text='Data de início da validade desta regra', null=True),
        ),
        migrations.AddField(
            model_name='splitpaymentconfig',
            name='cnpj_ente_destino',
            field=models.CharField(blank=True, help_text='CNPJ do ente tributário para roteamento TEF', max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='splitpaymentconfig',
            name='percentual_split',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='% do valor da venda desviado diretamente para este ente no ato do pagamento', max_digits=5),
        ),
        migrations.AddField(
            model_name='splitpaymentconfig',
            name='tipo_ente',
            field=models.CharField(choices=[('IBS_COMITE', 'IBS — Comitê Gestor do IBS'), ('CBS_RFB', 'CBS — Receita Federal do Brasil')], default='IBS_COMITE', help_text='Ente tributário destinatário do split (IBS→Comitê Gestor / CBS→RFB)', max_length=10),
        ),
        migrations.AddField(
            model_name='vendaitem',
            name='ibs_aliq_estadual',
            field=models.DecimalField(blank=True, db_column='ibs_aliq_estadual', decimal_places=4, help_text='Alíquota IBS quota-parte estadual (pAliqIBS_E na NF-e)', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='vendaitem',
            name='ibs_aliq_municipal',
            field=models.DecimalField(blank=True, db_column='ibs_aliq_municipal', decimal_places=4, help_text='Alíquota IBS quota-parte municipal (pAliqIBS_M na NF-e)', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='vendaitem',
            name='ibs_valor_estadual',
            field=models.DecimalField(blank=True, db_column='ibs_valor_estadual', decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='vendaitem',
            name='ibs_valor_municipal',
            field=models.DecimalField(blank=True, db_column='ibs_valor_municipal', decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='vendaitem',
            name='reducao_bc_cbs_perc',
            field=models.DecimalField(blank=True, db_column='reducao_bc_cbs_perc', decimal_places=2, help_text='% redução BC do CBS aplicada neste item', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='vendaitem',
            name='reducao_bc_ibs_perc',
            field=models.DecimalField(blank=True, db_column='reducao_bc_ibs_perc', decimal_places=2, help_text='% redução BC do IBS aplicada neste item', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='vendaitem',
            name='regra_reforma_aplicada',
            field=models.ForeignKey(blank=True, db_column='id_regra_reforma_aplicada', help_text='Qual regra IBS/CBS gerou estes valores — essencial para auditoria da Receita Federal', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.regrafiscalreforma'),
        ),
        migrations.AlterField(
            model_name='regrafiscalreforma',
            name='aliquota_ibs',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='% IBS total (Estadual + Municipal) — campo legado; use os campos _estadual/_municipal para a NF-e', max_digits=5),
        ),
    ]
