# Generated by Django 6.0.2 on 2026-03-07 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0110_reforma_tributaria_split_payment_completo'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacao',
            name='limite_desconto_percentual',
            field=models.DecimalField(blank=True, db_column='limite_desconto_percentual', decimal_places=2, default=0.0, help_text='Percentual máximo de desconto permitido sem aprovação do supervisor (0 = sem limite / aprovação desabilitada)', max_digits=5, null=True),
        ),
    ]
