# Generated by Django 6.0.2 on 2026-03-10 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0112_add_whatsapp_supervisor_user_parametros'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delay_entre_mensagens', models.IntegerField(default=15, help_text='Delay em segundos entre cada mensagem enviada (anti-ban)')),
                ('limite_envios_por_vez', models.IntegerField(default=50, help_text='Máximo de mensagens para processar em cada execução')),
                ('telefone_conectado', models.CharField(blank=True, help_text='Número do WhatsApp conectado atualmente', max_length=20, null=True)),
                ('status_conexao', models.CharField(choices=[('CONECTADO', 'Conectado'), ('DESCONECTADO', 'Desconectado'), ('ERRO', 'Erro')], default='DESCONECTADO', max_length=20)),
                ('qr_code', models.TextField(blank=True, help_text='QR Code em base64', null=True)),
                ('data_ultima_conexao', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Configuração WhatsApp',
                'verbose_name_plural': 'Configurações WhatsApp',
                'db_table': 'whatsapp_configuracao',
            },
        ),
        migrations.CreateModel(
            name='FilaWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(help_text='Número com DDI (ex: 5534999999999)', max_length=20)),
                ('nome_destinatario', models.CharField(blank=True, max_length=200, null=True)),
                ('mensagem', models.TextField(help_text='Texto da mensagem. Use [NOME] para personalização')),
                ('tipo_envio', models.CharField(choices=[('individual', 'Individual'), ('lote', 'Lote'), ('marketing', 'Marketing'), ('notificacao', 'Notificação')], default='individual', max_length=20)),
                ('prioridade', models.IntegerField(choices=[(1, 'Alta'), (2, 'Normal'), (3, 'Baixa')], default=2)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando'), ('enviado', 'Enviado'), ('falha', 'Falha'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('tentativas', models.IntegerField(default=0)),
                ('erro_mensagem', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_envio', models.DateTimeField(blank=True, null=True)),
                ('agendar_para', models.DateTimeField(blank=True, help_text='Se preenchido, mensagem só será enviada nesta data/hora', null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensagens_whatsapp', to='api.cliente')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensagens_criadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mensagem na Fila',
                'verbose_name_plural': 'Fila de Mensagens WhatsApp',
                'db_table': 'whatsapp_fila',
                'ordering': ['prioridade', 'data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='LogWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CONEXAO', 'Conexão'), ('ENVIO', 'Envio de Mensagem'), ('ERRO', 'Erro'), ('SISTEMA', 'Sistema')], max_length=20)),
                ('mensagem', models.TextField()),
                ('detalhes', models.JSONField(blank=True, null=True)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('fila_mensagem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='api.filawhatsapp')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log WhatsApp',
                'verbose_name_plural': 'Logs WhatsApp',
                'db_table': 'whatsapp_logs',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.AddIndex(
            model_name='filawhatsapp',
            index=models.Index(fields=['status', 'prioridade'], name='whatsapp_fi_status_0022e0_idx'),
        ),
        migrations.AddIndex(
            model_name='filawhatsapp',
            index=models.Index(fields=['data_criacao'], name='whatsapp_fi_data_cr_57412a_idx'),
        ),
    ]
