# Generated by Django 6.0.2 on 2026-03-12 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0114_modulos_mapa_carga_pcp_boletos'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleto',
            name='id_conta_bancaria',
            field=models.ForeignKey(blank=True, db_column='id_conta_bancaria', help_text='Conta bancária com configuração de API boleto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boletos', to='api.contabancaria'),
        ),
        migrations.AddField(
            model_name='contabancaria',
            name='boleto_ambiente',
            field=models.CharField(blank=True, choices=[('SANDBOX', 'Sandbox / Homologação'), ('PRODUCAO', 'Produção')], default='SANDBOX', help_text='Ambiente da API', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='contabancaria',
            name='boleto_ativo',
            field=models.BooleanField(default=False, help_text='Habilita emissão de boletos via API para esta conta'),
        ),
        migrations.AddField(
            model_name='contabancaria',
            name='boleto_banco',
            field=models.CharField(blank=True, choices=[('BB', 'Banco do Brasil'), ('ITAU', 'Itaú'), ('BRADESCO', 'Bradesco'), ('SANTANDER', 'Santander'), ('SICOOB', 'Sicoob'), ('SICREDI', 'Sicredi'), ('CAIXA', 'Caixa Econômica Federal')], help_text='Banco para integração de boletos', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contabancaria',
            name='boleto_carteira',
            field=models.CharField(blank=True, help_text='Carteira de cobrança', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='contabancaria',
            name='boleto_client_id',
            field=models.CharField(blank=True, help_text='client_id OAuth2 do banco', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contabancaria',
            name='boleto_client_secret',
            field=models.CharField(blank=True, help_text='client_secret OAuth2 do banco', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contabancaria',
            name='boleto_convenio',
            field=models.CharField(blank=True, help_text='Código de convênio/contrato', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contabancaria',
            name='boleto_nosso_numero_atual',
            field=models.IntegerField(default=1, help_text='Sequencial do próximo boleto'),
        ),
        migrations.AlterField(
            model_name='boleto',
            name='id_config',
            field=models.ForeignKey(blank=True, db_column='id_config', help_text='Configuração legada (substituído por id_conta_bancaria)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boletos', to='api.configuracaoboleto'),
        ),
    ]
