# Generated by Django 6.0.2 on 2026-03-12 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0115_boleto_config_conta_bancaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleto',
            name='data_pagamento',
            field=models.DateField(blank=True, help_text='Data em que o pagamento foi confirmado pelo banco', null=True),
        ),
        migrations.AddField(
            model_name='boleto',
            name='valor_pago',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor efetivamente pago (retornado pelo banco)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='contabancaria',
            name='boleto_baixa_automatica',
            field=models.BooleanField(default=False, help_text='Ao confirmar pagamento via API bancária, dá baixa automática na conta a receber vinculada'),
        ),
    ]
