# Generated by Django 6.0.2 on 2026-03-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0116_boleto_baixa_automatica_e_data_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleto',
            name='baixa_realizada_em',
            field=models.DateTimeField(blank=True, help_text='Data/hora em que a baixa automática foi executada', null=True),
        ),
        migrations.AddField(
            model_name='boleto',
            name='baixa_via_api',
            field=models.BooleanField(default=False, help_text='Indica que a baixa financeira foi realizada automaticamente via API bancária'),
        ),
    ]
