# Generated by Django 6.0.2 on 2026-03-12 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0119_restore_produto_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoproduto',
            name='material_construcao',
            field=models.BooleanField(default=False, help_text='Habilita campos específicos para materiais de construção (metragem, rendimento, peso, etc.)'),
        ),
    ]
