# Generated by Django 6.0.2 on 2026-03-16 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0122_adicionar_campos_tributacao_config_produto'),
        ('mdfe', '0004_mdfecarregamento_municipio_cep_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Remove tributacao_info do modelo Produto apenas se a coluna ainda existir no banco
        migrations.RunSQL(
            sql="""
                SET @col_exists = (
                    SELECT COUNT(*) FROM information_schema.COLUMNS
                    WHERE TABLE_SCHEMA = DATABASE()
                    AND TABLE_NAME = 'produto'
                    AND COLUMN_NAME = 'tributacao_info'
                );
                SET @q = IF(@col_exists > 0, 'ALTER TABLE produto DROP COLUMN tributacao_info', 'SELECT 1');
                PREPARE stmt FROM @q;
                EXECUTE stmt;
                DEALLOCATE PREPARE stmt;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddField(
            model_name='operacao',
            name='limite_desconto_percentual',
            field=models.DecimalField(blank=True, db_column='limite_desconto_percentual', decimal_places=2, default=0.0, help_text='Limite de desconto permitido em percentual (ex: 10.00 para 10%). Acima disso, requer aprovação de supervisor.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='tributacaoproduto',
            name='cofins_aliquota_sn',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='tributacaoproduto',
            name='csosn',
            field=models.CharField(blank=True, default='400', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tributacaoproduto',
            name='cst_cofins_sn',
            field=models.CharField(blank=True, default='07', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tributacaoproduto',
            name='cst_ipi_sn',
            field=models.CharField(blank=True, default='99', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tributacaoproduto',
            name='cst_pis_sn',
            field=models.CharField(blank=True, default='07', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tributacaoproduto',
            name='ipi_aliquota_sn',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='tributacaoproduto',
            name='pis_aliquota_sn',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.CreateModel(
            name='ConfiguracaoBancaria',
            fields=[
                ('id_config', models.AutoField(primary_key=True, serialize=False)),
                ('banco', models.CharField(choices=[('BB', 'Banco do Brasil'), ('ITAU', 'Itaú'), ('BRADESCO', 'Bradesco'), ('SICOOB', 'Sicoob'), ('SANTANDER', 'Santander'), ('CAIXA', 'Caixa Econômica'), ('OUTROS', 'Outros')], max_length=20)),
                ('nome_configuracao', models.CharField(help_text='Nome para identificação', max_length=100)),
                ('client_id', models.CharField(help_text='Client ID fornecido pelo banco', max_length=255)),
                ('client_secret', models.CharField(help_text='Client Secret fornecido pelo banco', max_length=255)),
                ('url_autenticacao', models.URLField(help_text='URL para obter o token OAuth2', max_length=500)),
                ('url_api_boletos', models.URLField(help_text='URL base da API de boletos', max_length=500)),
                ('codigo_banco', models.CharField(help_text='Código COMPE do banco (ex: 001, 237)', max_length=10)),
                ('agencia', models.CharField(max_length=10)),
                ('conta', models.CharField(max_length=20)),
                ('digito_conta', models.CharField(blank=True, max_length=2, null=True)),
                ('convenio', models.CharField(blank=True, help_text='Número do convênio/carteira', max_length=50, null=True)),
                ('dias_protesto', models.IntegerField(default=0, help_text='Dias para protesto automático (0 = sem protesto)')),
                ('dias_baixa', models.IntegerField(default=30, help_text='Dias para baixa automática após vencimento')),
                ('percentual_multa', models.DecimalField(decimal_places=2, default=2.0, help_text='Percentual de multa por atraso', max_digits=5)),
                ('percentual_juros_dia', models.DecimalField(decimal_places=4, default=0.0333, help_text='Percentual de juros ao dia (1% ao mês = 0.0333)', max_digits=5)),
                ('baixa_automatica_api', models.BooleanField(default=True, help_text='Consultar API e dar baixa automática quando pago')),
                ('gerar_boleto_automatico', models.BooleanField(default=True, help_text="Gerar boleto automaticamente para condição de pagamento 'Boleto'")),
                ('ativo', models.BooleanField(default=True)),
                ('ambiente', models.CharField(choices=[('PRODUCAO', 'Produção'), ('HOMOLOGACAO', 'Homologação')], default='PRODUCAO', max_length=20)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('access_token', models.TextField(blank=True, null=True)),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('token_expira_em', models.DateTimeField(blank=True, null=True)),
                ('id_conta_bancaria', models.ForeignKey(help_text='Conta bancária vinculada do sistema', on_delete=django.db.models.deletion.PROTECT, related_name='configuracoes_boleto', to='api.contabancaria')),
            ],
            options={
                'verbose_name': 'Configuração Bancária',
                'verbose_name_plural': 'Configurações Bancárias',
                'db_table': 'configuracoes_bancarias',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('id_boleto', models.AutoField(primary_key=True, serialize=False)),
                ('nosso_numero', models.CharField(help_text='Nosso número gerado pelo banco', max_length=50, unique=True)),
                ('numero_documento', models.CharField(help_text='Número do documento/título', max_length=50)),
                ('codigo_barras', models.CharField(blank=True, max_length=100, null=True)),
                ('linha_digitavel', models.CharField(blank=True, max_length=100, null=True)),
                ('pagador_nome', models.CharField(max_length=200)),
                ('pagador_cpf_cnpj', models.CharField(max_length=20)),
                ('pagador_endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('pagador_cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('pagador_uf', models.CharField(blank=True, max_length=2, null=True)),
                ('pagador_cep', models.CharField(blank=True, max_length=10, null=True)),
                ('pagador_codigo_ibge', models.CharField(blank=True, help_text='Código IBGE da cidade (importante!)', max_length=10, null=True)),
                ('valor_nominal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('valor_multa', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('valor_juros', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('valor_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('data_emissao', models.DateField()),
                ('data_vencimento', models.DateField()),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('data_registro_banco', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('REGISTRADO', 'Registrado'), ('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('CANCELADO', 'Cancelado'), ('VENCIDO', 'Vencido'), ('BAIXADO', 'Baixado')], default='PENDENTE', max_length=20)),
                ('url_boleto', models.URLField(blank=True, help_text='URL para download do PDF', max_length=500, null=True)),
                ('baixado_via_api', models.BooleanField(default=False, help_text='Foi baixado automaticamente via API')),
                ('data_baixa_api', models.DateTimeField(blank=True, help_text='Data/hora da baixa via API', null=True)),
                ('pix_qr_code', models.TextField(blank=True, help_text='Código QR Code PIX', null=True)),
                ('pix_emv', models.TextField(blank=True, help_text='String EMV do PIX', null=True)),
                ('pix_txid', models.CharField(blank=True, help_text='TXID da transação PIX', max_length=100, null=True)),
                ('mensagem_banco', models.TextField(blank=True, help_text='Mensagens/erros retornados pelo banco', null=True)),
                ('dados_retorno_json', models.JSONField(blank=True, help_text='JSON completo do retorno do banco', null=True)),
                ('id_conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boletos', to='api.financeiroconta')),
                ('usuario_baixa', models.ForeignKey(blank=True, help_text='Usuário que executou a baixa (ou sistema)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boletos_baixados', to=settings.AUTH_USER_MODEL)),
                ('id_config_bancaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boletos', to='api.configuracaobancaria')),
            ],
            options={
                'verbose_name': 'Boleto Bancário',
                'verbose_name_plural': 'Boletos Bancários',
                'db_table': 'boletos',
                'ordering': ['-data_emissao'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MapaCarga',
            fields=[
                ('id_mapa', models.AutoField(primary_key=True, serialize=False)),
                ('numero_mapa', models.CharField(help_text='Número sequencial do mapa', max_length=50, unique=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_saida', models.DateTimeField(blank=True, help_text='Data/hora prevista de saída', null=True)),
                ('data_retorno', models.DateTimeField(blank=True, help_text='Data/hora de retorno', null=True)),
                ('peso_total_kg', models.DecimalField(decimal_places=2, default=0, help_text='Peso total da carga em KG', max_digits=10)),
                ('valor_total_carga', models.DecimalField(decimal_places=2, default=0, help_text='Valor total das vendas', max_digits=15)),
                ('quantidade_entregas', models.IntegerField(default=0, help_text='Número de entregas no mapa')),
                ('distancia_total_km', models.DecimalField(decimal_places=2, default=0, help_text='Distância total estimada', max_digits=10)),
                ('status', models.CharField(choices=[('EM_MONTAGEM', 'Em Montagem'), ('EM_ROTA', 'Em Rota'), ('ENTREGUE', 'Entregue'), ('CANCELADO', 'Cancelado')], default='EM_MONTAGEM', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('id_mdfe', models.ForeignKey(blank=True, db_column='id_mdfe', help_text='MDF-e gerado a partir deste mapa', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mapas_carga', to='mdfe.manifestoeletronico')),
                ('id_motorista', models.ForeignKey(blank=True, db_column='id_motorista_id', help_text='Vendedor que atua como motorista', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mapas_motorista', to='api.vendedor')),
                ('id_veiculo', models.ForeignKey(blank=True, db_column='id_veiculo', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mapas_carga', to='api.veiculo')),
            ],
            options={
                'verbose_name': 'Mapa de Carga',
                'verbose_name_plural': 'Mapas de Carga',
                'db_table': 'mapa_carga',
                'ordering': ['-data_criacao'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MapaCargaItem',
            fields=[
                ('id_item_mapa', models.AutoField(primary_key=True, serialize=False)),
                ('ordem_entrega', models.IntegerField(help_text='Ordem de entrega (1ª, 2ª, 3ª...)')),
                ('distancia_km', models.DecimalField(blank=True, decimal_places=2, help_text='Distância até este ponto', max_digits=10, null=True)),
                ('data_entrega_prevista', models.DateTimeField(blank=True, null=True)),
                ('data_entrega_realizada', models.DateTimeField(blank=True, null=True)),
                ('status_entrega', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ENTREGUE', 'Entregue'), ('RECUSADA', 'Recusada'), ('REAGENDADA', 'Reagendada')], default='PENDENTE', max_length=20)),
                ('observacoes_entrega', models.TextField(blank=True, null=True)),
                ('id_mapa', models.ForeignKey(db_column='id_mapa', on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='api.mapacarga')),
                ('id_venda', models.ForeignKey(db_column='id_venda', on_delete=django.db.models.deletion.PROTECT, related_name='mapas_carga', to='api.venda')),
            ],
            options={
                'verbose_name': 'Item do Mapa de Carga',
                'verbose_name_plural': 'Itens do Mapa de Carga',
                'db_table': 'mapa_carga_itens',
                'ordering': ['id_mapa', 'ordem_entrega'],
                'managed': True,
                'unique_together': {('id_mapa', 'id_venda')},
            },
        ),
    ]
