# Generated by Django 6.0.2 on 2026-03-16 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0123_adicionar_campos_sn_tributacao_produto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='tributacao_info',
        ),
        migrations.AddField(
            model_name='venda',
            name='chave_nfe_referenciada',
            field=models.CharField(blank=True, db_column='chave_nfe_referenciada', help_text='Chave da NF-e referenciada (ex: devolução/complemento)', max_length=50, null=True),
        ),
    ]
