# Generated by Django 6.0.2 on 2026-03-16 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0124_add_chave_nfe_referenciada_to_venda'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendaitem',
            name='split_payment',
            field=models.BooleanField(db_column='split_payment', default=False),
        ),
    ]
