# Generated by Django 6.0.2 on 2026-03-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0126_add_fiscal_fields_to_venda_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Numeracao',
            fields=[
                ('id_numeracao', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=20)),
                ('numeracao', models.CharField(max_length=8)),
            ],
            options={
                'verbose_name': 'Numeração',
                'verbose_name_plural': 'Numerações',
                'db_table': 'numeracao',
                'managed': True,
            },
        ),
    ]
