# Generated by Django 6.0.2 on 2026-03-17 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0127_add_numeracao_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacao',
            name='id_numeracao',
            field=models.ForeignKey(blank=True, db_column='id_numeracao', help_text='Numeração padrão utilizada por esta operação', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operacoes', to='api.numeracao'),
        ),
    ]
