# Generated by Django 6.0.2 on 2026-03-17 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0128_add_numeracao_fk_to_operacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SplitPaymentConfig',
            fields=[
                ('id_config', models.AutoField(primary_key=True, serialize=False)),
                ('adquirente', models.CharField(choices=[('STONE', 'Stone Pagamentos'), ('CIELO', 'Cielo'), ('REDE', 'Rede'), ('PAGSEGURO', 'PagSeguro'), ('GETNET', 'Getnet'), ('MERCADOPAGO', 'Mercado Pago'), ('OUTRO', 'Outro')], help_text='Adquirente/gateway de pagamento', max_length=20)),
                ('api_url', models.URLField(help_text='URL base da API do adquirente', max_length=500)),
                ('api_key', models.CharField(help_text='Chave de API (criptografada)', max_length=255)),
                ('api_secret', models.CharField(blank=True, help_text='Secret da API (criptografado)', max_length=255, null=True)),
                ('split_automatico', models.BooleanField(default=True, help_text='Processar split automaticamente no pagamento?')),
                ('percentual_alerta', models.DecimalField(decimal_places=2, default=30.0, help_text='Acima deste percentual, exige aprovação do supervisor', max_digits=5)),
                ('conta_ibs_uf', models.CharField(blank=True, help_text='ID da conta/wallet para IBS Estadual', max_length=100, null=True)),
                ('conta_ibs_mun', models.CharField(blank=True, help_text='ID da conta/wallet para IBS Municipal', max_length=100, null=True)),
                ('conta_cbs', models.CharField(blank=True, help_text='ID da conta/wallet para CBS Federal', max_length=100, null=True)),
                ('ambiente', models.CharField(choices=[('SANDBOX', 'Sandbox/Homologação'), ('PRODUCAO', 'Produção')], default='SANDBOX', max_length=10)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.OneToOneField(help_text='Empresa vinculada à configuração', on_delete=django.db.models.deletion.CASCADE, related_name='split_payment_config', to='api.empresaconfig')),
            ],
            options={
                'verbose_name': 'Configuração Split Payment',
                'verbose_name_plural': 'Configurações Split Payment',
                'db_table': 'split_payment_config',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RegraFiscalReforma',
            fields=[
                ('id_regra', models.AutoField(primary_key=True, serialize=False)),
                ('ncm', models.CharField(help_text='NCM do produto (8 dígitos)', max_length=8)),
                ('aliquota_ibs_uf', models.DecimalField(decimal_places=2, default=0.0, help_text='Alíquota IBS Estadual (ex: 18.00)', max_digits=5)),
                ('aliquota_ibs_mun', models.DecimalField(decimal_places=2, default=0.0, help_text='Alíquota IBS Municipal (ex: 1.00)', max_digits=5)),
                ('aliquota_cbs', models.DecimalField(decimal_places=2, default=0.0, help_text='Alíquota CBS Federal (ex: 12.00)', max_digits=5)),
                ('is_split_active', models.BooleanField(default=True, help_text='Se True, o imposto será retido via Split Payment')),
                ('agente_retentor', models.CharField(choices=[('BANCO', 'Banco/Adquirente'), ('EMPRESA', 'Empresa via API'), ('SEFAZ', 'SEFAZ Direta')], default='BANCO', help_text='Quem fará a retenção do imposto', max_length=20)),
                ('aliquota_reduzida', models.BooleanField(default=False, help_text='Produto tem alíquota reduzida por lei?')),
                ('percentual_reducao', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentual de redução da base de cálculo (ex: 40.00)', max_digits=5)),
                ('descricao_beneficio', models.TextField(blank=True, help_text='Descrição do benefício fiscal (Lei nº, Convênio, etc.)', null=True)),
                ('vigencia_inicio', models.DateField(help_text='Data de início da vigência da alíquota')),
                ('vigencia_fim', models.DateField(blank=True, help_text='Data fim da vigência (null = vigente indefinidamente)', null=True)),
                ('uf_aplicacao', models.CharField(blank=True, help_text='UF específica (null = aplica para todas)', max_length=2, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('produto', models.ForeignKey(help_text='Produto vinculado à regra fiscal', on_delete=django.db.models.deletion.CASCADE, related_name='regras_reforma', to='api.produto')),
                ('usuario_cadastro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regras_reforma_criadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Regra Fiscal Reforma 2026',
                'verbose_name_plural': 'Regras Fiscais Reforma 2026',
                'db_table': 'regras_fiscais_reforma_2026',
                'ordering': ['-vigencia_inicio', 'ncm'],
                'managed': True,
                'indexes': [models.Index(fields=['ncm', 'vigencia_inicio'], name='regras_fisc_ncm_d7881e_idx'), models.Index(fields=['produto', 'uf_aplicacao'], name='regras_fisc_produto_0623bd_idx')],
            },
        ),
        migrations.CreateModel(
            name='VendaSplitPayment',
            fields=[
                ('id_split', models.AutoField(primary_key=True, serialize=False)),
                ('valor_liquido_empresa', models.DecimalField(decimal_places=2, help_text='Valor que efetivamente entra na conta da empresa', max_digits=15)),
                ('valor_ibs_uf', models.DecimalField(decimal_places=2, default=0.0, help_text='Valor retido para IBS Estadual', max_digits=15)),
                ('valor_ibs_mun', models.DecimalField(decimal_places=2, default=0.0, help_text='Valor retido para IBS Municipal', max_digits=15)),
                ('valor_cbs', models.DecimalField(decimal_places=2, default=0.0, help_text='Valor retido para CBS Federal', max_digits=15)),
                ('valor_total_retido', models.DecimalField(decimal_places=2, help_text='Soma de todos os impostos retidos', max_digits=15)),
                ('percentual_retencao', models.DecimalField(decimal_places=2, help_text='Percentual de retenção sobre o valor total', max_digits=5)),
                ('split_realizado', models.BooleanField(default=False, help_text='Split foi processado com sucesso?')),
                ('split_data_hora', models.DateTimeField(blank=True, help_text='Data/hora que o split foi processado', null=True)),
                ('split_transaction_id', models.CharField(blank=True, help_text='ID da transação retornado pelo adquirente', max_length=255, null=True)),
                ('split_response', models.JSONField(blank=True, help_text='Response completo da API do adquirente (para debug)', null=True)),
                ('requer_aprovacao_supervisor', models.BooleanField(default=False, help_text='Retenção excede limite e precisa de aprovação?')),
                ('motivo_excecao', models.TextField(blank=True, help_text='Motivo da retenção excepcional (NCM majorado, etc.)', null=True)),
                ('detalhamento_itens', models.JSONField(blank=True, help_text='Array com split calculado por item da venda', null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aprovacao', models.ForeignKey(blank=True, help_text='Solicitação de aprovação via WhatsApp', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='splits_aprovados', to='api.solicitacaoaprovacao')),
                ('venda', models.OneToOneField(help_text='Venda vinculada ao split', on_delete=django.db.models.deletion.CASCADE, related_name='split_payment', to='api.venda')),
            ],
            options={
                'verbose_name': 'Split Payment de Venda',
                'verbose_name_plural': 'Splits Payment de Vendas',
                'db_table': 'vendas_split_payment',
                'ordering': ['-criado_em'],
                'managed': True,
                'indexes': [models.Index(fields=['venda', 'split_realizado'], name='vendas_spli_venda_i_4f0623_idx'), models.Index(fields=['split_data_hora'], name='vendas_spli_split_d_9ebcc4_idx')],
            },
        ),
    ]
