# Generated by Django 6.0.2 on 2026-03-17 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0130_sistema_email_multi_provedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacao',
            name='venda_veiculo_novo',
            field=models.BooleanField(db_column='venda_veiculo_novo', default=False, help_text='Se TRUE, esta operação é para venda de veículos novos e exige dados do veículo'),
        ),
        migrations.CreateModel(
            name='VeiculoNovo',
            fields=[
                ('id_veiculo_novo', models.AutoField(primary_key=True, serialize=False)),
                ('tp_op', models.CharField(help_text='Tipo Operação: 1=Venda concessionária, 2=Faturamento direto, 3=Venda direta, 0=Outros', max_length=1)),
                ('chassi', models.CharField(help_text='Chassi do veículo (17 caracteres)', max_length=17)),
                ('c_cor', models.CharField(help_text='Código da cor (Tabela DENATRAN)', max_length=4)),
                ('x_cor', models.CharField(help_text='Descrição da cor', max_length=40)),
                ('pot', models.CharField(help_text='Potência do motor (CV)', max_length=4)),
                ('cilin', models.CharField(help_text='Cilindrada (cc)', max_length=4)),
                ('peso_l', models.CharField(help_text='Peso líquido (kg)', max_length=9)),
                ('peso_b', models.CharField(help_text='Peso bruto (kg)', max_length=9)),
                ('n_serie', models.CharField(help_text='Número de série', max_length=9)),
                ('tp_comb', models.CharField(help_text='Tipo de combustível: 01=Álcool, 02=Gasolina, 03=Diesel...', max_length=2)),
                ('n_motor', models.CharField(help_text='Número do motor', max_length=21)),
                ('cmt', models.CharField(help_text='Capacidade Máxima de Tração (kg)', max_length=9)),
                ('dist', models.CharField(help_text='Distância entre eixos (mm)', max_length=4)),
                ('ano_mod', models.IntegerField(help_text='Ano modelo')),
                ('ano_fab', models.IntegerField(help_text='Ano de fabricação')),
                ('tp_pint', models.CharField(help_text='Tipo de pintura: S=Sólida, M=Metálica, P=Perolizada', max_length=1)),
                ('tp_veic', models.CharField(help_text='Tipo de veículo: 02=Ciclomotor, 03=Motoneta, 04=Motocicleta...', max_length=2)),
                ('esp_veic', models.CharField(help_text='Espécie: 1=Passageiro, 2=Carga, 3=Misto...', max_length=1)),
                ('vin', models.CharField(help_text='VIN (chassi remarcado): R=Remarcado, N=Normal', max_length=1)),
                ('cond_veic', models.CharField(help_text='Condição: 1=Acabado, 2=Inacabado, 3=Semi-acabado', max_length=1)),
                ('c_mod', models.CharField(help_text='Código Marca/Modelo (Tabela RENAVAM)', max_length=6)),
                ('c_cor_denatran', models.CharField(help_text='Código da cor DENATRAN', max_length=2)),
                ('lota', models.IntegerField(help_text='Lotação máxima')),
                ('tp_rest', models.CharField(help_text='Tipo de restrição: 0=Não há, 1=Alienação, 2=Arrendamento...', max_length=1)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('id_venda_item', models.OneToOneField(db_column='id_venda_item', help_text='Item da venda que contém este veículo', on_delete=django.db.models.deletion.CASCADE, related_name='veiculo_novo', to='api.vendaitem')),
            ],
            options={
                'verbose_name': 'Veículo Novo',
                'verbose_name_plural': 'Veículos Novos',
                'db_table': 'veiculos_novos',
                'managed': True,
            },
        ),
    ]
