# Generated by Django 6.0.2 on 2026-03-19 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0132_produto_campos_argamassa'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoComplementar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ordem', models.IntegerField(default=0, help_text='Ordem de exibição na sugestão')),
                ('produto', models.ForeignKey(db_column='id_produto', on_delete=django.db.models.deletion.CASCADE, related_name='complementares', to='api.produto')),
                ('produto_complementar', models.ForeignKey(db_column='id_produto_complementar', on_delete=django.db.models.deletion.CASCADE, related_name='complementar_de', to='api.produto')),
            ],
            options={
                'verbose_name': 'Produto Complementar',
                'verbose_name_plural': 'Produtos Complementares',
                'db_table': 'produtos_complementares',
                'ordering': ['ordem'],
                'managed': True,
                'unique_together': {('produto', 'produto_complementar')},
            },
        ),
    ]
