# Generated by Django 6.0.2 on 2026-03-19 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0133_produto_complementar_m2m'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.CharField(blank=True, help_text='Categoria do produto (ex: Construção, Ferramentas)', max_length=100, null=True),
        ),
    ]
