# Generated by Django 6.0.2 on 2026-03-20 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0136_operacao_tipo_faturamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('telefone', 'Conta de Telefone'), ('energia', 'Conta de Energia Elétrica'), ('agua', 'Conta de Água'), ('gas', 'Conta de Gás'), ('servico_terceiro', 'Nota de Serviço de Terceiro')], max_length=20)),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('fornecedor_nome', models.CharField(max_length=150)),
                ('cnpj_fornecedor', models.CharField(blank=True, max_length=18, null=True)),
                ('numero_documento', models.CharField(blank=True, max_length=50)),
                ('serie', models.CharField(blank=True, max_length=5)),
                ('chave_acesso', models.CharField(blank=True, max_length=44, null=True)),
                ('data_emissao', models.DateField()),
                ('data_vencimento', models.DateField(blank=True, null=True)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('mes_competencia', models.IntegerField()),
                ('ano_competencia', models.IntegerField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('valor_pis', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('aliq_pis', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('valor_cofins', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('aliq_cofins', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('valor_icms', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('aliq_icms', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('cfop', models.CharField(default='1949', max_length=5)),
                ('cst_pis', models.CharField(default='50', max_length=3)),
                ('cst_cofins', models.CharField(default='50', max_length=3)),
                ('cst_icms', models.CharField(blank=True, max_length=3)),
                ('observacao', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('cancelado', 'Cancelado'), ('vencido', 'Vencido')], default='pendente', max_length=15)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'contas_servicos',
                'ordering': ['-data_emissao'],
            },
        ),
        migrations.RenameIndex(
            model_name='notafiscalreferenciada',
            new_name='notas_fisca_id_vend_9a865c_idx',
            old_name='notas_fisca_id_vend_idx',
        ),
        migrations.RenameIndex(
            model_name='notafiscalreferenciada',
            new_name='notas_fisca_chave_a_51c576_idx',
            old_name='notas_fisca_chave_a_idx',
        ),
        migrations.AddField(
            model_name='venda',
            name='id_venda_faturamento',
            field=models.ForeignKey(blank=True, db_column='id_venda_faturamento', help_text='Venda NF-e/NFC-e gerada ao faturar esta venda', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas_faturadas', to='api.venda'),
        ),
    ]
