# Generated by Django 6.0.2 on 2026-03-20 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0137_contaservico_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpermissoes',
            options={'managed': True},
        ),
    ]
