# Generated by Django 6.0.2 on 2026-03-20 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0138_alter_userpermissoes_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissoes',
            name='faturamento_acessar',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='userpermissoes',
            name='faturamento_multi_cliente',
            field=models.IntegerField(blank=True, default=0, help_text='Permite faturar pedidos de clientes diferentes em uma única nota', null=True),
        ),
    ]
