# Generated by Django 6.0.2 on 2026-03-21 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0139_add_faturamento_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da integração (ex: Minha Loja ML)', max_length=100)),
                ('plataforma', models.CharField(choices=[('MERCADOLIVRE', 'Mercado Livre'), ('SHOPEE', 'Shopee'), ('AMAZON', 'Amazon'), ('MAGALU', 'Magalu'), ('WOOCOMMERCE', 'WooCommerce'), ('SHOPIFY', 'Shopify')], max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('client_id', models.CharField(blank=True, max_length=255, null=True)),
                ('client_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('access_token', models.TextField(blank=True, null=True)),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('expires_in', models.DateTimeField(blank=True, null=True)),
                ('config_json', models.TextField(default='{}', help_text='Configurações extras em JSON')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de Marketplace',
                'verbose_name_plural': 'Configurações de Marketplaces',
            },
        ),
        migrations.AlterModelOptions(
            name='userpermissoes',
            options={'managed': False},
        ),
        migrations.AddField(
            model_name='produto',
            name='disponivel_web',
            field=models.BooleanField(default=False, help_text='Produto disponível no e-commerce'),
        ),
        migrations.AddField(
            model_name='produto',
            name='preco_web',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Preço diferenciado para o site (se vazio, usa o preço normal)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL amigável para SEO', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='origem',
            field=models.CharField(choices=[('PDV', 'Ponto de Venda'), ('ECOM', 'E-commerce'), ('WHATSAPP', 'WhatsApp')], db_column='origem_venda', default='PDV', max_length=20),
        ),
        migrations.AddField(
            model_name='venda',
            name='payment_id',
            field=models.CharField(blank=True, help_text='ID do pagamento no Gateway (Pix/Stripe/MP)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='status_logistica',
            field=models.CharField(choices=[('PREPARANDO', 'Preparando'), ('AGUARDANDO_RETIRADA', 'Aguardando Retirada'), ('DESPACHADO', 'Despachado'), ('ENTREGUE', 'Entregue')], db_column='status_logistica', default='PREPARANDO', max_length=20),
        ),
        migrations.AddField(
            model_name='venda',
            name='status_pagamento',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('ESTORNADO', 'Estornado'), ('RECUSADO', 'Recusado')], db_column='status_pagamento', default='PENDENTE', max_length=20),
        ),
        migrations.CreateModel(
            name='MarketplaceProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_externo', models.CharField(max_length=100)),
                ('link_anuncio', models.CharField(blank=True, max_length=500, null=True)),
                ('preco_plataforma', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estoque_plataforma', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('status_sincronizacao', models.CharField(choices=[('PENDENTE', 'Pendente'), ('SINCRONIZADO', 'Sincronizado'), ('ERRO', 'Erro')], default='SINCRONIZADO', max_length=20)),
                ('ultimo_erro', models.TextField(blank=True, null=True)),
                ('ultima_sincronizacao', models.DateTimeField(auto_now=True)),
                ('marketplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos_vinculados', to='api.marketplaceconfig')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_marketplace', to='api.produto')),
            ],
            options={
                'verbose_name': 'Produto no Marketplace',
                'verbose_name_plural': 'Produtos nos Marketplaces',
                'unique_together': {('marketplace', 'produto')},
            },
        ),
    ]
