# Generated by Django 6.0.2 on 2026-03-23 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0140_marketplaceconfig_alter_userpermissoes_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoImpressao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(choices=[('venda', 'Venda'), ('venda_rapida', 'Venda Rápida (PDV)'), ('ordem_servico', 'Ordem de Serviço')], help_text='Módulo do sistema ao qual esta configuração se aplica', max_length=20, unique=True)),
                ('tipo_impressora', models.CharField(choices=[('termica', 'Térmica (Cupom)'), ('a4', 'A4 (Folha)')], default='termica', help_text='Tipo de impressora a utilizar', max_length=10)),
                ('largura_termica', models.CharField(choices=[('58mm', '58mm'), ('72mm', '72mm'), ('80mm', '80mm')], default='80mm', help_text='Largura do papel térmico (usado somente quando tipo=térmica)', max_length=5)),
                ('imprimir_automatico', models.BooleanField(default=False, help_text='Abre o diálogo de impressão automaticamente ao finalizar')),
                ('mostrar_logo', models.BooleanField(default=True, help_text='Exibe o logotipo da empresa no cabeçalho')),
                ('copias', models.PositiveSmallIntegerField(default=1, help_text='Número de vias a imprimir')),
                ('observacao_rodape', models.CharField(blank=True, default='', help_text='Texto livre exibido no rodapé da impressão', max_length=200)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de Impressão',
                'verbose_name_plural': 'Configurações de Impressão',
                'db_table': 'configuracoes_impressao',
            },
        ),
    ]
