# Generated by Django 6.0.2 on 2026-03-23 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0141_configuracao_impressao'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='controla_lote',
            field=models.BooleanField(default=False, help_text='Exige seleção de lote na venda quando True'),
        ),
        migrations.AddField(
            model_name='vendaitem',
            name='id_lote',
            field=models.ForeignKey(blank=True, db_column='id_lote', help_text='Lote utilizado nesta venda', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='venda_itens', to='api.loteproduto'),
        ),
    ]
