# Generated by Django 6.0.2 on 2026-03-24 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0142_controla_lote_produto_id_lote_vendaitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaMercadologica',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Nome da categoria', max_length=100)),
                ('nivel', models.IntegerField(choices=[(1, 'Departamento'), (2, 'Categoria'), (3, 'Subcategoria')], help_text='Nível hierárquico')),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.IntegerField(default=0, help_text='Ordem de exibição')),
                ('keywords', models.TextField(blank=True, help_text='Palavras-chave para classificação (separadas por vírgula)', null=True)),
                ('pai', models.ForeignKey(blank=True, help_text='Categoria pai (nível superior)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filhos', to='api.categoriamercadologica')),
            ],
            options={
                'verbose_name': 'Categoria Mercadológica',
                'verbose_name_plural': 'Categorias Mercadológicas',
                'db_table': 'categorias_mercadologicas',
                'ordering': ['nivel', 'ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ClassificacaoIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confianca', models.DecimalField(decimal_places=2, help_text='Nível de confiança (0.0 a 1.0)', max_digits=3)),
                ('aceita', models.BooleanField(blank=True, help_text='Se o usuário aceitou ou rejeitou a sugestão', null=True)),
                ('data_classificacao', models.DateTimeField(auto_now_add=True)),
                ('texto_analisado', models.TextField(help_text='Nome + Descrição usado na análise')),
                ('modelo_ia', models.CharField(default='gemini-2.5-flash', max_length=50)),
                ('categoria_escolhida_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escolhas_manuais', to='api.categoriamercadologica')),
                ('categoria_sugerida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sugestoes_ia', to='api.categoriamercadologica')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classificacoes_ia', to='api.produto')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Classificação IA',
                'verbose_name_plural': 'Classificações IA',
                'db_table': 'classificacoes_ia',
                'ordering': ['-data_classificacao'],
            },
        ),
        migrations.CreateModel(
            name='InformacaoProdutoAPI',
            fields=[
                ('produto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='info_api', serialize=False, to='api.produto')),
                ('fonte_api', models.CharField(choices=[('COSMOS', 'Cosmos API (Bluesoft)'), ('GS1', 'GS1 Brasil'), ('MERCADOLIVRE', 'Mercado Livre'), ('MANUAL', 'Cadastro Manual')], default='MANUAL', max_length=50)),
                ('dados_completos_json', models.JSONField(blank=True, help_text='JSON completo retornado pela API (backup)', null=True)),
                ('imagem_url_externa', models.URLField(blank=True, help_text='URL original da imagem fornecida pela API', max_length=500, null=True)),
                ('descricao_api', models.TextField(blank=True, help_text='Descrição original da API', null=True)),
                ('marca_api', models.CharField(blank=True, help_text='Marca retornada pela API', max_length=100, null=True)),
                ('categoria_sugerida', models.CharField(blank=True, help_text='Categoria sugerida pela API (GPC ou similar)', max_length=200, null=True)),
                ('data_sincronizacao', models.DateTimeField(auto_now=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('confianca_dados', models.DecimalField(decimal_places=2, default=1.0, help_text='Nível de confiança dos dados (0.0 a 1.0)', max_digits=3)),
                ('usuario_sincronizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Informação de Produto (API)',
                'verbose_name_plural': 'Informações de Produtos (API)',
                'db_table': 'informacoes_produto_api',
            },
        ),
        migrations.CreateModel(
            name='PrecoConcorrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ean', models.CharField(db_index=True, max_length=14)),
                ('nome_loja', models.CharField(blank=True, max_length=200, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('distancia_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_coleta', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('fonte', models.CharField(choices=[('INFOPRICE', 'InfoPrice'), ('NFE_PUBLICA', 'NFe Pública'), ('SCRAP', 'Web Scraping'), ('MANUAL', 'Entrada Manual')], max_length=50)),
                ('dados_origem_json', models.JSONField(blank=True, null=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precos_concorrencia', to='api.produto')),
            ],
            options={
                'verbose_name': 'Preço Concorrente',
                'verbose_name_plural': 'Preços da Concorrência',
                'db_table': 'precos_concorrencia',
                'ordering': ['-data_coleta'],
            },
        ),
        migrations.AddIndex(
            model_name='categoriamercadologica',
            index=models.Index(fields=['nivel', 'ativo'], name='categorias__nivel_58b301_idx'),
        ),
        migrations.AddIndex(
            model_name='categoriamercadologica',
            index=models.Index(fields=['pai', 'nivel'], name='categorias__pai_id_f8077b_idx'),
        ),
        migrations.AddIndex(
            model_name='precoconcorrente',
            index=models.Index(fields=['ean', 'data_coleta'], name='precos_conc_ean_750f35_idx'),
        ),
        migrations.AddIndex(
            model_name='precoconcorrente',
            index=models.Index(fields=['produto', 'data_coleta'], name='precos_conc_produto_092499_idx'),
        ),
    ]
