# Generated by Django 6.0.2 on 2026-03-25 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0143_categoriamercadologica_classificacaoia_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManifestacaoNFe',
            fields=[
                ('id_manifestacao', models.AutoField(primary_key=True, serialize=False)),
                ('chave_nfe', models.CharField(help_text='Chave de acesso da NFe (44 dígitos)', max_length=44)),
                ('numero_nfe', models.IntegerField(blank=True, null=True)),
                ('serie', models.IntegerField(blank=True, null=True)),
                ('emitente_nome', models.CharField(blank=True, max_length=255, null=True)),
                ('emitente_cnpj', models.CharField(blank=True, max_length=14, null=True)),
                ('valor_nfe', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('data_emissao', models.DateField(blank=True, null=True)),
                ('tipo_evento', models.CharField(choices=[('210200', 'Confirmação da Operação'), ('210210', 'Ciência da Operação'), ('210220', 'Operação não Realizada'), ('210240', 'Desconhecimento da Operação')], help_text='Código do tipo de evento (210200, 210210, 210220, 210240)', max_length=6)),
                ('n_seq_evento', models.IntegerField(default=1, help_text='Número sequencial do evento')),
                ('justificativa', models.TextField(blank=True, help_text='Justificativa (obrigatória para Operação não Realizada ou Desconhecimento)', null=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ENVIADO', 'Enviado'), ('REGISTRADO', 'Registrado'), ('REJEITADO', 'Rejeitado'), ('ERRO', 'Erro')], default='PENDENTE', max_length=20)),
                ('c_stat', models.CharField(blank=True, help_text='Código de status do retorno SEFAZ', max_length=3, null=True)),
                ('x_motivo', models.TextField(blank=True, help_text='Descrição do motivo retornado pela SEFAZ', null=True)),
                ('protocolo', models.CharField(blank=True, help_text='Número do protocolo de autorização', max_length=50, null=True)),
                ('dh_reg_evento', models.DateTimeField(blank=True, help_text='Data/hora de registro do evento na SEFAZ', null=True)),
                ('xml_evento', models.TextField(blank=True, help_text='XML completo do evento de manifestação', null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuário que criou a manifestação', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'manifestacao_nfe',
                'ordering': ['-criado_em'],
                'managed': True,
                'indexes': [models.Index(fields=['chave_nfe'], name='manifestaca_chave_n_542ad5_idx'), models.Index(fields=['status'], name='manifestaca_status_f83233_idx'), models.Index(fields=['tipo_evento'], name='manifestaca_tipo_ev_30694d_idx')],
            },
        ),
    ]
