# Generated by Django 6.0.2 on 2026-03-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0145_novos_modulos'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='matricula',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
