# Generated by Django 6.0.2 on 2026-03-26 20:28

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0151_cliente_ativo_inativacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecebimentoCartao',
            fields=[
                ('id_recebimento', models.AutoField(primary_key=True, serialize=False)),
                ('data_venda', models.DateField()),
                ('valor_bruto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('taxa_percentual', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('valor_taxa', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('valor_liquido', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_previsao', models.DateField(help_text='Data prevista para o crédito em conta')),
                ('data_pagamento', models.DateField(blank=True, help_text='Data real da liquidação/conciliação', null=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONCILIADO', 'Conciliado'), ('LIQUIDADO', 'Liquidado'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20)),
                ('bandeira', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_cartao', models.CharField(default='CREDITO', max_length=20)),
                ('nsu', models.CharField(blank=True, max_length=50, null=True)),
                ('codigo_autorizacao', models.CharField(blank=True, max_length=50, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Recebimento de Cartão',
                'verbose_name_plural': 'Recebimentos de Cartões',
                'db_table': 'financeiro_cartoes',
                'ordering': ['data_previsao', 'status'],
                'managed': True,
            },
        ),
        migrations.RemoveConstraint(
            model_name='composicaoproduto',
            name='pcp_composicao_unique',
        ),
        migrations.RemoveIndex(
            model_name='financeiroconta',
            name='fin_data_venc_idx',
        ),
        migrations.RemoveIndex(
            model_name='financeiroconta',
            name='fin_status_conta_idx',
        ),
        migrations.RemoveIndex(
            model_name='financeiroconta',
            name='fin_tipo_conta_idx',
        ),
        migrations.RemoveIndex(
            model_name='financeiroconta',
            name='fin_venc_status_tipo_idx',
        ),
        migrations.RemoveIndex(
            model_name='produto',
            name='produto_gtin_idx',
        ),
        migrations.RemoveIndex(
            model_name='produto',
            name='produto_nome_idx',
        ),
        migrations.RemoveIndex(
            model_name='produto',
            name='produto_web_idx',
        ),
        migrations.RemoveIndex(
            model_name='venda',
            name='venda_data_doc_idx',
        ),
        migrations.RemoveIndex(
            model_name='venda',
            name='venda_status_nfe_idx',
        ),
        migrations.RemoveIndex(
            model_name='venda',
            name='venda_data_status_idx',
        ),
        migrations.RenameIndex(
            model_name='ocorrenciafuncionario',
            new_name='rh_ocorrenc_funcion_9d9af3_idx',
            old_name='rh_ocorr_func_data_idx',
        ),
        migrations.AlterField(
            model_name='composicaoproduto',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Item ativo na ficha técnica.'),
        ),
        migrations.AlterField(
            model_name='contratorecorrencia',
            name='descricao',
            field=models.CharField(blank=True, default='', help_text='Descrição do serviço/produto', max_length=500),
        ),
        migrations.AlterField(
            model_name='ordemproducao',
            name='custo_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Custo total dos insumos consumidos (calculado ao finalizar).', max_digits=15),
        ),
        migrations.AlterField(
            model_name='ordemproducao',
            name='data_finalizacao',
            field=models.DateTimeField(blank=True, help_text='Momento em que a produção foi finalizada.', null=True),
        ),
        migrations.AlterField(
            model_name='ordemproducao',
            name='data_inicio_producao',
            field=models.DateTimeField(blank=True, help_text='Momento em que a produção foi iniciada.', null=True),
        ),
        migrations.AlterField(
            model_name='ordemproducao',
            name='quantidade_produzida',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Quantidade efetivamente produzida (preenchido ao finalizar).', max_digits=12),
        ),
        migrations.AlterUniqueTogether(
            name='composicaoproduto',
            unique_together={('produto_acabado', 'insumo')},
        ),
        migrations.AddField(
            model_name='recebimentocartao',
            name='id_financeiro',
            field=models.ForeignKey(blank=True, db_column='id_financeiro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recebimentos_cartao', to='api.financeiroconta'),
        ),
        migrations.AddField(
            model_name='recebimentocartao',
            name='id_venda',
            field=models.ForeignKey(blank=True, db_column='id_venda', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recebimentos_cartao', to='api.venda'),
        ),
    ]
