# Generated by Django 6.0.2 on 2026-03-31 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0157_os_foto_assinatura'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendaEntregaLog',
            fields=[
                ('id_entrega_log', models.AutoField(primary_key=True, serialize=False)),
                ('status_anterior', models.CharField(blank=True, choices=[('PREPARANDO', 'Preparando'), ('AGUARDANDO_RETIRADA', 'Aguardando Retirada'), ('DESPACHADO', 'Despachado'), ('ENTREGUE', 'Entregue')], max_length=30, null=True)),
                ('status_novo', models.CharField(choices=[('PREPARANDO', 'Preparando'), ('AGUARDANDO_RETIRADA', 'Aguardando Retirada'), ('DESPACHADO', 'Despachado'), ('ENTREGUE', 'Entregue')], max_length=30)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('data_log', models.DateTimeField(auto_now_add=True)),
                ('recebedor_nome', models.CharField(blank=True, help_text='Nome de quem recebeu a mercadoria', max_length=150, null=True)),
                ('recebedor_documento', models.CharField(blank=True, help_text='CPF/RG de quem recebeu', max_length=20, null=True)),
            ],
            options={
                'db_table': 'venda_entrega_logs',
                'ordering': ['data_log'],
            },
        ),
        migrations.AlterModelOptions(
            name='produtosimilar',
            options={'managed': True, 'ordering': ['ordem'], 'verbose_name': 'Produto Similar', 'verbose_name_plural': 'Produtos Similares'},
        ),
        migrations.RemoveIndex(
            model_name='tipotributacao',
            name='trib_tipo_empresa_nome_idx',
        ),
        migrations.RemoveIndex(
            model_name='tributacaouf',
            name='trib_uf_tipo_uf_idx',
        ),
        migrations.AddField(
            model_name='venda',
            name='data_prevista_entrega',
            field=models.DateField(blank=True, help_text='Data prevista para entrega', null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='endereco_entrega',
            field=models.TextField(blank=True, help_text='Endereço de entrega', null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='observacao_entrega',
            field=models.TextField(blank=True, help_text='Observações sobre a entrega', null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='responsavel_entrega',
            field=models.CharField(blank=True, help_text='Entregador / motorista responsável', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='regrafiscal',
            name='c_benef',
            field=models.CharField(blank=True, help_text='Código do Benefício Fiscal (cBenef)', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='regrafiscal',
            name='c_class_trib',
            field=models.CharField(blank=True, help_text='Classificação Tributária cClassTrib (IBS/CBS)', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='regrafiscal',
            name='cbs_aliq',
            field=models.DecimalField(decimal_places=4, default=0.0, help_text='Alíquota CBS (%)', max_digits=7),
        ),
        migrations.AlterField(
            model_name='regrafiscal',
            name='cbs_cst',
            field=models.CharField(blank=True, help_text='CST CBS', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='regrafiscal',
            name='cest_codigo',
            field=models.CharField(blank=True, help_text='Código CEST (7 dígitos) — obrigatório para ICMS-ST', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='regrafiscal',
            name='cofins_aliq',
            field=models.DecimalField(decimal_places=4, default=0.0, help_text='Alíquota COFINS (%)', max_digits=7),
        ),
        migrations.AlterField(
            model_name='regrafiscal',
            name='cofins_cst',
            field=models.CharField(blank=True, help_text='CST COFINS', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='regrafiscal',
            name='descricao',
            field=models.CharField(blank=True, help_text='Descrição / observação da regra', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='regrafiscal',
            name='diferimento_icms_perc',
            field=models.DecimalField(decimal_places=4, default=0.0, help_text='Diferimento ICMS (%)', max_digits=7),
        ),
        migrations.AlterField(
            model_name='regrafiscal',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Empresa à qual a regra pertence. Vazio = regra global.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regras_fiscais', to='api.empresaconfig'),
        ),
        migrations.AlterField(
            model_name='regrafiscal',
            name='funrural_aliq',
            field=models.DecimalField(decimal_places=4, default=0.0, help_text='Alíquota FUNRURAL (%)', max_digits=7),
        ),
        migrations.AlterField(
            model_name='regrafiscal',
            name='ibs_aliq',
            field=models.DecimalField(decimal_places=4, default=0.0, help_text='Alíquota IBS total (%)', max_digits=7),
        ),
        migrations.AlterField(
            model_name='regrafiscal',
            name='ibs_cst',
            field=models.CharField(blank=True, help_text='CST IBS', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='regrafiscal',
            name='icms_aliq',
            field=models.DecimalField(decimal_places=4, default=0.0, help_text='Alíquota ICMS (%)', max_digits=7),
        ),
        migrations.AlterField(
            model_name='regrafiscal',
            name='icms_cst_csosn',
            field=models.CharField(blank=True, help_text='CST (regime normal) ou CSOSN (Simples Nacional)', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='regrafiscal',
            name='icms_modalidade_bc',
            field=models.CharField(blank=True, help_text='Modalidade BC ICMS: 0=Margem Valor Agregado, 1=Pauta, 2=Preço Tabelado, 3=Valor Operação', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='regrafiscal',
            name='icms_reducao_bc_perc',
            field=models.DecimalField(decimal_places=4, default=0.0, help_text='Redução da BC ICMS (%)', max_digits=7),
        ),
        migrations.AlterField(
            model_name='regrafiscal',
            name='icmsst_aliq',
            field=models.DecimalField(decimal_places=4, default=0.0, help_text='Alíquota ICMS-ST (%)', max_digits=7),
        ),
        migrations.AlterField(
            model_name='regrafiscal',
            name='icmsst_reducao_bc_perc',
            field=models.DecimalField(decimal_places=4, default=0.0, help_text='Redução da BC ST (%)', max_digits=7),
        ),
        migrations.AlterField(
            model_name='regrafiscal',
            name='ipi_aliq',
            field=models.DecimalField(decimal_places=4, default=0.0, help_text='Alíquota IPI (%)', max_digits=7),
        ),
        migrations.AlterField(
            model_name='regrafiscal',
            name='ipi_classe_enquadramento',
            field=models.CharField(blank=True, help_text='Classe de Enquadramento IPI', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='regrafiscal',
            name='ipi_cst',
            field=models.CharField(blank=True, help_text='CST IPI', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='regrafiscal',
            name='pis_aliq',
            field=models.DecimalField(decimal_places=4, default=0.0, help_text='Alíquota PIS (%)', max_digits=7),
        ),
        migrations.AlterField(
            model_name='regrafiscal',
            name='pis_cst',
            field=models.CharField(blank=True, help_text='CST PIS', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='regrafiscal',
            name='regime_tributario',
            field=models.CharField(choices=[('SIMPLES', 'Simples Nacional'), ('MEI', 'MEI'), ('LUCRO_PRESUMIDO', 'Lucro Presumido'), ('LUCRO_REAL', 'Lucro Real'), ('TODOS', 'Todos os regimes')], default='TODOS', help_text='Regime tributário ao qual a regra se aplica', max_length=20),
        ),
        migrations.AlterField(
            model_name='regrafiscal',
            name='senar_aliq',
            field=models.DecimalField(decimal_places=4, default=0.0, help_text='Alíquota SENAR (%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='regrafiscal',
            name='split_payment',
            field=models.BooleanField(default=False, help_text='Aplica Split Payment desta regra?'),
        ),
        migrations.AlterField(
            model_name='regrafiscal',
            name='tipo_cliente',
            field=models.CharField(choices=[('TODOS', 'Todos os clientes'), ('CONSUMIDOR_FINAL', 'Consumidor Final (não contribuinte)'), ('REVENDEDOR', 'Revendedor / Contribuinte ICMS')], default='TODOS', help_text='Tipo de cliente ao qual a regra se aplica', max_length=20),
        ),
        migrations.AlterField(
            model_name='regrafiscal',
            name='tipo_produto_reform',
            field=models.CharField(choices=[('PADRAO', 'Padrão (alíquota cheia)'), ('REDUZIDA_50', 'Redução 50%'), ('REDUZIDA_60', 'Redução 60%'), ('ISENTO', 'Isento'), ('MONOFASICO', 'Monofásico')], default='PADRAO', help_text='Classificação na Reforma Tributária', max_length=12),
        ),
        migrations.AlterField(
            model_name='regrafiscal',
            name='uf_destino',
            field=models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], help_text='UF de destino (vazio = todas)', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='regrafiscal',
            name='uf_origem',
            field=models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], help_text='UF de origem/emitente (vazio = qualquer)', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='tipotributacao',
            name='antecipacao_tributaria',
            field=models.DecimalField(decimal_places=4, default=0.0, help_text='Percentual de antecipação tributária (%)', max_digits=7),
        ),
        migrations.AlterField(
            model_name='tipotributacao',
            name='cfop_devolucao',
            field=models.CharField(blank=True, help_text='CFOP utilizado em devoluções (ex: 1411)', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='tipotributacao',
            name='cfop_padrao',
            field=models.CharField(blank=True, help_text='CFOP padrão (pode ser sobreposto por linha de UF)', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='tipotributacao',
            name='considera_sintegra',
            field=models.BooleanField(default=False, help_text='Considera apuração do ICMS no SINTEGRA'),
        ),
        migrations.AlterField(
            model_name='tipotributacao',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Empresa vinculada (vazio = perfil global)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipos_tributacao', to='api.empresaconfig'),
        ),
        migrations.AlterField(
            model_name='tipotributacao',
            name='icms_modalidade_bc',
            field=models.CharField(choices=[('0', '0 - Margem Valor Agregado (%)'), ('1', '1 - Pauta (valor)'), ('2', '2 - Preço Tabelado Máx. Sugerido'), ('3', '3 - Valor da Operação')], default='3', help_text='Modalidade de determinação da BC do ICMS', max_length=1),
        ),
        migrations.AlterField(
            model_name='tipotributacao',
            name='icmsst_modalidade_bc',
            field=models.CharField(blank=True, choices=[('0', '0 - Preço Tabelado ou Máximo Sugerido'), ('1', '1 - Lista Negativa (valor)'), ('2', '2 - Lista Positiva (valor)'), ('3', '3 - Lista Neutra (valor)'), ('4', '4 - Margem Valor Agregado (%)'), ('5', '5 - Pauta (valor)'), ('6', '6 - Valor da Operação')], help_text='Modalidade de determinação da BC do ICMS ST', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='tipotributacao',
            name='nome',
            field=models.CharField(help_text='Nome do perfil (ex: CONSUMIDOR, REVENDEDOR, INDUSTRIAL)', max_length=100),
        ),
        migrations.AlterField(
            model_name='tipotributacao',
            name='observacao_nfe',
            field=models.TextField(blank=True, help_text='Observação a ser impressa na NF-e', null=True),
        ),
        migrations.AlterField(
            model_name='tributacaouf',
            name='cfop_saida',
            field=models.CharField(blank=True, help_text='CFOP de saída para esta UF (ex: 6102)', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='tributacaouf',
            name='fcp_aliq',
            field=models.DecimalField(decimal_places=4, default=0.0, help_text='Alíquota FCP (%)', max_digits=7),
        ),
        migrations.AlterField(
            model_name='tributacaouf',
            name='frete_perc',
            field=models.DecimalField(decimal_places=4, default=0.0, help_text='Percentual de frete incluído na BC ST (%)', max_digits=7),
        ),
        migrations.AlterField(
            model_name='tributacaouf',
            name='icms_aliq',
            field=models.DecimalField(decimal_places=4, default=0.0, help_text='Alíquota ICMS (%)', max_digits=7),
        ),
        migrations.AlterField(
            model_name='tributacaouf',
            name='icmsst_aliq',
            field=models.DecimalField(decimal_places=4, default=0.0, help_text='Alíquota ICMS ST (%)', max_digits=7),
        ),
        migrations.AlterField(
            model_name='tributacaouf',
            name='icmsst_mva_perc',
            field=models.DecimalField(decimal_places=4, default=0.0, help_text='MVA / IVA original (%)', max_digits=7),
        ),
        migrations.AlterField(
            model_name='tributacaouf',
            name='outras_despesas_perc',
            field=models.DecimalField(decimal_places=4, default=0.0, help_text='Outras despesas incluídas na BC ST (%)', max_digits=7),
        ),
        migrations.AlterField(
            model_name='tributacaouf',
            name='reducao_bc_perc',
            field=models.DecimalField(decimal_places=4, default=0.0, help_text='Redução da BC do ICMS (%)', max_digits=7),
        ),
        migrations.AlterField(
            model_name='tributacaouf',
            name='reducao_bc_st_perc',
            field=models.DecimalField(decimal_places=4, default=0.0, help_text='Redução da BC do ICMS ST (%)', max_digits=7),
        ),
        migrations.AlterField(
            model_name='tributacaouf',
            name='seguro_perc',
            field=models.DecimalField(decimal_places=4, default=0.0, help_text='Percentual de seguro incluído na BC ST (%)', max_digits=7),
        ),
        migrations.AlterField(
            model_name='tributacaouf',
            name='uf_destino',
            field=models.CharField(choices=[('AC', 'AC - Acre'), ('AL', 'AL - Alagoas'), ('AM', 'AM - Amazonas'), ('AP', 'AP - Amapá'), ('BA', 'BA - Bahia'), ('CE', 'CE - Ceará'), ('DF', 'DF - Distrito Federal'), ('ES', 'ES - Espírito Santo'), ('EX', 'EX - Exterior'), ('GO', 'GO - Goiás'), ('MA', 'MA - Maranhão'), ('MG', 'MG - Minas Gerais'), ('MS', 'MS - Mato Grosso do Sul'), ('MT', 'MT - Mato Grosso'), ('PA', 'PA - Pará'), ('PB', 'PB - Paraíba'), ('PE', 'PE - Pernambuco'), ('PI', 'PI - Piauí'), ('PR', 'PR - Paraná'), ('RJ', 'RJ - Rio de Janeiro'), ('RN', 'RN - Rio G. Norte'), ('RO', 'RO - Rondônia'), ('RR', 'RR - Roraima'), ('RS', 'RS - Rio G. do Sul'), ('SC', 'SC - Santa Catarina'), ('SE', 'SE - Sergipe'), ('SP', 'SP - São Paulo'), ('TO', 'TO - Tocantins')], help_text='UF de destino das mercadorias', max_length=2),
        ),
        migrations.AddField(
            model_name='vendaentregalog',
            name='id_venda',
            field=models.ForeignKey(db_column='id_venda', on_delete=django.db.models.deletion.CASCADE, related_name='logs_entrega', to='api.venda'),
        ),
        migrations.AddField(
            model_name='vendaentregalog',
            name='usuario',
            field=models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
