# Generated by Django 6.0.2 on 2026-04-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0158_venda_entrega_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeirobancario',
            name='conciliado',
            field=models.BooleanField(default=False, help_text='Indica se o lançamento foi conciliado manualmente'),
        ),
    ]
