# Generated by Django 6.0.2 on 2026-04-14 18:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0159_add_conciliado_to_financeiro_bancario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compra',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='compraitem',
            options={'managed': False},
        ),
        migrations.CreateModel(
            name='ConfiguracaoMercadoPago',
            fields=[
                ('id_config', models.AutoField(primary_key=True, serialize=False)),
                ('access_token', models.TextField(help_text='Access Token do Mercado Pago (APP_USR-...)')),
                ('mp_user_id', models.CharField(help_text='ID numérico do usuário/vendedor no MP', max_length=50)),
                ('device_id', models.CharField(help_text='Device ID do terminal Point Tap (ex: PAX_A910__123456)', max_length=100)),
                ('ambiente', models.CharField(choices=[('PRODUCAO', 'Produção'), ('HOMOLOGACAO', 'Homologação / Sandbox')], default='PRODUCAO', max_length=15)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuracoes_mp_point', to='api.empresaconfig')),
            ],
            options={
                'verbose_name': 'Configuração Mercado Pago',
                'verbose_name_plural': 'Configurações Mercado Pago',
                'db_table': 'mp_point_configuracao',
            },
        ),
        migrations.CreateModel(
            name='TransacaoMPPoint',
            fields=[
                ('id_transacao', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('payment_intent_id', models.CharField(blank=True, db_index=True, help_text='ID da intenção de pagamento no MP', max_length=100, null=True)),
                ('payment_id', models.CharField(blank=True, help_text='ID do pagamento aprovado no MP', max_length=100, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('CRIADA', 'Criada / Aguardando terminal'), ('PROCESSANDO', 'Processando pagamento'), ('APROVADA', 'Aprovada'), ('RECUSADA', 'Recusada/Negada'), ('CANCELADA', 'Cancelada pelo operador'), ('ERRO', 'Erro de comunicação')], default='CRIADA', max_length=15)),
                ('detalhe_status', models.CharField(blank=True, help_text='Mensagem de retorno do MP (ex: cc_rejected_insufficient_amount)', max_length=255, null=True)),
                ('tipo_pagamento', models.CharField(blank=True, help_text='credit_card, debit_card, etc.', max_length=30, null=True)),
                ('parcelas', models.IntegerField(default=1)),
                ('payload_webhook', models.JSONField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.configuracaomercadopago')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacoes_mp_criadas', to=settings.AUTH_USER_MODEL)),
                ('id_venda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacoes_mp_point', to='api.venda')),
            ],
            options={
                'verbose_name': 'Transação MP Point',
                'verbose_name_plural': 'Transações MP Point',
                'db_table': 'mp_point_transacoes',
                'ordering': ['-criado_em'],
            },
        ),
    ]
