# Generated by Django 6.0.2 on 2026-04-14 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0160_mp_point_integracao'),
    ]

    operations = [
        migrations.AddField(
            model_name='formapagamento',
            name='tipo_integracao',
            field=models.CharField(blank=True, choices=[('', 'Nenhuma'), ('MERCADOPAGO', 'Mercado Pago Point')], default='', help_text='Integração de pagamento externo vinculada a esta forma', max_length=20),
        ),
    ]
