# Generated by Django 6.0.2 on 2026-04-14 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0161_forma_pagamento_tipo_integracao'),
    ]

    operations = [
        migrations.AddField(
            model_name='formapagamento',
            name='dias_repasse',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='formapagamento',
            name='taxa_operadora',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
    ]
