# Generated by Django 6.0.2 on 2026-04-16 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0162_forma_pagamento_taxa_repasse'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='genero',
            field=models.CharField(blank=True, choices=[('feminino', 'Feminino'), ('masculino', 'Masculino'), ('unissex', 'Unissex')], help_text='Gênero do produto: feminino, masculino ou unissex', max_length=20, null=True),
        ),
    ]
