# Generated by Django 4.2 on 2026-01-09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0163_produto_genero'),
    ]

    operations = [
        migrations.CreateModel(
            name='FornecedorProdutoFracao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gtin', models.CharField(db_index=True, help_text='GTIN/EAN do produto no XML do fornecedor', max_length=14)),
                ('fracao', models.DecimalField(decimal_places=6, help_text='Fator de conversão (ex: 10.0 para caixa com 10 unidades)', max_digits=15)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('fornecedor', models.ForeignKey(db_column='id_fornecedor', help_text='Fornecedor que utiliza esta fração', on_delete=django.db.models.deletion.CASCADE, related_name='fracoes_produto', to='api.fornecedor')),
                ('produto', models.ForeignKey(db_column='id_produto', help_text='Produto ao qual a fração se aplica', on_delete=django.db.models.deletion.CASCADE, related_name='fracoes_fornecedor', to='api.produto')),
            ],
            options={
                'verbose_name': 'Fração de Produto por Fornecedor',
                'verbose_name_plural': 'Frações de Produtos por Fornecedor',
                'db_table': 'fornecedor_produto_fracao',
                'ordering': ['-data_atualizacao'],
                'managed': True,
            },
        ),
        migrations.AddConstraint(
            model_name='fornecedorprodutofracao',
            constraint=models.UniqueConstraint(fields=('fornecedor', 'produto', 'gtin'), name='unique_fornecedor_produto_gtin'),
        ),
    ]
