# Generated by Django 6.0.2 on 2026-04-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0164_fornecedor_produto_fracao'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='fornecedorprodutofracao',
            name='unique_fornecedor_produto_gtin',
        ),
        migrations.AlterField(
            model_name='produto',
            name='genero',
            field=models.CharField(blank=True, choices=[('FEMININO', 'Feminino'), ('MASCULINO', 'Masculino'), ('UNISSEX', 'Unissex')], help_text='Gênero do produto: feminino, masculino ou unissex', max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='fornecedorprodutofracao',
            unique_together={('fornecedor', 'produto', 'gtin')},
        ),
        # Adicionar campo fracao_aplicada na tabela compra_itens (managed=False, então fazemos SQL raw)
        migrations.RunSQL(
            sql="""
                ALTER TABLE compra_itens 
                ADD COLUMN fracao_aplicada DECIMAL(15,6) NULL 
                COMMENT 'Fração aplicada (ex: 12.0 para caixa com 12 unidades)'
            """,
            reverse_sql="ALTER TABLE compra_itens DROP COLUMN fracao_aplicada",
        ),
    ]
