# Generated by Django 6.0.2 on 2026-04-24 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0166_user_preferencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaoimpressao',
            name='tipo_impressora',
            field=models.CharField(choices=[('termica', 'Térmica (Cupom)'), ('a4', 'A4 (Folha)'), ('a4_fotos', 'A4 com Fotos e Assinatura')], default='termica', help_text='Tipo de impressora a utilizar', max_length=10),
        ),
        migrations.AlterField(
            model_name='userpreferencia',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
