# Generated by Django 6.0.2 on 2026-05-13 11:50

from django.db import migrations, connection

def add_cliente_fields(apps, schema_editor):
    with connection.cursor() as cursor:
        # Check existing columns
        cursor.execute("SHOW COLUMNS FROM clientes")
        columns = [row[0] for row in cursor.fetchall()]
        
        if 'tipo_desconto' not in columns:
            cursor.execute("ALTER TABLE clientes ADD COLUMN tipo_desconto VARCHAR(10) DEFAULT 'PERCENTUAL'")
        if 'valor_desconto' not in columns:
            cursor.execute("ALTER TABLE clientes ADD COLUMN valor_desconto DECIMAL(10, 2) DEFAULT 0.00")
        if 'percentual_arredondamento' not in columns:
            cursor.execute("ALTER TABLE clientes ADD COLUMN percentual_arredondamento DECIMAL(5, 2) DEFAULT 0.00")
        if 'priorizar_desconto_cliente' not in columns:
            cursor.execute("ALTER TABLE clientes ADD COLUMN priorizar_desconto_cliente TINYINT(1) DEFAULT 0")
            
        # Create M2M table
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS clientes_grupos_excecao (
                id INT AUTO_INCREMENT PRIMARY KEY,
                cliente_id INT NOT NULL,
                grupoproduto_id INT NOT NULL,
                FOREIGN KEY (cliente_id) REFERENCES clientes(id_cliente) ON DELETE CASCADE,
                FOREIGN KEY (grupoproduto_id) REFERENCES grupos_produto(id_grupo) ON DELETE CASCADE,
                UNIQUE KEY unique_cliente_grupo (cliente_id, grupoproduto_id)
            )
        """)

def remove_cliente_fields(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute("DROP TABLE IF EXISTS clientes_grupos_excecao")
        
        cursor.execute("SHOW COLUMNS FROM clientes")
        columns = [row[0] for row in cursor.fetchall()]
        
        if 'tipo_desconto' in columns:
            cursor.execute("ALTER TABLE clientes DROP COLUMN tipo_desconto")
        if 'valor_desconto' in columns:
            cursor.execute("ALTER TABLE clientes DROP COLUMN valor_desconto")
        if 'percentual_arredondamento' in columns:
            cursor.execute("ALTER TABLE clientes DROP COLUMN percentual_arredondamento")
        if 'priorizar_desconto_cliente' in columns:
            cursor.execute("ALTER TABLE clientes DROP COLUMN priorizar_desconto_cliente")

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0170_operacao_tipo_desconto'),
    ]

    operations = [
        migrations.RunPython(add_cliente_fields, remove_cliente_fields),
    ]
