# Generated by Django 6.0.2 on 2026-05-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0171_cliente_novos_campos_desconto'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userpreferencia',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userpreferencia',
            name='user',
        ),
        migrations.RemoveField(
            model_name='operacao',
            name='finalidade_emissao',
        ),
        migrations.RemoveField(
            model_name='operacao',
            name='tipo_desconto',
        ),
        migrations.AlterField(
            model_name='configuracaoimpressao',
            name='tipo_impressora',
            field=models.CharField(choices=[('termica', 'Térmica (Cupom)'), ('a4', 'A4 (Folha)')], default='termica', help_text='Tipo de impressora a utilizar', max_length=10),
        ),
        migrations.AlterField(
            model_name='produto',
            name='genero',
            field=models.CharField(blank=True, choices=[('feminino', 'Feminino'), ('masculino', 'Masculino'), ('unissex', 'Unissex')], help_text='Gênero do produto: feminino, masculino ou unissex', max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='FornecedorProdutoFracao',
        ),
        migrations.DeleteModel(
            name='UserPreferencia',
        ),
    ]
