# Generated by Django 6.0.2 on 2026-05-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0172_alter_userpreferencia_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteGrupoExcecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'clientes_grupos_excecao',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='produto',
            name='localizacao',
            field=models.CharField(blank=True, help_text='Localização física do produto', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='referencia',
            field=models.CharField(blank=True, help_text='Código de referência do produto', max_length=100, null=True),
        ),
    ]
