# Generated by Django 6.0.2 on 2026-05-21 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0173_clientegrupoexcecao_produto_localizacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quarto',
            fields=[
                ('id_quarto', models.AutoField(primary_key=True, serialize=False)),
                ('numero_quarto', models.CharField(help_text='Ex: 101, 102', max_length=10, unique=True)),
                ('status_atual', models.CharField(choices=[('disponivel', 'Disponível'), ('ocupado', 'Ocupado'), ('sujo', 'Sujo'), ('manutencao', 'Manutenção')], default='disponivel', max_length=20)),
                ('capacidade_adultos', models.PositiveIntegerField(default=2)),
                ('capacidade_criancas', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Quarto',
                'verbose_name_plural': 'Quartos',
                'db_table': 'hotel_quarto',
                'ordering': ['numero_quarto'],
            },
        ),
        migrations.CreateModel(
            name='TipoQuarto',
            fields=[
                ('id_tipo_quarto', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Ex: Single, Duplo, Suíte Master', max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('valor_diaria_padrao', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('limite_adultos', models.PositiveIntegerField(default=2)),
                ('limite_criancas', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Tipo de Quarto',
                'verbose_name_plural': 'Tipos de Quarto',
                'db_table': 'hotel_tipo_quarto',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('data_entrada_prevista', models.DateTimeField()),
                ('data_saida_prevista', models.DateTimeField()),
                ('data_checkin_real', models.DateTimeField(blank=True, null=True)),
                ('data_checkout_real', models.DateTimeField(blank=True, null=True)),
                ('status_reserva', models.CharField(choices=[('confirmada', 'Confirmada'), ('checkin', 'Check-in Realizado'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada'), ('noshow', 'No-show')], default='confirmada', max_length=20)),
                ('valor_diaria_aplicada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('hospede', models.ForeignKey(db_column='hospede_id', on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='api.cliente')),
                ('quarto', models.ForeignKey(db_column='quarto_id', on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='api.quarto')),
                ('venda', models.ForeignKey(blank=True, db_column='venda_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='api.venda')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'db_table': 'hotel_reserva',
                'ordering': ['-data_entrada_prevista'],
            },
        ),
        migrations.CreateModel(
            name='ConsumoQuarto',
            fields=[
                ('id_consumo', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.DecimalField(decimal_places=3, default=1.0, max_digits=10)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_lancamento', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.CharField(blank=True, max_length=255, null=True)),
                ('produto', models.ForeignKey(db_column='produto_id', on_delete=django.db.models.deletion.PROTECT, related_name='consumos_hospedagem', to='api.produto')),
                ('reserva', models.ForeignKey(db_column='reserva_id', on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='api.reserva')),
            ],
            options={
                'verbose_name': 'Consumo de Quarto',
                'verbose_name_plural': 'Consumo de Quartos',
                'db_table': 'hotel_consumo',
                'ordering': ['-data_lancamento'],
            },
        ),
        migrations.AddField(
            model_name='quarto',
            name='tipo',
            field=models.ForeignKey(db_column='tipo_id', on_delete=django.db.models.deletion.PROTECT, related_name='quartos', to='api.tipoquarto'),
        ),
    ]
