# Generated by Django 6.0.2 on 2026-05-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0174_quarto_tipoquarto_reserva_consumoquarto_quarto_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comodidade',
            fields=[
                ('id_comodidade', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Ex: Ar Condicionado, Frigobar, Wi-Fi', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Comodidade',
                'verbose_name_plural': 'Comodidades',
                'db_table': 'hotel_comodidade',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='quarto',
            name='comodidades',
            field=models.ManyToManyField(blank=True, db_table='hotel_quarto_comodidade', related_name='quartos', to='api.comodidade'),
        ),
    ]
