# Generated by Django 6.0.2 on 2026-05-22 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0175_comodidade_quarto_comodidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='chave_nfse',
            field=models.CharField(blank=True, db_column='chave_nfse', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='data_emissao_nfse',
            field=models.DateTimeField(blank=True, db_column='data_emissao_nfse', null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='numero_dps',
            field=models.IntegerField(blank=True, db_column='numero_dps', null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='numero_nfse',
            field=models.CharField(blank=True, db_column='numero_nfse', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='serie_dps',
            field=models.CharField(blank=True, db_column='serie_dps', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='status_nfse',
            field=models.CharField(blank=True, db_column='status_nfse', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='tipo_emissao_dps',
            field=models.CharField(blank=True, db_column='tipo_emissao_dps', default='normal', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='xml_url',
            field=models.TextField(blank=True, db_column='xml_url_nfse', null=True),
        ),
    ]
