# Generated by Django 6.0.2 on 2026-05-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0177_add_hotelaria_parametros'),
    ]

    operations = [
        migrations.CreateModel(
            name='TTSAudioCache',
            fields=[
                ('id_cache', models.AutoField(primary_key=True, serialize=False)),
                ('text_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('text', models.TextField()),
                ('audio_file_path', models.CharField(max_length=500)),
                ('audio_url', models.CharField(max_length=500)),
                ('provider', models.CharField(default='google', max_length=50)),
                ('voice', models.CharField(blank=True, max_length=100, null=True)),
                ('velocidade', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'TTS Audio Cache',
                'verbose_name_plural': 'TTS Audio Caches',
                'db_table': 'tts_audio_cache',
                'managed': True,
            },
        ),
    ]

