# Generated by Django 6.0.2 on 2026-05-24 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0178_ttsaudiocache_venda_valor_desconto'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaaSCliente',
            fields=[
                ('id_saas_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('cnpj', models.CharField(help_text='CNPJ da empresa contratante', max_length=14, unique=True)),
                ('razao_social', models.CharField(max_length=255)),
                ('dia_vencimento', models.IntegerField(default=10)),
                ('valor_mensalidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('emite_nota', models.BooleanField(default=False)),
                ('status_licenca', models.CharField(default='ATIVO', help_text='Status da licença: ATIVO, BLOQUEADO, DEMO', max_length=20)),
                ('data_reajuste', models.DateField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'SaaS Cliente',
                'verbose_name_plural': 'SaaS Clientes',
                'db_table': 'saas_cliente',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SaaSClienteContrato',
            fields=[
                ('id_contrato', models.AutoField(primary_key=True, serialize=False)),
                ('texto_contrato', models.TextField()),
                ('data_geracao', models.DateTimeField(auto_now_add=True)),
                ('assinado', models.BooleanField(default=False)),
                ('data_assinatura', models.DateTimeField(blank=True, null=True)),
                ('ip_assinatura', models.CharField(blank=True, max_length=45, null=True)),
                ('usuario_assinou', models.CharField(blank=True, max_length=100, null=True)),
                ('saas_cliente', models.ForeignKey(db_column='saas_cliente_id', on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='api.saascliente')),
            ],
            options={
                'verbose_name': 'SaaS Contrato',
                'verbose_name_plural': 'SaaS Contratos',
                'db_table': 'saas_cliente_contrato',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SaaSClienteMensalidade',
            fields=[
                ('id_mensalidade', models.AutoField(primary_key=True, serialize=False)),
                ('nosso_numero', models.CharField(blank=True, max_length=50, null=True)),
                ('data_emissao', models.DateField(auto_now_add=True)),
                ('data_vencimento', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status_pagamento', models.CharField(default='PENDENTE', help_text='PENDENTE, PAGO, VENCIDO, CANCELADO', max_length=20)),
                ('url_boleto', models.CharField(blank=True, max_length=500, null=True)),
                ('linha_digitavel', models.CharField(blank=True, max_length=255, null=True)),
                ('pix_copia_cola', models.TextField(blank=True, null=True)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('saas_cliente', models.ForeignKey(db_column='saas_cliente_id', on_delete=django.db.models.deletion.CASCADE, related_name='mensalidades', to='api.saascliente')),
            ],
            options={
                'verbose_name': 'SaaS Mensalidade',
                'verbose_name_plural': 'SaaS Mensalidades',
                'db_table': 'saas_cliente_mensalidade',
                'managed': True,
            },
        ),
    ]
