# Generated by Django 6.0.2 on 2026-05-26 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
        ('api', '0179_saascliente_venda_valor_desconto_saasclientecontrato_and_more'),
    ]

    operations = [
    ]
