# Generated by Django 6.0.2 on 2026-05-26 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0180_merge_20260526_1050'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='saascliente',
                    name='db_host',
                    field=models.CharField(default='localhost', max_length=100),
                ),
                migrations.AddField(
                    model_name='saascliente',
                    name='db_port',
                    field=models.CharField(default='8005', max_length=5),
                ),
                migrations.AddField(
                    model_name='saascliente',
                    name='is_test_environment',
                    field=models.BooleanField(default=False, help_text='Marcador para saber se é um ambiente de teste'),
                ),
                migrations.AddField(
                    model_name='saascliente',
                    name='schema_name',
                    field=models.SlugField(default='central', help_text='Identificador único do banco de dados (slug)', unique=True),
                ),
                migrations.AddField(
                    model_name='venda',
                    name='valor_desconto',
                    field=models.DecimalField(blank=True, db_column='valor_desconto', decimal_places=2, default=0.0, max_digits=10, null=True),
                ),
            ]
        ),
        migrations.AlterField(
            model_name='saascliente',
            name='cnpj',
            field=models.CharField(help_text='CNPJ da empresa contratante', max_length=18),
        ),
    ]
