# Generated by Django 6.0.2 on 2026-05-26 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0183_saascliente_fix_missing_0181_columns'),
    ]

    operations = [
        migrations.CreateModel(
            name='VersaoSistema',
            fields=[
                ('id_versao', models.AutoField(primary_key=True, serialize=False)),
                ('versao', models.CharField(max_length=20, unique=True, verbose_name='Versão')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição/Changelog')),
                ('data_lancamento', models.DateTimeField(auto_now_add=True, verbose_name='Data de Lançamento')),
            ],
            options={
                'verbose_name': 'Versão do Sistema',
                'verbose_name_plural': 'Versões do Sistema',
                'db_table': 'saas_versao_sistema',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HistoricoAtualizacao',
            fields=[
                ('id_historico', models.AutoField(primary_key=True, serialize=False)),
                ('data_atualizacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('SUCESSO', 'Sucesso'), ('FALHA', 'Falha'), ('PROCESSANDO', 'Processando')], default='PROCESSANDO', max_length=20)),
                ('log_erro', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(db_column='saas_cliente_id', on_delete=django.db.models.deletion.CASCADE, related_name='historicos_atualizacao', to='api.saascliente')),
                ('versao', models.ForeignKey(db_column='versao_id', on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='api.versaosistema')),
            ],
            options={
                'verbose_name': 'Histórico de Atualização',
                'verbose_name_plural': 'Históricos de Atualização',
                'db_table': 'saas_historico_atualizacao',
                'managed': True,
            },
        ),
    ]
