# Generated by Django 6.0.2 on 2026-05-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0184_versaosistema_historicoatualizacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoAgendamento',
            fields=[
                ('id_config', models.AutoField(primary_key=True, serialize=False)),
                ('horario_execucao', models.TimeField(default='02:00:00', verbose_name='Horário de Execução')),
                ('dias_da_semana', models.CharField(default='0,1,2,3,4,5,6', max_length=50, verbose_name='Dias da Semana (0-6)')),
                ('agendamento_ativo', models.BooleanField(default=True, verbose_name='Agendamento Ativo')),
            ],
            options={
                'verbose_name': 'Configuração de Agendamento',
                'verbose_name_plural': 'Configurações de Agendamento',
                'db_table': 'saas_configuracao_agendamento',
                'managed': True,
            },
        ),
    ]
