# Generated by Django 6.0.2 on 2026-05-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0185_configuracaoagendamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='saascliente',
            name='banco_criado',
            field=models.BooleanField(default=False, verbose_name='Banco de Dados Criado'),
        ),
    ]
