# Generated by Django 6.0.2 on 2026-05-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0186_saascliente_banco_criado'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissoes',
            name='pode_atualizar_cliente',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='userpermissoes',
            name='pode_criar_banco',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='userpermissoes',
            name='pode_gerenciar_agendamento',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='userpermissoes',
            name='pode_cadastrar_financeiro_saas',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.RunSQL(
            sql="""
            ALTER TABLE user_permissoes ADD COLUMN pode_atualizar_cliente INT DEFAULT 0;
            ALTER TABLE user_permissoes ADD COLUMN pode_criar_banco INT DEFAULT 0;
            ALTER TABLE user_permissoes ADD COLUMN pode_gerenciar_agendamento INT DEFAULT 0;
            ALTER TABLE user_permissoes ADD COLUMN pode_cadastrar_financeiro_saas INT DEFAULT 0;
            """,
            reverse_sql="""
            ALTER TABLE user_permissoes DROP COLUMN pode_atualizar_cliente;
            ALTER TABLE user_permissoes DROP COLUMN pode_criar_banco;
            ALTER TABLE user_permissoes DROP COLUMN pode_gerenciar_agendamento;
            ALTER TABLE user_permissoes DROP COLUMN pode_cadastrar_financeiro_saas;
            """
        ),
    ]
