# Generated by Django 6.0.2 on 2026-05-30 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0187_add_saas_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='saascliente',
            name='contrato_pendente',
            field=models.BooleanField(default=False, verbose_name='Contrato Pendente'),
        ),
        migrations.AddField(
            model_name='saascliente',
            name='data_nascimento_responsavel',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento do Responsável'),
        ),
        migrations.AddField(
            model_name='saascliente',
            name='email_responsavel',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='E-mail do Responsável'),
        ),
        migrations.AddField(
            model_name='saasclientecontrato',
            name='assinado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Assinado em'),
        ),
        migrations.AddField(
            model_name='saasclientecontrato',
            name='token_expira_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expira em'),
        ),
        migrations.AddField(
            model_name='saasclientecontrato',
            name='token_validacao',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Token de Validação'),
        ),
        migrations.AddField(
            model_name='saasclientecontrato',
            name='user_agent',
            field=models.TextField(blank=True, null=True, verbose_name='User Agent'),
        ),
    ]
