# Generated by Django 6.0.5 on 2026-05-29 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0187_add_saas_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateContrato',
            fields=[
                ('id_template', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(default='Contrato de Prestação de Serviços SaaS', max_length=200, verbose_name='Título')),
                ('texto_template', models.TextField(help_text='Texto do contrato com tags: {{ cliente_razao_social }}, {{ cliente_cnpj }}, {{ mensalidade_base }}', verbose_name='Texto do Template')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'SaaS Template Contrato',
                'verbose_name_plural': 'SaaS Templates Contratos',
                'db_table': 'saas_template_contrato',
                'managed': True,
            },
        ),
    ]
