# Generated by Django 6.0.2 on 2026-05-30 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0188_saascliente_contrato_pendente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoPadrao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Contrato Padrão de Prestação de Serviços - Aperus', max_length=150)),
                ('versao', models.CharField(default='1.0', max_length=10)),
                ('conteudo_html', models.TextField(help_text='Texto do contrato contendo tags como {{ cliente_razao_social }}')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Contrato Padrão',
                'verbose_name_plural': 'Contratos Padrão',
                'db_table': 'saas_contrato_padrao',
                'managed': True,
            },
        ),
    ]
