# Generated by Django 6.0.4 on 2026-05-30 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0189_add_habilitar_central_saas'),
        ('api', '0189_contratopadrao'),
    ]

    operations = [
    ]
