# Generated by Django 6.0.5 on 2026-06-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0190_merge_20260530_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComunicadoSaaS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('IMAGEM', 'Imagem/Arte'), ('VIDEO', 'Vídeo do YouTube'), ('TEXTO', 'Apenas Texto')], default='TEXTO', max_length=10)),
                ('conteudo_texto', models.TextField(blank=True, null=True)),
                ('url_midia', models.URLField(blank=True, help_text='Link da imagem ou do vídeo do YouTube', null=True)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Comunicado SaaS',
                'verbose_name_plural': 'Comunicados SaaS',
                'db_table': 'saas_comunicado',
                'managed': True,
            },
        ),

        migrations.DeleteModel(
            name='TemplateContrato',
        ),
    ]
