# Generated by Django 6.0.5 on 2026-06-03 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0191_comunicadosaas_licenca_delete_templatecontrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunicadosaas',
            name='imagem',
            field=models.ImageField(blank=True, help_text='Upload direto do arquivo de imagem', null=True, upload_to='comunicados/'),
        ),
    ]
