# Generated by Django 6.0.5 on 2026-06-05 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0192_licenca_comunicadosaas_imagem'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Licenca',
                    fields=[
                        ('id_licenca', models.AutoField(primary_key=True, serialize=False)),
                        ('chave_licenca', models.CharField(max_length=255, unique=True)),
                        ('data_validade', models.DateField()),
                        ('ultimo_check', models.DateTimeField(blank=True, null=True)),
                        ('status', models.CharField(default='Ativa', max_length=20)),
                    ],
                    options={
                        'verbose_name': 'Licença',
                        'verbose_name_plural': 'Licenças',
                        'db_table': 'licenca',
                        'managed': True,
                    },
                ),
            ],
            database_operations=[]
        ),
        migrations.CreateModel(
            name='GabaritoCustomizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_relatorio', models.CharField(help_text='Ex: nfe_gabarito_custom ou etiqueta_barra', max_length=100)),
                ('tipo_gabarito', models.CharField(choices=[('ETIQUETA', 'Etiqueta Térmica'), ('A4_RETRATO', 'Relatório A4 Retrato'), ('A4_PAISAGEM', 'Relatório A4 Paisagem'), ('RECIBO', 'Recibo / Bobina 80mm')], default='A4_RETRATO', max_length=20)),
                ('layout_json', models.JSONField(help_text='Coordenadas e configurações dos campos do relatório')),
                ('largura_gabarito_mm', models.IntegerField(default=210, help_text='Largura total da página/etiqueta em milímetros')),
                ('altura_gabarito_mm', models.IntegerField(default=297, help_text='Altura total (use 0 ou 297 para A4 livre)')),
                ('ativo', models.BooleanField(default=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gabaritos', to='api.saascliente')),
            ],
            options={
                'verbose_name': 'Gabarito Customizado',
                'verbose_name_plural': 'Gabaritos Customizados',
                'db_table': 'saas_gabarito_customizado',
                'managed': True,
            },
        ),
    ]
