# Generated by Django 6.0.5 on 2026-06-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0193_licenca_gabaritocustomizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoimpressao',
            name='gabarito_customizado_nome',
            field=models.CharField(blank=True, default=None, help_text='Nome do gabarito customizado se selecionado', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='configuracaoimpressao',
            name='tipo_impressora',
            field=models.CharField(choices=[('termica', 'Térmica (Cupom)'), ('a4', 'A4 (Folha)'), ('personalizado', 'Gabarito Customizado')], default='termica', help_text='Tipo de impressora a utilizar', max_length=20),
        ),
    ]
