# Generated by Django 6.0.5 on 2026-06-15 13:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0194_configuracaoimpressao_gabarito_customizado_nome_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkCadastroRemoto',
            fields=[
                ('id_token', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('whatsapp_cliente', models.CharField(max_length=20, verbose_name='WhatsApp do Cliente')),
                ('usado', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('expira_em', models.DateTimeField()),
                ('dia_vencimento', models.IntegerField(default=10)),
                ('valor_mensalidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('emite_nota', models.BooleanField(default=False)),
                ('vendedor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Vendedor/Representante')),
                ('status_licenca', models.CharField(default='ATIVO', max_length=20)),
                ('schema_name', models.SlugField(blank=True, null=True, verbose_name='Slug / Schema')),
                ('db_host', models.CharField(default='localhost', max_length=100)),
                ('db_port', models.CharField(default='8005', max_length=5)),
                ('is_test_environment', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Link Cadastro Remoto',
                'verbose_name_plural': 'Links Cadastros Remotos',
                'db_table': 'saas_link_cadastro_remoto',
                'managed': True,
            },
        ),
    ]
