# Generated by Django 6.0.5 on 2026-06-15 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0195_linkcadastroremoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoSaaS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome do Plano')),
                ('valor_mensalidade', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Mensalidade')),
                ('modulo_pdv', models.BooleanField(default=True, verbose_name='Frente de Caixa / NFC-e')),
                ('modulo_financeiro_avancado', models.BooleanField(default=False, verbose_name='Financeiro Avançado')),
                ('modulo_producao_industria', models.BooleanField(default=False, verbose_name='Controle de Produção/Estoque Avançado')),
                ('modulo_transporte_cte', models.BooleanField(default=False, verbose_name='Emissão de CT-e e MDF-e')),
                ('modulo_ciot_automatico', models.BooleanField(default=False, verbose_name='Automação de CIOT')),
                ('modulo_report_builder', models.BooleanField(default=False, verbose_name='Editor de Relatórios Customizados')),
            ],
            options={
                'verbose_name': 'Plano SaaS',
                'verbose_name_plural': 'Planos SaaS',
                'db_table': 'saas_plano',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='licenca',
            name='recursos_planos',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Módulos / Recursos do Plano'),
        ),
        migrations.AddField(
            model_name='linkcadastroremoto',
            name='plano',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='links_cadastro', to='api.planosaas'),
        ),
        migrations.AddField(
            model_name='saascliente',
            name='plano',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='api.planosaas'),
        ),
        migrations.AddField(
            model_name='saascliente',
            name='upgrade_solicitado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_solicitando_upgrade', to='api.planosaas'),
        ),
    ]
