# Generated by Django 6.0.5 on 2026-06-17 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0196_planosaas_licenca_recursos_planos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaobancaria',
            name='banco',
            field=models.CharField(choices=[('BB', 'Banco do Brasil'), ('ITAU', 'Itaú'), ('BRADESCO', 'Bradesco'), ('SICOOB', 'Sicoob'), ('SANTANDER', 'Santander'), ('CAIXA', 'Caixa Econômica'), ('MERCADOPAGO', 'Mercado Pago'), ('OUTROS', 'Outros')], max_length=20),
        ),
    ]
