# Generated by Django 6.0.5 on 2026-06-17 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0197_alter_configuracaobancaria_banco'),
    ]

    operations = [
        migrations.AddField(
            model_name='saascliente',
            name='limite_maquinas',
            field=models.IntegerField(default=1, verbose_name='Quantidade de Máquinas Contratadas'),
        ),
        migrations.CreateModel(
            name='TerminalAtivo',
            fields=[
                ('id_terminal', models.AutoField(primary_key=True, serialize=False)),
                ('hardware_id', models.CharField(max_length=255, unique=True)),
                ('nome_computador', models.CharField(help_text='Ex: CAIXA_01, ESCRITORIO', max_length=100)),
                ('ativado_em', models.DateTimeField(auto_now_add=True)),
                ('ultimo_acesso', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(db_column='saas_cliente_id', on_delete=django.db.models.deletion.CASCADE, related_name='terminais', to='api.saascliente')),
            ],
            options={
                'verbose_name': 'Terminal Ativo',
                'verbose_name_plural': 'Terminais Ativos',
                'db_table': 'saas_terminal_ativo',
                'managed': True,
            },
        ),
    ]
