# Generated by Django 6.0.5 on 2026-06-18 11:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0198_saascliente_limite_maquinas_terminalativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='saasclientemensalidade',
            name='configuracao_bancaria',
            field=models.ForeignKey(blank=True, db_column='id_config_bancaria', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensalidades', to='api.configuracaobancaria'),
        ),
    ]
