# Generated by Django 6.0.5 on 2026-06-18 12:04

import api.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0199_boleto_atualizado_em_boleto_criado_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleto',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='boleto',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='boleto',
            name='baixado_via_api',
            field=models.BooleanField(db_column='baixa_via_api', default=False, help_text='Foi baixado automaticamente via API'),
        ),
        migrations.AlterField(
            model_name='boleto',
            name='dados_retorno_json',
            field=models.JSONField(blank=True, db_column='resposta_banco', help_text='JSON completo do retorno do banco', null=True),
        ),
        migrations.AlterField(
            model_name='boleto',
            name='data_baixa_api',
            field=models.DateTimeField(blank=True, db_column='baixa_realizada_em', help_text='Data/hora da baixa via API', null=True),
        ),
        migrations.AlterField(
            model_name='boleto',
            name='id_config_bancaria',
            field=models.ForeignKey(db_column='id_config', on_delete=django.db.models.deletion.PROTECT, related_name='boletos', to='api.configuracaobancaria'),
        ),
        migrations.AlterField(
            model_name='boleto',
            name='id_conta',
            field=models.ForeignKey(db_column='id_conta', on_delete=django.db.models.deletion.PROTECT, related_name='boletos', to='api.financeiroconta'),
        ),
        migrations.AlterField(
            model_name='boleto',
            name='pagador_codigo_ibge',
            field=models.CharField(blank=True, db_column='codigo_ibge_cidade', help_text='Código IBGE da cidade (importante!)', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='boleto',
            name='pix_qr_code',
            field=models.TextField(blank=True, db_column='qrcode_pix', help_text='Código QR Code PIX', null=True),
        ),
        migrations.AlterField(
            model_name='boleto',
            name='url_boleto',
            field=models.URLField(blank=True, db_column='url_boleto_pdf', help_text='URL para download do PDF', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='configuracaobancaria',
            name='access_token',
            field=api.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='configuracaobancaria',
            name='client_id',
            field=api.fields.EncryptedCharField(help_text='Client ID fornecido pelo banco', max_length=255),
        ),
        migrations.AlterField(
            model_name='configuracaobancaria',
            name='client_secret',
            field=api.fields.EncryptedCharField(help_text='Client Secret fornecido pelo banco', max_length=255),
        ),
        migrations.AlterField(
            model_name='configuracaobancaria',
            name='refresh_token',
            field=api.fields.EncryptedTextField(blank=True, null=True),
        ),
    ]
