# Generated by Django 6.0.4 on 2026-06-19 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0200_boleto_atualizado_em_boleto_criado_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saascliente',
            name='link_acesso',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Link de Acesso'),
        ),
    ]
