# Generated by Django 6.0.5 on 2026-06-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0201_saascliente_link_acesso'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendamentoBackupLocal',
            fields=[
                ('id_agendamento', models.AutoField(primary_key=True, serialize=False)),
                ('diretorio_destino', models.CharField(default='G:\\Meu Drive\\BackupsAperus', help_text='Caminho completo da pasta dentro da unidade G: do Google Drive', max_length=255)),
                ('segunda', models.BooleanField(default=True)),
                ('terca', models.BooleanField(default=True)),
                ('quarta', models.BooleanField(default=True)),
                ('quinta', models.BooleanField(default=True)),
                ('sexta', models.BooleanField(default=True)),
                ('sabado', models.BooleanField(default=True)),
                ('domingo', models.BooleanField(default=True)),
                ('horarios_execucao', models.TextField(default='02:00', help_text='Horários separados por vírgula para execução diária')),
                ('retencao_arquivos', models.IntegerField(default=30, help_text='Quantidade máxima de arquivos de backup a manter na pasta')),
                ('ativo', models.BooleanField(default=True)),
                ('ultimo_backup_em', models.DateTimeField(blank=True, null=True)),
                ('status_ultimo_backup', models.CharField(default='Pendente', max_length=50)),
            ],
            options={
                'verbose_name': 'Backup Agendado Local',
                'verbose_name_plural': 'Backups Agendados Locais',
                'db_table': 'saas_backup_agendado_local',
                'managed': True,
            },
        ),
    ]
