# Generated by Django 6.0.4 on 2026-06-29 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0202_agendamentobackuplocal'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='taxa_servico',
            field=models.DecimalField(blank=True, db_column='taxa_servico', decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
    ]
