# Generated by Django 6.0.5 on 2026-07-01 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0203_venda_taxa_servico'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentralErroLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_schema', models.CharField(help_text='Qual cliente gerou o erro (ex: amerpusinformatica)', max_length=100)),
                ('url_afetada', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_excecao', models.CharField(help_text='Ex: KeyError, OperationalError', max_length=255)),
                ('mensagem_erro', models.TextField()),
                ('traceback_completo', models.TextField(help_text='Onde o código quebrou exatamente')),
                ('nivel', models.CharField(choices=[('ERROR', 'Erro Crítico'), ('WARNING', 'Aviso / Alerta')], default='ERROR', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('resolvido', models.BooleanField(default=False)),
                ('observacao_suporte', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Log de Erro Centralizado',
                'verbose_name_plural': 'Logs de Erro Centralizados',
                'db_table': 'saas_central_erro_log',
                'ordering': ['-criado_em'],
                'managed': True,
            },
        ),
    ]
