# Generated by Django 6.0.4 on 2026-07-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0204_centralerrolog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacao',
            name='modelo_documento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
