# Generated by Django 6.0.4 on 2026-07-11 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0205_alter_operacao_modelo_documento'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tipotributacao',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='tipotributacao',
            name='regime_tributario',
            field=models.CharField(choices=[('SIMPLES', 'Simples Nacional'), ('NORMAL', 'Regime Normal')], default='SIMPLES', help_text='Regime ao qual o perfil se aplica', max_length=20),
        ),
        migrations.AddField(
            model_name='tributacaoproduto',
            name='tipo_tributacao',
            field=models.ForeignKey(blank=True, help_text='Perfil de tributação padrão associado ao produto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos_tributados', to='api.tipotributacao'),
        ),
        migrations.AlterUniqueTogether(
            name='tipotributacao',
            unique_together={('empresa', 'nome', 'regime_tributario')},
        ),
    ]
