# Generated by Django 6.0.4 on 2026-07-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0207_userpreferencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipotributacao',
            name='cofins_aliq',
            field=models.DecimalField(decimal_places=4, default=3.0, help_text='Alíquota do COFINS (%)', max_digits=7),
        ),
        migrations.AddField(
            model_name='tipotributacao',
            name='cofins_cst',
            field=models.CharField(blank=True, default='01', help_text='CST do COFINS (ex: 01, 02, 04, 06, 07, 08, 49, 99)', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='tipotributacao',
            name='ipi_aliq',
            field=models.DecimalField(decimal_places=4, default=0.0, help_text='Alíquota do IPI (%)', max_digits=7),
        ),
        migrations.AddField(
            model_name='tipotributacao',
            name='ipi_cst',
            field=models.CharField(blank=True, default='53', help_text='CST do IPI (ex: 50, 51, 52, 53, 55, 99)', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='tipotributacao',
            name='ipi_enquadramento',
            field=models.CharField(blank=True, default='999', help_text='Código de Enquadramento IPI', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='tipotributacao',
            name='pis_aliq',
            field=models.DecimalField(decimal_places=4, default=0.65, help_text='Alíquota do PIS (%)', max_digits=7),
        ),
        migrations.AddField(
            model_name='tipotributacao',
            name='pis_cst',
            field=models.CharField(blank=True, default='01', help_text='CST do PIS (ex: 01, 02, 04, 06, 07, 08, 49, 99)', max_length=3, null=True),
        ),
    ]
