# Generated by Django 6.0.4 on 2026-07-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0208_tipotributacao_cofins_aliq_tipotributacao_cofins_cst_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tributacaoproduto',
            name='ad_rem_icms_ret',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='tributacaoproduto',
            name='cprod_anp',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='tributacaoproduto',
            name='desc_anp',
            field=models.CharField(blank=True, default='', max_length=95, null=True),
        ),
        migrations.AddField(
            model_name='tributacaoproduto',
            name='pglp',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='tributacaoproduto',
            name='pgni',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='tributacaoproduto',
            name='pgnn',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='tributacaoproduto',
            name='vpart',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=12),
        ),
    ]
