# Generated by Django 6.0.4 on 2026-07-30 15:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0209_tributacaoproduto_ad_rem_icms_ret_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoResponsabilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('cliente_nome', models.CharField(max_length=255)),
                ('cliente_documento', models.CharField(blank=True, max_length=20)),
                ('cliente_whatsapp', models.CharField(blank=True, max_length=20)),
                ('texto_contrato', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('assinado_em', models.DateTimeField(blank=True, null=True)),
                ('assinado_por_nome', models.CharField(blank=True, max_length=255)),
                ('assinado_por_cpf', models.CharField(blank=True, max_length=20)),
                ('assinatura_desenho', models.TextField(blank=True, help_text='Desenho em Base64', null=True)),
                ('status', models.CharField(default='PENDENTE', max_length=20)),
                ('ip_assinatura', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'contrato_responsabilidade',
                'ordering': ['-criado_em'],
                'managed': True,
            },
        ),
    ]
