# Generated by Django 6.0.4 on 2026-07-30 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0210_contratoresponsabilidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratoresponsabilidade',
            name='cliente_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contratoresponsabilidade',
            name='token_expira',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contratoresponsabilidade',
            name='token_validacao',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
