# Generated by Django 6.0.4 on 2026-08-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0211_contratoresponsabilidade_cliente_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacao',
            name='finalidade_emissao',
            field=models.CharField(blank=True, db_column='finalidade_emissao', default='1', help_text='Finalidade de emissão da NF-e (finNFe): 1-Normal, 2-Complementar, 3-Ajuste, 4-Devolução, 5-Crédito, 6-Débito Pgto Antecipado, 7-Débito Perda Estoque', max_length=1, null=True),
        ),
    ]
