# Generated by Django 6.0.4 on 2026-08-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0212_operacao_finalidade_emissao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contaservico',
            name='chave_acesso',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
