# Generated by Django 5.2.7 on 2025-11-10 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LayoutEtiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_layout', models.CharField(max_length=100, verbose_name='Nome do Layout')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('tamanho_papel', models.CharField(choices=[('A4', 'A4 (210x297mm)'), ('CARTA', 'Carta (215.9x279.4mm)'), ('10X15', '10x15cm'), ('5X5', '5x5cm'), ('7X5', '7x5cm'), ('CUSTOM', 'Personalizado')], default='A4', max_length=20)),
                ('largura_papel', models.DecimalField(decimal_places=2, default=210, max_digits=6, verbose_name='Largura do Papel (mm)')),
                ('altura_papel', models.DecimalField(decimal_places=2, default=297, max_digits=6, verbose_name='Altura do Papel (mm)')),
                ('largura_etiqueta', models.DecimalField(decimal_places=2, default=50, max_digits=6, verbose_name='Largura da Etiqueta (mm)')),
                ('altura_etiqueta', models.DecimalField(decimal_places=2, default=30, max_digits=6, verbose_name='Altura da Etiqueta (mm)')),
                ('colunas', models.IntegerField(default=3, verbose_name='Número de Colunas')),
                ('linhas', models.IntegerField(default=10, verbose_name='Número de Linhas')),
                ('margem_superior', models.DecimalField(decimal_places=2, default=10, max_digits=6, verbose_name='Margem Superior (mm)')),
                ('margem_inferior', models.DecimalField(decimal_places=2, default=10, max_digits=6, verbose_name='Margem Inferior (mm)')),
                ('margem_esquerda', models.DecimalField(decimal_places=2, default=5, max_digits=6, verbose_name='Margem Esquerda (mm)')),
                ('margem_direita', models.DecimalField(decimal_places=2, default=5, max_digits=6, verbose_name='Margem Direita (mm)')),
                ('espaco_horizontal', models.DecimalField(decimal_places=2, default=2, max_digits=6, verbose_name='Espaço Horizontal (mm)')),
                ('espaco_vertical', models.DecimalField(decimal_places=2, default=2, max_digits=6, verbose_name='Espaço Vertical (mm)')),
                ('campos_visiveis', models.JSONField(default=dict, help_text='JSON com campos e suas configurações', verbose_name='Campos Visíveis')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario_criacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='layouts_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Layout de Etiqueta',
                'verbose_name_plural': 'Layouts de Etiqueta',
                'db_table': 'layouts_etiqueta',
                'ordering': ['nome_layout'],
            },
        ),
        migrations.CreateModel(
            name='ImpressaoEtiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produtos', models.JSONField(help_text='Lista de IDs e quantidades', verbose_name='Produtos Impressos')),
                ('quantidade_total', models.IntegerField(default=0)),
                ('data_impressao', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='impressoes', to='etiquetas.layoutetiqueta')),
            ],
            options={
                'verbose_name': 'Impressão de Etiqueta',
                'verbose_name_plural': 'Impressões de Etiqueta',
                'db_table': 'impressoes_etiqueta',
                'ordering': ['-data_impressao'],
            },
        ),
    ]
