# Generated by Django 5.2.7 on 2025-11-25 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etiquetas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='impressaoetiqueta',
            name='cliente_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID do Cliente'),
        ),
    ]
