# Generated by Django 6.0.5 on 2026-06-25 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etiquetas', '0002_impressaoetiqueta_cliente_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layoutetiqueta',
            name='tamanho_papel',
            field=models.CharField(choices=[('A4', 'A4 (210x297mm)'), ('CARTA', 'Carta (215.9x279.4mm)'), ('10X15', '10x15cm'), ('5X5', '5x5cm'), ('7X5', '7x5cm'), ('TOMATE_80X50', 'Tomate 80x50mm'), ('TOMATE_58', 'Tomate 58mm (Bobina)'), ('CUSTOM', 'Personalizado')], default='A4', max_length=20),
        ),
    ]
