# Generated by Django 5.2.7 on 2025-11-10 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comandas', '0001_initial'),
    ]

    operations = [
    ]
