# Generated by Django 5.2.7 on 2025-11-10 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comandas', '0002_initial_comandas'),
    ]

    operations = [
        migrations.AddField(
            model_name='comanda',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('Dinheiro', 'Dinheiro'), ('Cartão de Crédito', 'Cartão de Crédito'), ('Cartão de Débito', 'Cartão de Débito'), ('PIX', 'PIX'), ('Vale Refeição', 'Vale Refeição'), ('Cortesia', 'Cortesia'), ('Fiado', 'Fiado')], max_length=30, null=True, verbose_name='Forma de Pagamento'),
        ),
    ]
