# Generated by Django 5.2.7 on 2025-11-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comandas', '0003_comanda_forma_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comanda',
            name='numero',
            field=models.CharField(max_length=20, verbose_name='Número da Comanda'),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='numero',
            field=models.CharField(max_length=10, verbose_name='Número da Mesa'),
        ),
    ]
