# Generated by Django 5.2.7 on 2025-11-26 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comandas', '0004_remove_unique_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comanda',
            name='forma_pagamento',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Forma de Pagamento'),
        ),
    ]
