# Generated by Django 6.0 on 2025-12-11 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comandas', '0005_alter_comanda_forma_pagamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagamentoComanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma_pagamento', models.CharField(max_length=50, verbose_name='Forma de Pagamento')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('comanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='comandas.comanda')),
            ],
            options={
                'verbose_name': 'Pagamento da Comanda',
                'verbose_name_plural': 'Pagamentos da Comanda',
                'db_table': 'pagamentos_comanda',
            },
        ),
    ]
