# Generated by Django 6.0.2 on 2026-03-02 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0100_produto_metragem_caixa_produto_peso_unitario_and_more'),
        ('comandas', '0006_pagamentocomanda'),
    ]

    operations = [
        migrations.AddField(
            model_name='comanda',
            name='id_operacao_nfce',
            field=models.ForeignKey(blank=True, help_text='Operação fiscal a ser usada ao emitir NFC-e desta comanda', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comandas_nfce', to='api.operacao', verbose_name='Operação NFC-e'),
        ),
    ]
