# Generated by Django - Adicionar campo id_vendedor na Comanda

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('comandas', '0007_comanda_id_operacao_nfce'),
    ]

    operations = [
        migrations.AddField(
            model_name='comanda',
            name='id_vendedor',
            field=models.ForeignKey(
                blank=True,
                db_column='id_vendedor',
                help_text='Vendedor da comanda (buscado dos parâmetros do usuário ao fechar)',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='comandas_vendedor',
                to='api.vendedor',
                verbose_name='Vendedor'
            ),
        ),
    ]
