# Generated by Django 6.0.2 on 2026-04-17 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0165_adicionar_fracao_aplicada_compra_item'),
        ('comandas', '0008_comanda_id_vendedor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transferenciamesa',
            options={'ordering': ['-data_transferencia'], 'verbose_name': 'TransferÃªncia de Mesa', 'verbose_name_plural': 'TransferÃªncias de Mesa'},
        ),
        migrations.AlterField(
            model_name='comanda',
            name='id_operacao_nfce',
            field=models.ForeignKey(blank=True, help_text='OperaÃ§Ã£o fiscal a ser usada ao emitir NFC-e desta comanda', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comandas_nfce', to='api.operacao', verbose_name='OperaÃ§Ã£o NFC-e'),
        ),
        migrations.AlterField(
            model_name='comanda',
            name='id_vendedor',
            field=models.ForeignKey(blank=True, db_column='id_vendedor', help_text='Vendedor da comanda (buscado dos parÃ¢metros do usuÃ¡rio ao fechar)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comandas_vendedor', to='api.vendedor', verbose_name='Vendedor'),
        ),
        migrations.AlterField(
            model_name='comanda',
            name='numero',
            field=models.CharField(max_length=20, verbose_name='NÃºmero da Comanda'),
        ),
        migrations.AlterField(
            model_name='itemcomanda',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='ObservaÃ§Ãµes do item'),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='localizacao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='LocalizaÃ§Ã£o'),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='numero',
            field=models.CharField(max_length=10, verbose_name='NÃºmero da Mesa'),
        ),
    ]
