# Generated by Django 6.0.2 on 2026-03-04 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManifestoEletronico',
            fields=[
                ('id_mdfe', models.AutoField(primary_key=True, serialize=False)),
                ('chave_mdfe', models.CharField(blank=True, max_length=44, null=True)),
                ('protocolo_mdfe', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_mdfe', models.IntegerField(blank=True, null=True)),
                ('serie_mdfe', models.IntegerField(default=1)),
                ('status_mdfe', models.CharField(default='PENDENTE', max_length=20)),
                ('xml_mdfe', models.TextField(blank=True, null=True)),
                ('qrcode_url', models.CharField(blank=True, max_length=500, null=True)),
                ('cstat', models.IntegerField(blank=True, null=True)),
                ('xmotivo', models.CharField(blank=True, max_length=255, null=True)),
                ('data_emissao', models.DateTimeField(auto_now_add=True)),
                ('data_inicio_viagem', models.DateTimeField(blank=True, null=True)),
                ('cfop', models.CharField(default='5932', max_length=4)),
                ('modelo', models.CharField(default='58', max_length=2)),
                ('tipo_emitente', models.IntegerField(default=1)),
                ('tipo_transporte', models.IntegerField(default=1)),
                ('modal', models.CharField(default='01', max_length=2)),
                ('uf_inicio', models.CharField(blank=True, max_length=2, null=True)),
                ('uf_fim', models.CharField(blank=True, max_length=2, null=True)),
                ('quantidade_cte', models.IntegerField(default=0)),
                ('quantidade_nfe', models.IntegerField(default=0)),
                ('valor_total_carga', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('peso_total_kg', models.DecimalField(decimal_places=4, default=0.0, max_digits=12)),
                ('produto_predominante', models.CharField(blank=True, default='Diversos', max_length=120, null=True)),
                ('cep_carregamento', models.CharField(blank=True, max_length=8, null=True)),
                ('cep_descarregamento', models.CharField(blank=True, max_length=8, null=True)),
                ('responsavel_seguro', models.CharField(default='2', max_length=1)),
                ('nome_seguradora', models.CharField(blank=True, max_length=60, null=True)),
                ('numero_apolice', models.CharField(blank=True, max_length=20, null=True)),
                ('cnpj_seguradora', models.CharField(blank=True, max_length=14, null=True)),
                ('condutor_nome', models.CharField(blank=True, max_length=60, null=True)),
                ('condutor_cpf', models.CharField(blank=True, max_length=11, null=True)),
                ('placa_veiculo', models.CharField(blank=True, max_length=7, null=True)),
                ('uf_veiculo', models.CharField(blank=True, max_length=2, null=True)),
                ('rntrc_veiculo', models.CharField(blank=True, help_text='RNTRC do Veículo', max_length=8, null=True)),
                ('proprietario_veiculo_cpf_cnpj', models.CharField(blank=True, max_length=14, null=True)),
                ('proprietario_veiculo_tipo', models.IntegerField(default=1)),
                ('proprietario_veiculo_nome', models.CharField(blank=True, max_length=60, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MDF-e',
                'verbose_name_plural': 'MDF-e',
                'db_table': 'mdfe_manifestos',
                'ordering': ['-id_mdfe'],
            },
        ),
        migrations.CreateModel(
            name='MDFeCarregamento',
            fields=[
                ('id_carregamento', models.AutoField(primary_key=True, serialize=False)),
                ('municipio_nome', models.CharField(max_length=60)),
                ('municipio_codigo_ibge', models.CharField(max_length=7)),
                ('uf', models.CharField(max_length=2)),
                ('mdfe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carregamentos', to='mdfe.manifestoeletronico')),
            ],
            options={
                'verbose_name': 'Carregamento',
                'verbose_name_plural': 'Carregamentos',
                'db_table': 'mdfe_carregamentos',
            },
        ),
        migrations.CreateModel(
            name='MDFeCondutor',
            fields=[
                ('id_condutor', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=60)),
                ('cpf', models.CharField(max_length=11)),
                ('mdfe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condutores_adicionais', to='mdfe.manifestoeletronico')),
            ],
            options={
                'verbose_name': 'Condutor Adicional',
                'verbose_name_plural': 'Condutores Adicionais',
                'db_table': 'mdfe_condutores',
            },
        ),
        migrations.CreateModel(
            name='MDFeDescarregamento',
            fields=[
                ('id_descarregamento', models.AutoField(primary_key=True, serialize=False)),
                ('municipio_nome', models.CharField(max_length=60)),
                ('municipio_codigo_ibge', models.CharField(max_length=7)),
                ('uf', models.CharField(max_length=2)),
                ('mdfe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descarregamentos', to='mdfe.manifestoeletronico')),
            ],
            options={
                'verbose_name': 'Descarregamento',
                'verbose_name_plural': 'Descarregamentos',
                'db_table': 'mdfe_descarregamentos',
            },
        ),
        migrations.CreateModel(
            name='MDFeDocumentoVinculado',
            fields=[
                ('id_doc', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(choices=[('CTE', 'CT-e - Conhecimento de Transporte Eletrônico'), ('NFE', 'NF-e - Nota Fiscal Eletrônica')], default='NFE', max_length=3)),
                ('chave_acesso', models.CharField(help_text='Chave de Acesso do documento (44 dígitos)', max_length=44)),
                ('uf_percurso', models.CharField(blank=True, max_length=2, null=True)),
                ('municipio_carregamento', models.CharField(blank=True, max_length=60, null=True)),
                ('municipio_descarregamento', models.CharField(blank=True, max_length=60, null=True)),
                ('mdfe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_vinculados', to='mdfe.manifestoeletronico')),
            ],
            options={
                'verbose_name': 'Documento Vinculado',
                'verbose_name_plural': 'Documentos Vinculados',
                'db_table': 'mdfe_documentos_vinculados',
            },
        ),
        migrations.CreateModel(
            name='MDFeLacre',
            fields=[
                ('id_lacre', models.AutoField(primary_key=True, serialize=False)),
                ('numero_lacre', models.CharField(max_length=60)),
                ('mdfe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lacres', to='mdfe.manifestoeletronico')),
            ],
            options={
                'verbose_name': 'Lacre',
                'verbose_name_plural': 'Lacres',
                'db_table': 'mdfe_lacres',
            },
        ),
        migrations.CreateModel(
            name='MDFePercurso',
            fields=[
                ('id_percurso', models.AutoField(primary_key=True, serialize=False)),
                ('uf', models.CharField(help_text='Sigla da UF', max_length=2)),
                ('ordem', models.IntegerField(default=1, help_text='Ordem de percurso')),
                ('mdfe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='percursos', to='mdfe.manifestoeletronico')),
            ],
            options={
                'verbose_name': 'Percurso',
                'verbose_name_plural': 'Percursos',
                'db_table': 'mdfe_percursos',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='MDFeReboque',
            fields=[
                ('id_reboque', models.AutoField(primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=7)),
                ('uf', models.CharField(max_length=2)),
                ('rntrc', models.CharField(blank=True, max_length=8, null=True)),
                ('tara_kg', models.IntegerField(default=0, help_text='Tara em KG')),
                ('capacidade_kg', models.IntegerField(default=0, help_text='Capacidade em KG')),
                ('tipo_carroceria', models.CharField(default='00', help_text='00-não aplicável, 01-Aberta, 02-Fechada/Baú, etc', max_length=2)),
                ('mdfe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reboques', to='mdfe.manifestoeletronico')),
            ],
            options={
                'verbose_name': 'Reboque',
                'verbose_name_plural': 'Reboques',
                'db_table': 'mdfe_reboques',
            },
        ),
    ]
