# Generated by Django 6.0.2 on 2026-03-05 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mdfe', '0001_initial'),
    ]

    operations = [
    ]
