# Generated by Django 6.0.2 on 2026-03-05 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0107_formapagamento_dias_repasse_and_more'),
        ('mdfe', '0002_adicionar_campos_moc_v3'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifestoeletronico',
            name='averbacao',
            field=models.CharField(blank=True, help_text='Número de Averbação do Seguro', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='manifestoeletronico',
            name='contratante_cnpj',
            field=models.CharField(blank=True, help_text='CNPJ do Contratante do Serviço', max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='manifestoeletronico',
            name='contratante_rntrc',
            field=models.CharField(blank=True, help_text='RNTRC ANTT do Contratante', max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='manifestoeletronico',
            name='data_saida',
            field=models.DateField(blank=True, help_text='Data de saída da carga', null=True),
        ),
        migrations.AddField(
            model_name='manifestoeletronico',
            name='hora_saida',
            field=models.TimeField(blank=True, help_text='Hora de saída da carga', null=True),
        ),
        migrations.AddField(
            model_name='manifestoeletronico',
            name='produto_ncm',
            field=models.CharField(blank=True, help_text='NCM do Produto Predominante', max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='manifestoeletronico',
            name='responsavel_seguro_cpf_cnpj',
            field=models.CharField(blank=True, help_text='CPF/CNPJ do Responsável pela contratação do seguro', max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='manifestoeletronico',
            name='rntrc_prestador',
            field=models.CharField(blank=True, help_text='RNTRC ANTT do Prestador do Serviço', max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='manifestoeletronico',
            name='tipo_carga',
            field=models.CharField(blank=True, help_text='01-Granel sólido, 02-Granel líquido, 03-Frigorificada, 04-Conteinerizada, 05-Carga Geral, 06-Neogranel, 07-Perigosa (IMO)', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='manifestoeletronico',
            name='tipo_emissao',
            field=models.IntegerField(default=1, help_text='1-Normal, 2-Contingência, 3-Regime Especial NFF'),
        ),
        migrations.AddField(
            model_name='manifestoeletronico',
            name='tomador_cliente',
            field=models.ForeignKey(blank=True, help_text='Cliente tomador do serviço (quando tipo_emitente=1 e tomador_servico=4)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mdfes_como_tomador', to='api.cliente'),
        ),
        migrations.AddField(
            model_name='manifestoeletronico',
            name='tomador_cpf_cnpj',
            field=models.CharField(blank=True, help_text='CPF/CNPJ do tomador (alternativa ao tomador_cliente)', max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='manifestoeletronico',
            name='tomador_ind_ie',
            field=models.IntegerField(blank=True, help_text='1-Contribuinte ICMS, 2-Isento, 9-Não Contribuinte. OBRIGATÓRIO quando tipo_emitente=1', null=True),
        ),
        migrations.AddField(
            model_name='manifestoeletronico',
            name='tomador_nome',
            field=models.CharField(blank=True, help_text='Nome/Razão Social do tomador', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='manifestoeletronico',
            name='tomador_servico',
            field=models.IntegerField(blank=True, help_text='0-Remetente, 1-Expedidor, 2-Recebedor, 3-Destinatário, 4-Outros. Obrigatório para tipo_emitente=1', null=True),
        ),
        migrations.AddField(
            model_name='manifestoeletronico',
            name='veiculo_capacidade_kg',
            field=models.IntegerField(default=0, help_text='Capacidade de carga do veículo em KG. OBRIGATÓRIO'),
        ),
        migrations.AddField(
            model_name='manifestoeletronico',
            name='veiculo_tara_kg',
            field=models.IntegerField(default=0, help_text='Tara do veículo em KG. OBRIGATÓRIO'),
        ),
        migrations.AddField(
            model_name='manifestoeletronico',
            name='veiculo_tipo_carroceria',
            field=models.CharField(blank=True, help_text='00-Não aplicável, 01-Aberta, 02-Fechada/Baú, 03-Graneleira, 04-Porta Container, 05-Sider. OBRIGATÓRIO', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='manifestoeletronico',
            name='veiculo_tipo_rodado',
            field=models.CharField(blank=True, help_text='01-Truck, 02-Toco, 03-Cavalo, 04-VAN, 05-Utilitário, 06-Outros. OBRIGATÓRIO', max_length=2, null=True),
        ),
        migrations.CreateModel(
            name='MDFePagamento',
            fields=[
                ('id_pagamento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_pagamento', models.CharField(choices=[('01', '01 - Dinheiro'), ('02', '02 - Vale Pedágio'), ('03', '03 - Cartão de Crédito'), ('04', '04 - Cartão de Débito'), ('05', '05 - Cheque'), ('10', '10 - Boleto Bancário'), ('11', '11 - Depósito Bancário'), ('12', '12 - PIX'), ('99', '99 - Outros')], default='01', max_length=2)),
                ('responsavel_pagamento', models.CharField(choices=[('1', '1 - Emitente'), ('2', '2 - Destinatário'), ('3', '3 - Expedidor'), ('4', '4 - Recebedor'), ('5', '5 - Remetente')], default='1', max_length=1)),
                ('componente', models.CharField(blank=True, help_text='Vale Pedágio, Impostos, Taxas, Contribuições', max_length=50, null=True)),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('conta_bancaria', models.CharField(blank=True, max_length=30, null=True)),
                ('chave_pix', models.CharField(blank=True, max_length=100, null=True)),
                ('mdfe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='mdfe.manifestoeletronico')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'db_table': 'mdfe_pagamento',
            },
        ),
        migrations.CreateModel(
            name='MDFeValePedagio',
            fields=[
                ('id_vale_pedagio', models.AutoField(primary_key=True, serialize=False)),
                ('categoria_veiculo', models.CharField(blank=True, choices=[('01', '01 - Eixo simples/Rodado simples'), ('02', '02 - Eixo simples/Rodado duplo'), ('03', '03 - Eixo duplo'), ('04', '04 - Eixo triplo')], max_length=2, null=True)),
                ('tipo_vale', models.CharField(choices=[('01', '01 - TAG/OBU'), ('02', '02 - Cupom papel'), ('03', '03 - Vale eletrônico')], default='01', max_length=2)),
                ('cnpj_fornecedor', models.CharField(blank=True, max_length=14, null=True)),
                ('cpf_cnpj_portador', models.CharField(blank=True, max_length=14, null=True)),
                ('numero_comprovante', models.CharField(blank=True, max_length=20, null=True)),
                ('valor_pedagio', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('mdfe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vales_pedagio', to='mdfe.manifestoeletronico')),
            ],
            options={
                'verbose_name': 'Vale Pedágio',
                'verbose_name_plural': 'Vales Pedágio',
                'db_table': 'mdfe_vale_pedagio',
            },
        ),
    ]
