# Generated by Django 6.0.2 on 2026-03-05 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdfe', '0003_manifestoeletronico_averbacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mdfecarregamento',
            name='municipio_cep',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='mdfedescarregamento',
            name='municipio_cep',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
