# Generated by Django 6.0.5 on 2026-06-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdfe', '0004_mdfecarregamento_municipio_cep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifestoeletronico',
            name='ciot_cpf_cnpj',
            field=models.CharField(blank=True, help_text='CPF/CNPJ do contratante do CIOT', max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='manifestoeletronico',
            name='distancia_km',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Distância percorrida em KM', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='manifestoeletronico',
            name='numero_ciot',
            field=models.CharField(blank=True, help_text='Código CIOT (12 dígitos)', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='manifestoeletronico',
            name='tipo_carga',
            field=models.CharField(blank=True, choices=[('01', 'Granel sólido'), ('02', 'Granel líquido'), ('03', 'Frigorificada'), ('04', 'Conteinerizada'), ('05', 'Carga Geral'), ('06', 'Neogranel'), ('07', 'Perigosa (Granel)'), ('08', 'Perigosa (Frigorificada)'), ('09', 'Perigosa (Carga Geral)'), ('10', 'Outros'), ('11', 'Carga Geral e Granel')], help_text='01-Granel sólido, 02-Granel líquido, 03-Frigorificada, 04-Conteinerizada, 05-Carga Geral, 06-Neogranel, 07-Perigosa (IMO)', max_length=2, null=True),
        ),
    ]
