# Generated by Django 6.0 on 2025-12-13 11:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EscritorioContabilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=18, unique=True, validators=[django.core.validators.RegexValidator(message='CNPJ deve estar no formato: XX.XXX.XXX/XXXX-XX', regex='^\\d{2}\\.\\d{3}\\.\\d{3}/\\d{4}-\\d{2}$')], verbose_name='CNPJ')),
                ('razao_social', models.CharField(max_length=255, verbose_name='Razão Social')),
                ('telefone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Telefone deve estar no formato: (XX) XXXXX-XXXX', regex='^\\(\\d{2}\\)\\s?\\d{4,5}-\\d{4}$')], verbose_name='Telefone')),
                ('contador', models.CharField(max_length=255, verbose_name='Nome do Contador')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Escritório de Contabilidade',
                'verbose_name_plural': 'Escritórios de Contabilidade',
                'db_table': 'escritorio_contabilidade',
                'ordering': ['razao_social'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=255, verbose_name='Razão Social')),
                ('nome_fantasia', models.CharField(max_length=255, verbose_name='Nome Fantasia')),
                ('cnpj', models.CharField(max_length=18, unique=True, validators=[django.core.validators.RegexValidator(message='CNPJ deve estar no formato: XX.XXX.XXX/XXXX-XX', regex='^\\d{2}\\.\\d{3}\\.\\d{3}/\\d{4}-\\d{2}$')], verbose_name='CNPJ')),
                ('inscricao_estadual', models.CharField(blank=True, max_length=20, null=True, verbose_name='Inscrição Estadual')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
                ('numero', models.CharField(max_length=20, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=2, verbose_name='Estado')),
                ('cep', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='CEP deve estar no formato: XXXXX-XXX', regex='^\\d{5}-\\d{3}$')], verbose_name='CEP')),
                ('proprietario', models.CharField(max_length=255, verbose_name='Nome do Proprietário')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('cpf', models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(message='CPF deve estar no formato: XXX.XXX.XXX-XX', regex='^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$')], verbose_name='CPF do Proprietário')),
                ('telefone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Telefone deve estar no formato: (XX) XXXXX-XXXX', regex='^\\(\\d{2}\\)\\s?\\d{4,5}-\\d{4}$')], verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('regime_tributario', models.CharField(choices=[('SIMPLES', 'Simples Nacional'), ('LUCRO_REAL', 'Lucro Real'), ('LUCRO_PRESUMIDO', 'Lucro Presumido'), ('MEI', 'Microempreendedor Individual (MEI)'), ('IMUNES_ISENTAS', 'Imunes e Isentas')], default='SIMPLES', max_length=20, verbose_name='Regime Tributário')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('escritorio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='cadastro_clientes.escritoriocontabilidade', verbose_name='Escritório de Contabilidade')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
                'ordering': ['razao_social'],
                'indexes': [models.Index(fields=['cnpj'], name='cliente_cnpj_87b524_idx'), models.Index(fields=['razao_social'], name='cliente_razao_s_0f2c51_idx'), models.Index(fields=['regime_tributario'], name='cliente_regime__3050a0_idx')],
            },
        ),
    ]
