# Generated by Django 6.0 on 2026-01-06 13:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='CNPJ deve estar no formato: XX.XXX.XXX/XXXX-XX', regex='^\\d{2}\\.\\d{3}\\.\\d{3}/\\d{4}-\\d{2}$')], verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, validators=[django.core.validators.RegexValidator(message='CPF deve estar no formato: XXX.XXX.XXX-XX', regex='^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$')], verbose_name='CPF do Proprietário'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='escritorio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='cadastro_clientes.escritoriocontabilidade', verbose_name='Escritório de Contabilidade'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome_fantasia',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Fantasia'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='proprietario',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Proprietário'),
        ),
    ]
